In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import lxml

# Big 5 Table

In [2]:
dfs = pd.read_html('https://fbref.com/en/comps/Big5/Big-5-European-Leagues-Stats')

In [3]:
big_5_table = dfs[0]

In [4]:
big_5_table

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Inter,it ITA,1,27,23,3,1,69,13,...,72,2.67,58.0,21.0,37.0,1.37,W W W W W,52031,Lautaro Martínez - 23,Yann Sommer
1,2,Leverkusen,de GER,1,24,20,4,0,61,16,...,64,2.67,48.3,21.5,26.8,1.12,W W W W W,29978,Victor Boniface - 10,Lukáš Hrádecký
2,3,Real Madrid,es ESP,1,27,20,6,1,56,18,...,66,2.44,48.8,25.4,23.4,0.87,D W D W D,71486,Jude Bellingham - 16,Andriy Lunin
3,4,Liverpool,eng ENG,1,27,19,6,2,64,25,...,63,2.33,59.9,32.9,26.9,1.00,L W W W W,54101,Mohamed Salah - 15,Alisson
4,5,Manchester City,eng ENG,2,27,19,5,3,62,27,...,62,2.30,55.0,24.9,30.1,1.12,W D W W W,52996,Erling Haaland - 18,Ederson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,Darmstadt 98,de GER,18,24,2,7,15,24,58,...,13,0.54,24.4,49.4,-25.0,-1.04,L D L D L,17735,Tim Skarke - 6,Marcel Schuhen
92,93,Salernitana,it ITA,20,27,2,8,17,21,54,...,14,0.52,20.7,51.3,-30.5,-1.13,D L L L D,15101,Antonio Candreva - 5,Guillermo Ochoa
93,94,Burnley,eng ENG,19,27,3,4,20,25,60,...,13,0.48,25.0,47.3,-22.3,-0.83,D L L L L,21211,"Lyle Foster, Zeki Amdouni - 4",James Trafford
94,95,Sheffield Utd,eng ENG,20,27,3,4,20,22,72,...,13,0.48,24.0,53.7,-29.8,-1.10,L W L L L,30355,"Oliver McBurnie, Cameron Archer - 4",Wes Foderingham
95,96,Almería,es ESP,20,27,0,9,18,25,55,...,9,0.33,33.6,45.2,-11.7,-0.43,L D D D L,13825,Sergio Arribas - 6,Luís Maximiano

In [5]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time

# Initialise the webdriver
firefox_options = Options()
firefox_options.headless = True
driver = webdriver.Firefox(options=firefox_options)
driver.get('https://fbref.com/en/comps/Big5/Big-5-European-Leagues-Stats')

time.sleep(5)  # ensure the page is fully loaded

# Render the dynamic content to static HTML
html = driver.page_source
# print(html)

# Parse the static HTML
soup1 = BeautifulSoup(html, "html.parser")

# Close the webdriver
driver.close()

# League Summaries

In [6]:
premier_league_summary = soup1.find_all('div', {'class': 'data_grid_box'})[0]

In [7]:
print((premier_league_summary.find_all('p')[0].get_text()).replace("\xa0", " "))
print((premier_league_summary.find_all('p')[1].get_text()).replace("\xa0", " "))
print((premier_league_summary.find_all('p')[2].get_text()).replace("\xa0", " "))

Most Goals: Erling Haaland (Manchester City) - 18
Most Assists: Ollie Watkins (Aston Villa), Kieran Trippier (Newcastle United)... - 10
Most Clean Sheets: David Raya (Arsenal) - 9

In [8]:
serie_a_summary = soup1.find_all('div', {'class': 'data_grid_box'})[1]
print((serie_a_summary.find_all('p')[0].get_text()).replace("\xa0", " "))
print((serie_a_summary.find_all('p')[1].get_text()).replace("\xa0", " "))
print((serie_a_summary.find_all('p')[2].get_text()).replace("\xa0", " "))

Most Goals: Lautaro Martínez (Internazionale) - 23
Most Assists: Olivier Giroud (Milan) - 8
Most Clean Sheets: Yann Sommer (Internazionale) - 16

In [9]:
la_liga_summary = soup1.find_all('div', {'class': 'data_grid_box'})[2]
print((la_liga_summary.find_all('p')[0].get_text()).replace("\xa0", " "))
print((la_liga_summary.find_all('p')[1].get_text()).replace("\xa0", " "))
print((la_liga_summary.find_all('p')[2].get_text()).replace("\xa0", " "))

Most Goals: Jude Bellingham (Real Madrid) - 16
Most Assists: Alex Baena (Villarreal) - 9
Most Clean Sheets: Unai Simón (Athletic Club) - 13

In [10]:
ligue_1_summary = soup1.find_all('div', {'class': 'data_grid_box'})[3]
print((ligue_1_summary.find_all('p')[0].get_text()).replace("\xa0", " "))
print((ligue_1_summary.find_all('p')[1].get_text()).replace("\xa0", " "))
print((ligue_1_summary.find_all('p')[2].get_text()).replace("\xa0", " "))

Most Goals: Kylian Mbappé (Paris Saint-Germain) - 21
Most Assists: Pierre-Emerick Aubameyang (Marseille), Ousmane Dembélé (Paris Saint-Germain) - 7
Most Clean Sheets: Marcin Bułka (Nice), Lucas Chevalier (Lille) - 14

In [11]:
bundesliga_summary = soup1.find_all('div', {'class': 'data_grid_box'})[4]
print((bundesliga_summary.find_all('p')[0].get_text()).replace("\xa0", " "))
print((bundesliga_summary.find_all('p')[1].get_text()).replace("\xa0", " "))
print((bundesliga_summary.find_all('p')[2].get_text()).replace("\xa0", " "))

Most Goals: Harry Kane (Bayern Munich) - 27
Most Assists: Leroy Sané (Bayern Munich) - 11
Most Clean Sheets: Lukáš Hrádecký (Bayer Leverkusen) - 11

# Leaderboards for 77 metrics

In [12]:
#here are the leaderboards
#soup1.find_all('div',{'id':'all_leaders'})

In [13]:
data_grid_boxes = soup1.find_all('div', {'class': 'data_grid_box'})

all_leaderboards = []
for box in data_grid_boxes[5:83]:  # assuming indices 5 to 82 represent the leaderboards for different metrics
    metric_name = box.find('caption').text.strip()
    leaderboard_data = []
    for row in box.tbody.find_all("tr"):
        columns = row.find_all("td")
        if columns:
            rank = columns[0].text.strip()
            player = columns[1].text.strip()
            value = columns[2].text.strip()
            leaderboard_data.append([rank, player, value, metric_name])
    leaderboard_df = pd.DataFrame(leaderboard_data, columns=["Rank", "Player", "Value", "Metric"])
    all_leaderboards.append(leaderboard_df)

In [14]:
unique_metrics = pd.Series([df['Metric'].unique()[0] for df in all_leaderboards]).unique()

In [15]:
#use a dictionary comprehension to construct the dataframe with all the metric names and each of their indices
# Create a dataframe with metric names and their corresponding indices
index_mapping = pd.DataFrame({
    'Metric': unique_metrics,
    'Index': range(5,len(unique_metrics)+5)  # Use the length of unique_metrics to determine the range, # Adjust the range to start from 5 and end at len(unique_metrics) + 5
})

# Set the display option to show all rows
pd.set_option('display.max_rows', None)

# Display the dataframe
print(index_mapping)

# Reset the display option to its default value (optional)
pd.reset_option('display.max_rows')

                            Metric  Index
0                            Goals      5
1                         Goals/90      6
2                          Assists      7
3                       Assists/90      8
4                  Goals + Assists      9
5               Goals + Assists/90     10
6               Penalty Kicks Made     11
7                Non-Penalty Goals     12
8             Non-Penalty Goals/90     13
9   Non-Penalty Goals + Assists/90     14
10              xG: Expected Goals     15
11                           xG/90     16
12            npxG: Non-Penalty xG     17
13                         npxG/90     18
14        xAG: Exp. Assisted Goals     19
15                          xAG/90     20
16                     Shots Total     21
17                  Shots Total/90     22
18                 Shots on Target     23
19              Shots on target/90     24
20               Shots on Target %     25
21                      Goals/Shot     26
22            Goals/Shot on Target     27
23                       npxG/Shot     28
24                      Goals - xG     29
25        Non-Penalty Goals - npxG     30
26                      Key Passes     31
27               Pass Completion %     32
28    Progressive Passing Distance     33
29         Passes into Final Third     34
30        Passes into Penalty Area     35
31       Crosses into Penalty Area     36
32              Progressive Passes     37
33                   Through Balls     38
34            xA: Expected Assists     39
35                           xA/90     40
36                    Corner Kicks     41
37                         Crosses     42
38                 Throw-ins Taken     43
39           Shot-Creating Actions     44
40        Shot-Creating Actions/90     45
41           Goal-Creating Actions     46
42        Goal-Creating Actions/90     47
43                         Tackles     48
44                     Tackles Won     49
45               Dribblers Tackled     50
46          % of Dribblers Tackled     51
47                          Blocks     52
48                   Interceptions     53
49                      Clearances     54
50                         Touches     55
51             Successful Take-Ons     56
52            Successful Take-On %     57
53   Progressive Carrying Distance     58
54             Progressive Carries     59
55       Carries into Penalty Area     60
56          Progressive Passes Rec     61
57                         Minutes     62
58          Substitute Appearances     63
59                Points per Match     64
60                      Plus/Minus     65
61                   Plus/Minus/90     66
62                   xG Plus/Minus     67
63                xG Plus/Minus/90     68
64                    Yellow Cards     69
65                       Red Cards     70
66                     Aerials Won     71
67                % of Aerials Won     72
68                 Fouls Committed     73
69                     Fouls Drawn     74
70                       Own Goals     75
71                    Clean Sheets     76
72          Clean Sheet Percentage     77
73                           Saves     78
74                 Save Percentage     79
75                Goals Against/90     80
76                         PSxG-GA     81
77                      PSxG-GA/90     82

In [16]:
#more optimized version
goals = soup1.find_all('div', {'class':'data_grid_box'})[5]

goal_leaders = pd.DataFrame(
    [(goal_columns[0].text.strip(), goal_columns[1].text.strip(), goal_columns[2].text.strip()) for goal_row in goals.tbody.find_all("tr") if (goal_columns := goal_row.find_all("td"))],
    columns=["Rank", "Player", "Goals"]
)
goal_leaders

   Rank                               Player Goals
0    1.           Harry Kane • Bayern Munich    27
1    2.    Lautaro Martínez • Internazionale    23
2    3.  Kylian Mbappé • Paris Saint-Germain    21
3    4.          Serhou Guirassy • Stuttgart    20
4    5.     Erling Haaland • Manchester City    18
5    6.             Loïs Openda • RB Leipzig    17
6    7.        Jude Bellingham • Real Madrid    16
7                Ollie Watkins • Aston Villa    16
8    9.               Borja Mayoral • Getafe    15
9                  Dušan Vlahović • Juventus    15
10                 Mohamed Salah • Liverpool    15

In [17]:
goals = soup1.find_all('div', {'class':'data_grid_box'})[5] #there are leaderboards for ~77 metrics, first one is goals
goal_leaders = pd.DataFrame(
    columns=["Rank", "Player", "Goals"]
)

mylist = []
for goals_row in goals.tbody.find_all("tr"):
    goals_columns = goals_row.find_all("td")

    if goals_columns != []:
        rank = goals_columns[0].text.strip()
        player = goals_columns[1].text.strip()
        goals_nb = goals_columns[2].text.strip()

        mylist.append([rank, player, goals_nb])

goal_leaders = pd.DataFrame(
    mylist,
    columns=["Rank", "Player", "Goals"]
)
goal_leaders

   Rank                               Player Goals
0    1.           Harry Kane • Bayern Munich    27
1    2.    Lautaro Martínez • Internazionale    23
2    3.  Kylian Mbappé • Paris Saint-Germain    21
3    4.          Serhou Guirassy • Stuttgart    20
4    5.     Erling Haaland • Manchester City    18
5    6.             Loïs Openda • RB Leipzig    17
6    7.        Jude Bellingham • Real Madrid    16
7                Ollie Watkins • Aston Villa    16
8    9.               Borja Mayoral • Getafe    15
9                  Dušan Vlahović • Juventus    15
10                 Mohamed Salah • Liverpool    15

In [18]:
PSxGDF90 = soup1.find_all('div', {'class':'data_grid_box'})[82]

PSxGDF90_leaders = pd.DataFrame(
    [(PSxGDF90_columns[0].text.strip(), PSxGDF90_columns[1].text.strip(), PSxGDF90_columns[2].text.strip()) for PSxGDF90_row in PSxGDF90.tbody.find_all("tr") if (PSxGDF90_columns := PSxGDF90_row.find_all("td"))],
    columns=["Rank", "Player", "PSxG-GA/90"]
)
PSxGDF90_leaders

  Rank                                      Player PSxG-GA/90
0   1.  Gianluigi Donnarumma • Paris Saint-Germain      +0.44
1   2.                  Andriy Lunin • Real Madrid      +0.37
2   3.                          Brice Samba • Lens      +0.35
3   4.                 Michele Di Gregorio • Monza      +0.28
4   5.          Martin Dúbravka • Newcastle United      +0.27
5   6.                  Álvaro Vallés • Las Palmas      +0.26
6   7.                         Marco Bizot • Brest      +0.25
7   8.                       Marvin Schwäbe • Köln      +0.23
8   9.             Pietro Terracciano • Fiorentina      +0.22
9                           Rui Silva • Real Betis      +0.22

In [19]:
#all_leaderboards

In [20]:
#use a dictionary comprehension to construct the dataframe with all the metric names and each of their indices
# Create a dataframe with metric names and their corresponding indices
index_mapping = pd.DataFrame({
    'Metric': unique_metrics,
    'Index': range(len(unique_metrics))  # Use the length of unique_metrics to determine the range, # Adjust the range to start from 5 and end at len(unique_metrics) + 5
})

# Set the display option to show all rows
pd.set_option('display.max_rows', None)

# Display the dataframe
print(index_mapping)

# Reset the display option to its default value (optional)
pd.reset_option('display.max_rows')

                            Metric  Index
0                            Goals      0
1                         Goals/90      1
2                          Assists      2
3                       Assists/90      3
4                  Goals + Assists      4
5               Goals + Assists/90      5
6               Penalty Kicks Made      6
7                Non-Penalty Goals      7
8             Non-Penalty Goals/90      8
9   Non-Penalty Goals + Assists/90      9
10              xG: Expected Goals     10
11                           xG/90     11
12            npxG: Non-Penalty xG     12
13                         npxG/90     13
14        xAG: Exp. Assisted Goals     14
15                          xAG/90     15
16                     Shots Total     16
17                  Shots Total/90     17
18                 Shots on Target     18
19              Shots on target/90     19
20               Shots on Target %     20
21                      Goals/Shot     21
22            Goals/Shot on Target     22
23                       npxG/Shot     23
24                      Goals - xG     24
25        Non-Penalty Goals - npxG     25
26                      Key Passes     26
27               Pass Completion %     27
28    Progressive Passing Distance     28
29         Passes into Final Third     29
30        Passes into Penalty Area     30
31       Crosses into Penalty Area     31
32              Progressive Passes     32
33                   Through Balls     33
34            xA: Expected Assists     34
35                           xA/90     35
36                    Corner Kicks     36
37                         Crosses     37
38                 Throw-ins Taken     38
39           Shot-Creating Actions     39
40        Shot-Creating Actions/90     40
41           Goal-Creating Actions     41
42        Goal-Creating Actions/90     42
43                         Tackles     43
44                     Tackles Won     44
45               Dribblers Tackled     45
46          % of Dribblers Tackled     46
47                          Blocks     47
48                   Interceptions     48
49                      Clearances     49
50                         Touches     50
51             Successful Take-Ons     51
52            Successful Take-On %     52
53   Progressive Carrying Distance     53
54             Progressive Carries     54
55       Carries into Penalty Area     55
56          Progressive Passes Rec     56
57                         Minutes     57
58          Substitute Appearances     58
59                Points per Match     59
60                      Plus/Minus     60
61                   Plus/Minus/90     61
62                   xG Plus/Minus     62
63                xG Plus/Minus/90     63
64                    Yellow Cards     64
65                       Red Cards     65
66                     Aerials Won     66
67                % of Aerials Won     67
68                 Fouls Committed     68
69                     Fouls Drawn     69
70                       Own Goals     70
71                    Clean Sheets     71
72          Clean Sheet Percentage     72
73                           Saves     73
74                 Save Percentage     74
75                Goals Against/90     75
76                         PSxG-GA     76
77                      PSxG-GA/90     77

In [21]:
all_leaderboards[0]

   Rank                               Player Value Metric
0    1.           Harry Kane • Bayern Munich    27  Goals
1    2.    Lautaro Martínez • Internazionale    23  Goals
2    3.  Kylian Mbappé • Paris Saint-Germain    21  Goals
3    4.          Serhou Guirassy • Stuttgart    20  Goals
4    5.     Erling Haaland • Manchester City    18  Goals
5    6.             Loïs Openda • RB Leipzig    17  Goals
6    7.        Jude Bellingham • Real Madrid    16  Goals
7                Ollie Watkins • Aston Villa    16  Goals
8    9.               Borja Mayoral • Getafe    15  Goals
9                  Dušan Vlahović • Juventus    15  Goals
10                 Mohamed Salah • Liverpool    15  Goals

In [22]:
all_leaderboards[77]

  Rank                                      Player  Value      Metric
0   1.  Gianluigi Donnarumma • Paris Saint-Germain  +0.44  PSxG-GA/90
1   2.                  Andriy Lunin • Real Madrid  +0.37  PSxG-GA/90
2   3.                          Brice Samba • Lens  +0.35  PSxG-GA/90
3   4.                 Michele Di Gregorio • Monza  +0.28  PSxG-GA/90
4   5.          Martin Dúbravka • Newcastle United  +0.27  PSxG-GA/90
5   6.                  Álvaro Vallés • Las Palmas  +0.26  PSxG-GA/90
6   7.                         Marco Bizot • Brest  +0.25  PSxG-GA/90
7   8.                       Marvin Schwäbe • Köln  +0.23  PSxG-GA/90
8   9.             Pietro Terracciano • Fiorentina  +0.22  PSxG-GA/90
9                           Rui Silva • Real Betis  +0.22  PSxG-GA/90

# Top 4 Nationalities in Big 5

In [23]:
nations_soup = soup1.find('table', {'id':'nations'})
df_nationalities = pd.DataFrame(
    columns=["Nation", "# Players", "Min","List"]
)

mylist = []
for nations_row in nations_soup.tbody.find_all("tr"):
    nations_columns = nations_row.find_all("td")

    if nations_columns != []:
        nation = nations_columns[0].text.strip()
        players = nations_columns[1].text.strip()
        Min = nations_columns[2].text.strip()
        List = nations_columns[3].text.strip()

        mylist.append([nation, players, Min, List])

df_nationalities = pd.DataFrame(
    mylist,
    columns=["Nation", "# Players", "Min","List"]
)
df_nationalities

,Nation,# Players,Min,List
0,es Spain,477,"346,946","Álex Grimaldo, Borja Mayoral, Hugo Duro, Rodri..."
1,fr France,385,"286,145","Kylian Mbappé, Olivier Giroud, Antoine Griezma..."
2,it Italy,300,"204,366","Antonio Candreva, Andrea Pinamonti, Vincenzo G..."
3,de Germany,294,"233,891","Leroy Sané, Niclas Füllkrug, Pascal Groß, Flor..."
4,,,,View Complete Nationalities Table

# Other Big 5 Pages/Links

In [24]:
# Function to scrape tables from a single link and store them in named DataFrames
def scrape_tables_from_link(link):
    response = requests.get(link)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Extract specific tables and name them
        extracted_dataframes = {}
        
        # Extract nationality table
        nationality_table = soup.find('table', {'id': 'nations'})  # Replace 'table_id' with the actual ID of the table for nationalities
        if nationality_table:
            extracted_dataframes['nationalities'] = pd.read_html(str(nationality_table))[0]
        else:
            pass
        
        # Extract player wages table
        squad_wages_table = soup.find('table', {'id': 'squad_wages'})  # Replace 'table_id_2' with the actual ID of the player wages table
        if squad_wages_table:
            extracted_dataframes['squad_wages'] = pd.read_html(str(squad_wages_table))[0]
        else:
            pass
        
        player_wages_table = soup.find('table', {'id': 'player_wages'})  # Replace 'table_id_2' with the actual ID of the player wages table
        if player_wages_table:
            extracted_dataframes['player_wages'] = pd.read_html(str(player_wages_table))[0]
        else:
            pass
        # Add more table extractions as needed
        
        return extracted_dataframes
    else:
        print(f"Failed to fetch data from link: {link}")
        return None

# Main function to scrape tables from the first series of links
def scrape_first_series():
    # Define the first series of links
    links = [
        'https://fbref.com/en/comps/Big5/nations/Big-5-European-Leagues-Nationalities',
        'https://fbref.com/en/comps/Big5/wages/Big-5-European-Leagues-Wages'
    ]
    all_data_frames = {}
    
    # Scrape tables from each link
    for link in links:
        data_frames = scrape_tables_from_link(link)
        if data_frames:
            all_data_frames.update(data_frames)
    
    return all_data_frames

# Call the main function to scrape tables from the first series of links
first_series_tables = scrape_first_series()

# Now you can access the DataFrames directly using their names
nationalities_df = first_series_tables['nationalities']
player_wages_df = first_series_tables['player_wages']
squad_wages_df = first_series_tables['squad_wages']

## Nationalities Table

In [25]:
nationalities_df

,Rk,Nation,# Players,Min,List
0,1,es Spain,477,346946,"Álex Grimaldo, Borja Mayoral, Hugo Duro, Rodri..."
1,2,fr France,385,286145,"Kylian Mbappé, Olivier Giroud, Antoine Griezma..."
2,3,it Italy,300,204366,"Antonio Candreva, Andrea Pinamonti, Vincenzo G..."
3,4,de Germany,294,233891,"Leroy Sané, Niclas Füllkrug, Pascal Groß, Flor..."
4,5,eng England,276,175667,"Harry Kane, Ollie Watkins, Bukayo Saka, Jarrod..."
...,...,...,...,...,...
108,105,sl Sierra Leone,1,4,Yayah Kallon
109,106,ad Andorra,1,NaN,Iker Álvarez
110,107,ee Estonia,1,NaN,Karl Jakob Hein
111,108,id Indonesia,1,NaN,Justin Hubner
112,109,sy Syria,1,NaN,Aiham Ousou

## Squad Wages Table

In [26]:
squad_wages_df

,Rk,Squad,Comp,# Pl,Weekly Wages,Annual Wages,% Estimated
0,1,Paris S-G,fr Ligue 1,56,"€ 5,634,423 (£ 4,821,021, $6,114,095)","€ 292,990,000 (£ 250,693,116, $317,932,940)",33%
1,2,Real Madrid,es La Liga,47,"€ 5,435,577 (£ 4,650,881, $5,898,321)","€ 282,650,000 (£ 241,845,832, $306,712,674)",35%
2,3,Bayern Munich,de Bundesliga,48,"€ 4,948,462 (£ 4,234,087, $5,369,736)","€ 257,320,000 (£ 220,172,543, $279,226,271)",19%
3,4,Manchester Utd,eng Premier League,57,"€ 4,624,416 (£ 3,956,846, $5,016,249)","€ 240,469,607 (£ 205,756,000, $260,844,947)",24%
4,5,Manchester City,eng Premier League,47,"€ 4,510,062 (£ 3,859,000, $4,892,206)","€ 234,523,199 (£ 200,668,000, $254,394,692)",33%
...,...,...,...,...,...,...,...
91,92,Le Havre,fr Ligue 1,51,"€ 226,538 (£ 193,835, $245,824)","€ 11,780,000 (£ 10,079,404, $12,782,861)",100%
92,93,Metz,fr Ligue 1,53,"€ 225,192 (£ 192,683, $244,363)","€ 11,710,000 (£ 10,019,509, $12,706,900)",89%
93,94,Heidenheim,de Bundesliga,52,"€ 210,962 (£ 180,507, $228,921)","€ 10,970,000 (£ 9,386,340, $11,903,905)",100%
94,95,Toulouse,fr Ligue 1,57,"€ 189,615 (£ 162,242, $205,758)","€ 9,860,000 (£ 8,436,578, $10,699,407)",100%
95,96,Clermont Foot,fr Ligue 1,49,"€ 159,615 (£ 136,573, $173,204)","€ 8,300,000 (£ 7,101,790, $9,006,599)",100%

## Player Wages Table

In [27]:
player_wages_df

,Rk,Player,Nation,Pos,Squad,Age,Weekly Wages,Annual Wages,Notes
0,1,Kylian Mbappé,fr FRA,FW,Paris S-G,24,"€ 1,384,615 (£ 1,184,728, $1,502,491)","€ 72,000,000 (£ 61,605,872, $78,129,533)",NaN
1,2,Frenkie de Jong,nl NED,MF,Barcelona,26,"€ 721,154 (£ 617,046, $782,547)","€ 37,500,000 (£ 32,086,392, $40,692,465)",NaN
2,3,Robert Lewandowski,pl POL,FW,Barcelona,34,"€ 520,769 (£ 445,589, $565,104)","€ 27,080,000 (£ 23,170,653, $29,385,385)",NaN
3,4,Harry Kane,eng ENG,FW,Bayern Munich,30,"€ 480,769 (£ 411,364, $521,698)","€ 25,000,000 (£ 21,390,928, $27,128,310)",NaN
4,5,Toni Kroos,de GER,MF,Real Madrid,33,"€ 468,846 (£ 401,162, $508,760)","€ 24,380,000 (£ 20,860,433, $26,455,528)",NaN
...,...,...,...,...,...,...,...,...,...
95,96,Ferland Mendy,fr FRA,DF,Real Madrid,28,"€ 200,385 (£ 171,457, $217,444)","€ 10,420,000 (£ 8,915,739, $11,307,080)",NaN
96,97,James Maddison,eng ENG,MF,Tottenham,26,"€ 198,681 (£ 170,000, $215,516)","€ 10,331,418 (£ 8,840,000, $11,206,815)",NaN
97,98,Alessandro Bastoni,it ITA,DF,Inter,24,"€ 195,962 (£ 167,672, $212,644)","€ 10,190,000 (£ 8,718,942, $11,057,499)",NaN
98,99,Cristian Romero,ar ARG,DF,Tottenham,25,"€ 192,838 (£ 165,000, $209,177)","€ 10,027,553 (£ 8,580,000, $10,877,202)",NaN
99,100,Timo Werner,de GER,FW,Tottenham,27,"€ 192,838 (£ 165,000, $209,177)","€ 10,027,553 (£ 8,580,000, $10,877,202)",Unverified estimation

## Player Stats

### Player Standard Stats

In [28]:
player_standard_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/stats/players/Big-5-European-Leagues-Stats')

In [29]:
player_standard_stats = player_standard_stats_df[0]
player_standard_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ...  \
                    Age               Born           MP Starts  ...
0                24-063               2000           14     12  ...
1                23-137               2000           20      6  ...
2                20-194               2003            7      1  ...
3                36-161               1987           21     21  ...
4                23-347               2000           22     15  ...
...                 ...                ...          ...    ...  ...
2822             18-304               2005            1      0  ...
2823             25-081               1998           24     24  ...
2824             33-290               1990           20     13  ...
2825             33-290               1990            6      4  ...
2826             21-038               2003           23      9  ...

     Per 90 Minutes                                                       \
                Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0              0.08  0.08  0.00   0.08  0.00  0.07   0.07  0.00     0.07
1              0.00  0.15  0.15   0.15  0.12  0.13   0.25  0.12     0.25
2              0.89  0.89  0.00   0.89  0.11  0.07   0.19  0.11     0.19
3              0.00  0.14  0.14   0.14  0.11  0.01   0.12  0.11     0.12
4              0.00  0.00  0.00   0.00  0.05  0.03   0.09  0.05     0.09
...             ...   ...   ...    ...   ...   ...    ...   ...      ...
2822           0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.00     0.00
2823           0.25  0.51  0.17   0.42  0.23  0.26   0.48  0.16     0.42
2824           0.07  0.45  0.30   0.37  0.34  0.09   0.43  0.16     0.25
2825           0.23  0.23  0.00   0.23  0.17  0.14   0.30  0.17     0.30
2826           0.00  0.00  0.00   0.00  0.02  0.02   0.04  0.02     0.04

     Unnamed: 37_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2822             Matches
2823             Matches
2824             Matches
2825             Matches
2826             Matches

[2827 rows x 38 columns]

### Player Goalkeeping Stats

In [30]:
player_gk_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/keepers/players/Big-5-European-Leagues-Stats')
player_gk_stats = player_gk_stats_df[0]
player_gk_stats

    Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk                Player             Nation
0                    1               Alisson             br BRA
1                    2       Alphonse Areola             fr FRA
2                    3     Kepa Arrizabalaga             es ESP
3                    4          Noah Atubolu             de GER
4                    5           Emil Audero             it ITA
..                 ...                   ...                ...
174                169     Guglielmo Vicario             it ITA
175                170           Iván Villar             es ESP
176                171  Odisseas Vlachodimos             gr GRE
177                172         Robin Zentner             de GER
178                173      Michael Zetterer             de GER

    Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                   Pos              Squad                Comp
0                   GK          Liverpool  eng Premier League
1                   GK           West Ham  eng Premier League
2                   GK        Real Madrid          es La Liga
3                   GK           Freiburg       de Bundesliga
4                   GK              Inter          it Serie A
..                 ...                ...                 ...
174                 GK          Tottenham  eng Premier League
175                 GK         Celta Vigo          es La Liga
176                 GK    Nott'ham Forest  eng Premier League
177                 GK           Mainz 05       de Bundesliga
178                 GK      Werder Bremen       de Bundesliga

    Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ...  \
                   Age               Born           MP Starts  ...
0               31-157               1992           21     21  ...
1               31-009               1993           24     24  ...
2               29-156               1994           12     12  ...
3               21-287               2002           24     24  ...
4               27-049               1997            1      1  ...
..                 ...                ...          ...    ...  ...
174             27-152               1996           26     26  ...
175             26-242               1997           10     10  ...
176             29-316               1994            5      5  ...
177             29-131               1994           20     20  ...
178             28-239               1995           17     17  ...

    Performance               Penalty Kicks                     \
              D   L CS    CS%         PKatt PKA PKsv PKm Save%
0             6   2  7   33.3             1   1    0   0   0.0
1             6   8  4   16.7             6   4    2   0  33.3
2             2   1  6   50.0             0   0    0   0   NaN
3             6  10  7   29.2             3   3    0   0   0.0
4             0   0  1  100.0             0   0    0   0   NaN
..          ...  .. ..    ...           ...  ..  ...  ..   ...
174           5   6  5   19.2             6   6    0   0   0.0
175           3   6  0    0.0             2   1    1   0  50.0
176           0   4  1   20.0             1   1    0   0   0.0
177           8  10  3   15.0             2   2    0   0   0.0
178           6   5  5   29.4             2   2    0   0   0.0

    Unnamed: 27_level_0
                Matches
0               Matches
1               Matches
2               Matches
3               Matches
4               Matches
..                  ...
174             Matches
175             Matches
176             Matches
177             Matches
178             Matches

[179 rows x 28 columns]

### Player Advanced Goalkeeping Stats

In [31]:
player_gkAdv_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/keepersadv/players/Big-5-European-Leagues-Stats')
player_gkAdv_stats = player_gkAdv_stats_df[0]
player_gkAdv_stats

    Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk                Player             Nation
0                    1               Alisson             br BRA
1                    2       Alphonse Areola             fr FRA
2                    3     Kepa Arrizabalaga             es ESP
3                    4          Noah Atubolu             de GER
4                    5           Emil Audero             it ITA
..                 ...                   ...                ...
174                169     Guglielmo Vicario             it ITA
175                170           Iván Villar             es ESP
176                171  Odisseas Vlachodimos             gr GRE
177                172         Robin Zentner             de GER
178                173      Michael Zetterer             de GER

    Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                   Pos              Squad                Comp
0                   GK          Liverpool  eng Premier League
1                   GK           West Ham  eng Premier League
2                   GK        Real Madrid          es La Liga
3                   GK           Freiburg       de Bundesliga
4                   GK              Inter          it Serie A
..                 ...                ...                 ...
174                 GK          Tottenham  eng Premier League
175                 GK         Celta Vigo          es La Liga
176                 GK    Nott'ham Forest  eng Premier League
177                 GK           Mainz 05       de Bundesliga
178                 GK      Werder Bremen       de Bundesliga

    Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Goals  ...  \
                   Age               Born                90s    GA  ...
0               31-157               1992               21.0    19  ...
1               31-009               1993               23.5    38  ...
2               29-156               1994               12.0     9  ...
3               21-287               2002               24.0    44  ...
4               27-049               1997                1.0     0  ...
..                 ...                ...                ...   ...  ...
174             27-152               1996               26.0    39  ...
175             26-242               1997                9.3    15  ...
176             29-316               1994                5.0    12  ...
177             29-131               1994               20.0    35  ...
178             28-239               1995               17.0    20  ...

    Goal Kicks                Crosses           Sweeper                  \
           Att Launch% AvgLen     Opp Stp  Stp%    #OPA #OPA/90 AvgDist
0          103    36.9   34.6     234  12   5.1      26    1.24    17.1
1          184    65.2   46.1     377  20   5.3       5    0.21     9.3
2           59    23.7   28.9     138   4   2.9      10    0.83    15.5
3          167    70.7   53.5     308  15   4.9      24    1.00    14.7
4            4    50.0   49.0      17   0   0.0       2    2.00    29.0
..         ...     ...    ...     ...  ..   ...     ...     ...     ...
174        159    17.6   23.4     373  24   6.4      55    2.12    17.2
175         80    68.8   49.6     121   5   4.1       7    0.76    12.8
176         44    61.4   44.3      92   3   3.3       2    0.40    10.3
177        113    51.3   41.9     250  26  10.4      29    1.45    16.6
178         81    33.3   36.3     250  23   9.2      18    1.06    14.7

    Unnamed: 34_level_0
                Matches
0               Matches
1               Matches
2               Matches
3               Matches
4               Matches
..                  ...
174             Matches
175             Matches
176             Matches
177             Matches
178             Matches

[179 rows x 35 columns]

### Player Shooting Stats

In [32]:
player_shooting_df = pd.read_html('https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats')
player_shooting_stats = player_shooting_df[0]
player_shooting_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...  \
                    Age               Born                90s      Gls  ...
0                24-063               2000               12.1        0  ...
1                23-137               2000                6.7        1  ...
2                20-194               2003                1.1        0  ...
3                36-161               1987               20.9        3  ...
4                23-347               2000               15.4        0  ...
...                 ...                ...                ...      ...  ...
2822             18-304               2005                0.0        0  ...
2823             25-081               1998               23.5        6  ...
2824             33-290               1990               13.4        5  ...
2825             33-290               1990                4.3        0  ...
2826             21-038               2003               10.3        0  ...

                       Expected                            Unnamed: 26_level_0
      Dist FK PK PKatt       xG npxG npxG/Sh  G-xG np:G-xG             Matches
0     23.9  0  0     0      0.0  0.0    0.02   0.0     0.0             Matches
1     16.3  0  0     0      0.8  0.8    0.16  +0.2    +0.2             Matches
2     15.1  0  0     0      0.1  0.1    0.06  -0.1    -0.1             Matches
3     13.7  0  0     0      2.2  2.2    0.14  +0.8    +0.8             Matches
4     21.6  0  0     0      0.8  0.8    0.17  -0.8    -0.8             Matches
...    ... .. ..   ...      ...  ...     ...   ...     ...                 ...
2822   NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
2823  20.9  2  2     2      5.4  3.8    0.08  +0.6    +0.2             Matches
2824  12.5  0  1     3      4.5  2.2    0.10  +0.5    +1.8             Matches
2825  11.7  0  0     0      0.7  0.7    0.09  -0.7    -0.7             Matches
2826  19.7  0  0     0      0.2  0.2    0.03  -0.2    -0.2             Matches

[2827 rows x 27 columns]

### Player Passing Stats

In [33]:
player_passing_df = pd.read_html('https://fbref.com/en/comps/Big5/passing/players/Big-5-European-Leagues-Stats')
player_passing_stats = player_passing_df[0]
player_passing_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Total  ...  \
                    Age               Born                90s   Cmp  ...
0                24-063               2000               12.1   379  ...
1                23-137               2000                6.7   146  ...
2                20-194               2003                1.1    41  ...
3                36-161               1987               20.9  1118  ...
4                23-347               2000               15.4   739  ...
...                 ...                ...                ...   ...  ...
2822             18-304               2005                0.0     0  ...
2823             25-081               1998               23.5  1229  ...
2824             33-290               1990               13.4   181  ...
2825             33-290               1990                4.3    43  ...
2826             21-038               2003               10.3   255  ...

     Unnamed: 23_level_0 Unnamed: 24_level_0 Expected        \
                     Ast                 xAG       xA A-xAG
0                      1                 0.8      0.9  +0.2
1                      0                 0.9      0.8  -0.9
2                      1                 0.1      0.1  +0.9
3                      0                 0.2      0.5  -0.2
4                      0                 0.5      1.1  -0.5
...                  ...                 ...      ...   ...
2822                   0                 0.0      0.0   0.0
2823                   6                 6.0      7.2   0.0
2824                   1                 1.2      0.5  -0.2
2825                   1                 0.6      0.1  +0.4
2826                   0                 0.2      0.4  -0.2

     Unnamed: 27_level_0 Unnamed: 28_level_0 Unnamed: 29_level_0  \
                      KP                 1/3                 PPA
0                      7                  22                  12
1                      9                  15                   1
2                      1                   4                   2
3                      5                  99                   2
4                      6                  83                   5
...                  ...                 ...                 ...
2822                   0                   0                   0
2823                  70                 117                  78
2824                  16                  18                   3
2825                   3                   1                   1
2826                   5                  27                   5

     Unnamed: 30_level_0 Unnamed: 31_level_0 Unnamed: 32_level_0
                   CrsPA                PrgP             Matches
0                      2                  40             Matches
1                      0                  15             Matches
2                      0                   5             Matches
3                      0                 100             Matches
4                      2                  73             Matches
...                  ...                 ...                 ...
2822                   0                   0             Matches
2823                   7                 230             Matches
2824                   0                  15             Matches
2825                   0                   2             Matches
2826                   1                  33             Matches

[2827 rows x 33 columns]

### Player Pass Types

In [34]:
player_passTypes_df = pd.read_html('https://fbref.com/en/comps/Big5/passing_types/players/Big-5-European-Leagues-Stats')
player_passTypes_stats = player_passTypes_df[0]
player_passTypes_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  \
                    Age               Born                90s
0                24-063               2000               12.1
1                23-137               2000                6.7
2                20-194               2003                1.1
3                36-161               1987               20.9
4                23-347               2000               15.4
...                 ...                ...                ...
2822             18-304               2005                0.0
2823             25-081               1998               23.5
2824             33-290               1990               13.4
2825             33-290               1990                4.3
2826             21-038               2003               10.3

     Unnamed: 9_level_0  ... Pass Types          Corner Kicks          \
                    Att  ...        Crs   TI  CK           In Out Str
0                   501  ...         11  105   0            0   0   0
1                   193  ...         12    1   6            2   3   0
2                    50  ...          0    1   0            0   0   0
3                  1334  ...          1   27   0            0   0   0
4                   828  ...          3    1   0            0   0   0
...                 ...  ...        ...  ...  ..          ...  ..  ..
2822                  0  ...          0    0   0            0   0   0
2823               1442  ...         50   10  18           14   1   0
2824                334  ...          1    0   0            0   0   0
2825                 82  ...          0    0   0            0   0   0
2826                324  ...          6    2   0            0   0   0

     Outcomes            Unnamed: 24_level_0
          Cmp Off Blocks             Matches
0         379   1     20             Matches
1         146   2      8             Matches
2          41   0      0             Matches
3        1118   6     15             Matches
4         739   2     14             Matches
...       ...  ..    ...                 ...
2822        0   0      0             Matches
2823     1229   9     27             Matches
2824      181   0      3             Matches
2825       43   0      3             Matches
2826      255   1     12             Matches

[2827 rows x 25 columns]

### Player Goal and Shot Creation

In [35]:
player_gca_df = pd.read_html('https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats')
player_gca_stats = player_gca_df[0]
player_gca_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  SCA  ...  \
                    Age               Born                90s  SCA  ...
0                24-063               2000               12.1   20  ...
1                23-137               2000                6.7   17  ...
2                20-194               2003                1.1    2  ...
3                36-161               1987               20.9   14  ...
4                23-347               2000               15.4   23  ...
...                 ...                ...                ...  ...  ...
2822             18-304               2005                0.0    0  ...
2823             25-081               1998               23.5  147  ...
2824             33-290               1990               13.4   33  ...
2825             33-290               1990                4.3    5  ...
2826             21-038               2003               10.3   15  ...

     SCA Types GCA       GCA Types                        Unnamed: 25_level_0
           Def GCA GCA90  PassLive PassDead TO Sh Fld Def             Matches
0            0   1  0.08         1        0  0  0   0   0             Matches
1            0   2  0.30         2        0  0  0   0   0             Matches
2            0   1  0.89         1        0  0  0   0   0             Matches
3            0   0  0.00         0        0  0  0   0   0             Matches
4            0   3  0.19         3        0  0  0   0   0             Matches
...        ...  ..   ...       ...      ... .. ..  ..  ..                 ...
2822         0   0  0.00         0        0  0  0   0   0             Matches
2823         0  13  0.55         9        2  0  1   1   0             Matches
2824         1   4  0.30         1        0  0  0   2   1             Matches
2825         0   1  0.23         1        0  0  0   0   0             Matches
2826         0   0  0.00         0        0  0  0   0   0             Matches

[2827 rows x 26 columns]

### Player Defense Stats

In [36]:
player_def_df = pd.read_html('https://fbref.com/en/comps/Big5/defense/players/Big-5-European-Leagues-Stats')
player_def_stats = player_def_df[0]
player_def_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Tackles  ...  \
                    Age               Born                90s     Tkl  ...
0                24-063               2000               12.1      28  ...
1                23-137               2000                6.7      12  ...
2                20-194               2003                1.1       2  ...
3                36-161               1987               20.9      41  ...
4                23-347               2000               15.4      18  ...
...                 ...                ...                ...     ...  ...
2822             18-304               2005                0.0       0  ...
2823             25-081               1998               23.5      33  ...
2824             33-290               1990               13.4       1  ...
2825             33-290               1990                4.3       3  ...
2826             21-038               2003               10.3      16  ...

     Challenges      Blocks          Unnamed: 21_level_0 Unnamed: 22_level_0  \
           Tkl% Lost Blocks  Sh Pass                 Int             Tkl+Int
0          63.3   11      9   5    4                   6                  34
1          50.0    7     16   0   16                   1                  13
2         100.0    0      2   0    2                   0                   2
3          53.1   15     34  22   12                  25                  66
4          46.2    7     10   1    9                  10                  28
...         ...  ...    ...  ..  ...                 ...                 ...
2822        NaN    0      0   0    0                   0                   0
2823       27.0   27     18   1   17                   7                  40
2824        0.0    3      0   0    0                   1                   2
2825       50.0    1      3   1    2                   0                   3
2826       40.0   15     10   2    8                   4                  20

     Unnamed: 23_level_0 Unnamed: 24_level_0 Unnamed: 25_level_0
                     Clr                 Err             Matches
0                     23                   0             Matches
1                      3                   0             Matches
2                      0                   0             Matches
3                     62                   1             Matches
4                     14                   0             Matches
...                  ...                 ...                 ...
2822                   1                   0             Matches
2823                   5                   0             Matches
2824                  13                   0             Matches
2825                   5                   0             Matches
2826                  15                   0             Matches

[2827 rows x 26 columns]

### Player Possession Stats

In [37]:
player_poss_df = pd.read_html('https://fbref.com/en/comps/Big5/possession/players/Big-5-European-Leagues-Stats')
player_poss_stats = player_poss_df[0]
player_poss_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Touches  ...  \
                    Age               Born                90s Touches  ...
0                24-063               2000               12.1     615  ...
1                23-137               2000                6.7     286  ...
2                20-194               2003                1.1      72  ...
3                36-161               1987               20.9    1562  ...
4                23-347               2000               15.4     934  ...
...                 ...                ...                ...     ...  ...
2822             18-304               2005                0.0       1  ...
2823             25-081               1998               23.5    1657  ...
2824             33-290               1990               13.4     421  ...
2825             33-290               1990                4.3     117  ...
2826             21-038               2003               10.3     428  ...

     Carries                              Receiving      Unnamed: 31_level_0
     TotDist PrgDist PrgC 1/3 CPA Mis Dis       Rec PrgR             Matches
0       1908     998   19  11   7  11   7       310   22             Matches
1       1055     482   13  11   1  24  12       189   35             Matches
2        193      50    2   0   1   5   4        46    7             Matches
3       6330    3525   27  15   0  18   3      1036    5             Matches
4       4004    1522    7  30   0  19  11       721   18             Matches
...      ...     ...  ...  ..  ..  ..  ..       ...  ...                 ...
2822       0       0    0   0   0   0   0         0    0             Matches
2823    5622    2468   66  55  24  35  43      1304  140             Matches
2824     529     151    3   6   1  22   8       352   33             Matches
2825     164      41    1   1   0  11   5       102   10             Matches
2826    1389     686   14  12   3  16  10       261   13             Matches

[2827 rows x 32 columns]

### Player Playing Time Stats

In [38]:
player_playingtime_df = pd.read_html('https://fbref.com/en/comps/Big5/playingtime/players/Big-5-European-Leagues-Stats')
player_playingtime_stats = player_playingtime_df[0]
player_playingtime_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4     James Abankwah             ie IRL
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
3519               3385       Oliwier Zych             pl POL
3520               3386    Martin Ødegaard             no NOR
3521               3387        Milan Đurić             ba BIH
3522               3388        Milan Đurić             ba BIH
3523               3389   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF            Udinese          it Serie A
4                    DF              Reims          fr Ligue 1
...                 ...                ...                 ...
3519                 GK        Aston Villa  eng Premier League
3520                 MF            Arsenal  eng Premier League
3521                 FW      Hellas Verona          it Serie A
3522                 FW              Monza          it Serie A
3523                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time        ...  \
                    Age               Born           MP   Min  ...
0                24-063               2000           14  1085  ...
1                23-137               2000           20   600  ...
2                20-194               2003            7   101  ...
3                20-051               2004            0   NaN  ...
4                36-161               1987           21  1881  ...
...                 ...                ...          ...   ...  ...
3519             19-253               2004            0   NaN  ...
3520             25-081               1998           24  2119  ...
3521             33-290               1990           20  1204  ...
3522             33-290               1990            6   391  ...
3523             21-038               2003           23   928  ...

     Team Success                    Team Success (xG)                       \
             onGA  +/-  +/-90 On-Off              onxG onxGA  xG+/- xG+/-90
0              29  -19  -1.58  -2.08              11.8  24.3  -12.5   -1.04
1              12   -4  -0.60  +0.09               5.9  11.0   -5.1   -0.76
2               2    0   0.00  -0.31               1.1   2.6   -1.5   -1.30
3             NaN  NaN    NaN    NaN               NaN   NaN    NaN     NaN
4              31   -6  -0.29  -1.58              28.0  26.7   +1.3   +0.06
...           ...  ...    ...    ...               ...   ...    ...     ...
3519          NaN  NaN    NaN    NaN               NaN   NaN    NaN     NaN
3520           19  +39  +1.66  -0.08              48.0  16.2  +31.8   +1.35
3521           21   -6  -0.45  -0.01              13.3  16.9   -3.7   -0.28
3522            5   -1  -0.23  -0.01               5.0   4.8   +0.1   +0.03
3523           26  -19  -1.84  -1.00               8.2  19.1  -10.9   -1.05

            Unnamed: 30_level_0
     On-Off             Matches
0     -1.60             Matches
1     -0.60             Matches
2     -1.14             Matches
3       NaN             Matches
4     -0.77             Matches
...     ...                 ...
3519    NaN             Matches
3520  -0.11             Matches
3521  +0.15             Matches
3522  +0.47             Matches
3523  +0.13             Matches

[3524 rows x 31 columns]

### Player Miscellaneous Stats

In [39]:
player_misc_df = pd.read_html('https://fbref.com/en/comps/Big5/misc/players/Big-5-European-Leagues-Stats')
player_misc_stats = player_misc_df[0]
player_misc_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Performance  \
                    Age               Born                90s        CrdY
0                24-063               2000               12.1           1
1                23-137               2000                6.7           3
2                20-194               2003                1.1           0
3                36-161               1987               20.9           3
4                23-347               2000               15.4           2
...                 ...                ...                ...         ...
2822             18-304               2005                0.0           0
2823             25-081               1998               23.5           2
2824             33-290               1990               13.4           2
2825             33-290               1990                4.3           1
2826             21-038               2003               10.3           3

      ...                               Aerial Duels              \
      ... Int TklW PKwon PKcon OG Recov          Won Lost   Won%
0     ...   6   18     0     1  0    69            4    9   30.8
1     ...   1    8     0     0  0    35            4   12   25.0
2     ...   0    2     0     0  0     5            3    0  100.0
3     ...  25   25     0     0  0   116           38   25   60.3
4     ...  10   12     0     3  0    81            2    6   25.0
...   ...  ..  ...   ...   ... ..   ...          ...  ...    ...
2822  ...   0    0     0     0  0     0            0    1    0.0
2823  ...   7   12     1     0  0   104            3    6   33.3
2824  ...   1    0     0     0  0    25          135   43   75.8
2825  ...   0    3     0     0  0    10           23   12   65.7
2826  ...   4    9     0     0  0    52           12   11   52.2

     Unnamed: 25_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2822             Matches
2823             Matches
2824             Matches
2825             Matches
2826             Matches

[2827 rows x 26 columns]

## Squad Stats

In [40]:
squad_standard_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/stats/squads/Big-5-European-Leagues-Stats')
squad_standard_stats = squad_standard_stats_df[0]

squad_gk_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/keepers/squads/Big-5-European-Leagues-Stats')
squad_gk_stats = squad_gk_stats_df[0]


squad_gkAdv_stats_df = pd.read_html('https://fbref.com/en/comps/Big5/keepersadv/squads/Big-5-European-Leagues-Stats')
squad_gkAdv_stats = squad_gkAdv_stats_df[0]


squad_shooting_df = pd.read_html('https://fbref.com/en/comps/Big5/shooting/squads/Big-5-European-Leagues-Stats')
squad_shooting_stats = squad_shooting_df[0]


squad_passing_df = pd.read_html('https://fbref.com/en/comps/Big5/passing/squads/Big-5-European-Leagues-Stats')
squad_passing_stats = squad_passing_df[0]


squad_passTypes_df = pd.read_html('https://fbref.com/en/comps/Big5/passing_types/squads/Big-5-European-Leagues-Stats')
squad_passTypes_stats = squad_passTypes_df[0]


squad_gca_df = pd.read_html('https://fbref.com/en/comps/Big5/gca/squads/Big-5-European-Leagues-Stats')
squad_gca_stats = squad_gca_df[0]


squad_def_df = pd.read_html('https://fbref.com/en/comps/Big5/defense/squads/Big-5-European-Leagues-Stats')
squad_def_stats = squad_def_df[0]


squad_poss_df = pd.read_html('https://fbref.com/en/comps/Big5/possession/squads/Big-5-European-Leagues-Stats')
squad_poss_stats = squad_poss_df[0]


squad_playingtime_df = pd.read_html('https://fbref.com/en/comps/Big5/playingtime/squads/Big-5-European-Leagues-Stats')
squad_playingtime_stats = squad_playingtime_df[0]

squad_misc_df = pd.read_html('https://fbref.com/en/comps/Big5/squads/players/Big-5-European-Leagues-Stats')
squad_misc_stats = player_misc_df[0]

### Squad Standard Stats

In [41]:
squad_standard_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Playing Time  \
                 # Pl                Age               Poss           MP
0                  28               26.4               42.6           27
1                  33               26.0               46.4           27
2                  25               25.5               61.1           27
3                  28               27.6               55.6           27
4                  28               27.0               50.2           27
..                ...                ...                ...          ...
91                 32               28.5               50.4           27
92                 28               27.8               47.3           24
93                 24               28.8               41.4           27
94                 27               26.2               47.6           24
95                 25               27.5               47.9           27

                       ... Per 90 Minutes                                 \
   Starts   Min   90s  ...            Gls   Ast   G+A  G-PK G+A-PK    xG
0     297  2430  27.0  ...           0.81  0.67  1.48  0.70   1.37  1.24
1     297  2430  27.0  ...           0.93  0.59  1.52  0.89   1.48  1.24
2     297  2430  27.0  ...           2.41  1.67  4.07  2.11   3.78  2.05
3     297  2430  27.0  ...           2.07  1.52  3.59  1.93   3.44  1.86
4     297  2430  27.0  ...           1.81  1.41  3.22  1.70   3.11  1.50
..    ...   ...   ...  ...            ...   ...   ...   ...    ...   ...
91    297  2430  27.0  ...           1.59  1.11  2.70  1.44   2.56  1.43
92    264  2160  24.0  ...           1.29  0.96  2.25  1.17   2.12  1.34
93    297  2430  27.0  ...           1.56  1.15  2.70  1.44   2.59  1.37
94    264  2160  24.0  ...           1.25  0.79  2.04  1.17   1.96  1.23
95    297  2430  27.0  ...           1.41  1.15  2.56  1.30   2.44  1.36


     xAG xG+xAG  npxG npxG+xAG
0   0.82   2.06  1.09     1.92
1   0.91   2.15  1.21     2.12
2   1.42   3.47  1.82     3.24
3   1.38   3.24  1.75     3.12
4   1.10   2.60  1.41     2.51
..   ...    ...   ...      ...
91  1.04   2.47  1.31     2.35
92  1.04   2.38  1.20     2.24
93  0.90   2.26  1.25     2.15
94  0.86   2.08  1.12     1.98
95  0.96   2.32  1.27     2.23

[96 rows x 34 columns]

### Squad Goalkeeping Stats

In [42]:
squad_gk_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Playing Time              Unnamed: 7_level_0  \
                 # Pl           MP Starts   Min                90s
0                   1           27     27  2430               27.0
1                   3           27     27  2430               27.0
2                   2           27     27  2430               27.0
3                   2           27     27  2430               27.0
4                   2           27     27  2430               27.0
..                ...          ...    ...   ...                ...
91                  2           27     27  2430               27.0
92                  2           24     24  2160               24.0
93                  2           27     27  2430               27.0
94                  2           24     24  2160               24.0
95                  2           27     27  2430               27.0

   Performance        ...                      Penalty Kicks               \
            GA  GA90  ...   W  D   L  CS   CS%         PKatt PKA PKsv PKm
0           33  1.22  ...   7  8  12   6  22.2             7   7    0   0
1           55  2.04  ...   0  9  18   4  14.8             9   6    1   2
2           23  0.85  ...  19  4   4  11  40.7             2   1    1   0
3           37  1.37  ...  17  4   6   6  22.2             0   0    0   0
4           30  1.11  ...  14  4   9  11  40.7             8   5    2   1
..         ...   ...  ...  .. ..  ..  ..   ...           ...  ..  ...  ..
91          49  1.81  ...   8  8  11   3  11.1             4   4    0   0
92          37  1.54  ...   8  6  10   6  25.0             4   4    0   0
93          47  1.74  ...  12  6   9   5  18.5             7   5    2   0
94          39  1.62  ...   6  7  11   3  12.5             2   2    0   0
95          43  1.59  ...  11  5  11   5  18.5             5   5    0   0


   Save%
0    0.0
1   14.3
2   50.0
3    NaN
4   28.6
..   ...
91   0.0
92   0.0
93  28.6
94   0.0
95   0.0

[96 rows x 23 columns]

### Squad Advanced Goalkeeping Stats

In [43]:
squad_gkAdv_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Goals                ... Passes  \
                 # Pl                90s    GA PKA FK  CK OG  ... AvgLen
0                   1               27.0    33   7  0   2  2  ...   43.9
1                   3               27.0    55   6  0   6  0  ...   24.1
2                   2               27.0    23   1  0   5  1  ...   30.0
3                   2               27.0    37   0  0  10  3  ...   27.5
4                   2               27.0    30   5  0   3  1  ...   29.5
..                ...                ...   ...  .. ..  .. ..  ...    ...
91                  2               27.0    49   4  1   7  1  ...   33.4
92                  2               24.0    37   4  0   4  1  ...   32.6
93                  2               27.0    47   5  0   4  1  ...   36.0
94                  2               24.0    39   2  1   3  2  ...   34.8
95                  2               27.0    43   5  1   3  1  ...   32.4

   Goal Kicks                Crosses           Sweeper
          Att Launch% AvgLen     Opp Stp  Stp%    #OPA #OPA/90 AvgDist
0         241    61.8   44.4     401  18   4.5      23    0.85    13.7
1         228    59.2   45.1     449  24   5.3      34    1.26    22.7
2         133    33.8   31.1     229  32  14.0      48    1.78    18.6
3         157    29.9   29.4     305  33  10.8      56    2.07    18.2
4         183    67.8   50.5     307  25   8.1      40    1.48    16.8
..        ...     ...    ...     ...  ..   ...     ...     ...     ...
91        242    33.9   31.3     502  24   4.8      25    0.93     NaN
92        201    22.4   28.1     359  30   8.4      27    1.13    14.7
93        230    58.3   42.6     441  25   5.7       6    0.22     8.3
94        184    47.3   38.6     340  19   5.6      38    1.58    16.5
95        212    50.5   39.2     413  38   9.2      20    0.74    12.7

[96 rows x 30 columns]

### Squad Shooting Stats

In [44]:
squad_shooting_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Standard                         ...  \
                 # Pl                90s      Gls   Sh  SoT  SoT%  Sh/90  ...
0                  28               27.0       22  337   89  26.4  12.48  ...
1                  33               27.0       25  331  108  32.6  12.26  ...
2                  25               27.0       65  453  148  32.7  16.78  ...
3                  28               27.0       56  394  146  37.1  14.59  ...
4                  28               27.0       49  380  138  36.3  14.07  ...
..                ...                ...      ...  ...  ...   ...    ...  ...
91                 32               27.0       43  320  117  36.6  11.85  ...
92                 28               24.0       31  279   80  28.7  11.62  ...
93                 24               27.0       42  309  102  33.0  11.44  ...
94                 27               24.0       30  295  109  36.9  12.29  ...
95                 25               27.0       38  319  113  35.4  11.81  ...

                            Expected
   G/SoT  Dist  FK PK PKatt       xG  npxG npxG/Sh  G-xG np:G-xG
0   0.21  17.5  14  3     5     33.5  29.5    0.09 -11.5   -10.5
1   0.22  18.9  14  1     1     33.6  32.8    0.10  -8.6    -8.8
2   0.39  16.0   4  8     8     55.3  49.3    0.11   9.7     7.7
3   0.36  16.2  13  4     4     50.2  47.2    0.12   5.8     4.8
4   0.33  15.8   5  3     3     40.6  38.2    0.10   8.4     7.8
..   ...   ...  .. ..   ...      ...   ...     ...   ...     ...
91  0.33  16.1   8  4     4     38.6  35.4    0.11   4.4     3.6
92  0.35  17.2  10  3     4     32.1  28.9    0.10  -1.1    -0.9
93  0.38  16.1  10  3     4     36.9  33.8    0.11   5.1     5.2
94  0.26  17.4  12  2     3     29.4  26.9    0.09   0.6     1.1
95  0.31  16.4   9  3     3     36.7  34.4    0.11   1.3     0.6

[96 rows x 22 columns]

### Squad Passing Stats

In [45]:
squad_passing_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0  Total                               \
                 # Pl                90s    Cmp    Att  Cmp% TotDist PrgDist
0                  28               27.0   7402  10287  72.0  138711   59092
1                  33               27.0   8784  11546  76.1  159998   60260
2                  25               27.0  14407  16908  85.2  236253   74956
3                  28               27.0  11920  14247  83.7  207726   70157
4                  28               27.0  11320  14127  80.1  198637   70446
..                ...                ...    ...    ...   ...     ...     ...
91                 32               27.0  10734  13124  81.8  192635   71853
92                 28               24.0   9018  11664  77.3  167214   64738
93                 24               27.0   9055  11800  76.7  157345   60948
94                 27               24.0   9067  11657  77.8  164726   61509
95                 25               27.0  10668  13367  79.8  177033   59778

    ...  Long Unnamed: 19_level_0 Unnamed: 20_level_0 Expected        \
    ...  Cmp%                 Ast                 xAG       xA A-xAG
0   ...  47.8                  18                22.3     21.5  -4.3
1   ...  48.1                  16                24.6     18.3  -8.6
2   ...  55.8                  45                38.3     40.7   6.7
3   ...  57.6                  41                37.2     34.0   3.8
4   ...  55.8                  38                29.6     26.7   8.4
..  ...   ...                 ...                 ...      ...   ...
91  ...  57.5                  30                28.1     27.8   1.9
92  ...  58.3                  23                24.9     27.3  -1.9
93  ...  47.7                  31                24.2     22.1   6.8
94  ...  53.6                  19                20.5     26.6  -1.5
95  ...  48.7                  31                25.8     21.5   5.2

   Unnamed: 23_level_0 Unnamed: 24_level_0 Unnamed: 25_level_0  \
                    KP                 1/3                 PPA
0                  243                 685                 193
1                  236                 621                 154
2                  353                1189                 378
3                  308                 883                 276
4                  297                 854                 260
..                 ...                 ...                 ...
91                 251                 822                 225
92                 225                 611                 195
93                 217                 703                 155
94                 223                 683                 184
95                 240                 674                 185

   Unnamed: 26_level_0 Unnamed: 27_level_0
                 CrsPA                PrgP
0                   81                 934
1                   63                 790
2                   51                1571
3                   54                1122
4                   84                1225
..                 ...                 ...
91                  58                1072
92                  58                 815
93                  45                 871
94                  49                 889
95                  48                 874

[96 rows x 28 columns]

### Squad Pass Types Stats

In [46]:
squad_passTypes_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Pass Types        \
                 # Pl                90s                Att       Live  Dead
0                  28               27.0              10287       8875  1361
1                  33               27.0              11546      10125  1366
2                  25               27.0              16908      15741  1105
3                  28               27.0              14247      12911  1307
4                  28               27.0              14127      12834  1248
..                ...                ...                ...        ...   ...
91                 32               27.0              13124      11702  1351
92                 28               24.0              11664      10541  1066
93                 24               27.0              11800      10545  1207
94                 27               24.0              11657      10432  1192
95                 25               27.0              13367      12123  1192

                                Corner Kicks         Outcomes
     FK  TB   Sw  Crs   TI   CK           In Out Str      Cmp Off Blocks
0   356  22   89  617  566  138           31  57   3     7402  51    256
1   388  25   84  493  540  128           51  48   0     8784  55    224
2   317  79   50  514  401  204          166   1   0    14407  62    215
3   452  63   75  483  466  168          106   9   2    11920  29    245
4   310  25   95  532  546  153           73  53   1    11320  45    279
..  ...  ..  ...  ...  ...  ...          ...  ..  ..      ...  ..    ...
91  404  50  106  422  494  137           59  46   0    10734  71    247
92  328  37   71  364  396   80           32  38   0     9018  57    235
93  296  48  108  465  496  111           66  41   0     9055  48    300
94  347  25   54  420  495  103           63  35   0     9067  33    248
95  306  41   95  437  486  117           56  33   8    10668  52    239

[96 rows x 20 columns]

### Squad Goal and Shot Creation Stats

In [47]:
squad_gca_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0  SCA        SCA Types               \
                 # Pl                90s  SCA  SCA90  PassLive PassDead  TO
0                  28               27.0  605  22.41       420       58  46
1                  33               27.0  557  20.63       388       49  33
2                  25               27.0  828  30.67       641       64  42
3                  28               27.0  706  26.15       520       58  37
4                  28               27.0  679  25.15       506       60  38
..                ...                ...  ...    ...       ...      ...  ..
91                 32               27.0  587  21.74       427       52  36
92                 28               24.0  497  20.71       382       34  27
93                 24               27.0  544  20.15       365       65  37
94                 27               24.0  527  21.96       390       38  29
95                 25               27.0  560  20.74       391       50  44

    ...          GCA       GCA Types
    ... Fld Def  GCA GCA90  PassLive PassDead TO  Sh Fld Def
0   ...  32   9   40  1.48        29        1  4   3   3   0
1   ...  36  14   40  1.48        22        3  6   5   3   1
2   ...  25  10  113  4.19        70       15  8   9  11   0
3   ...  25   8  100  3.70        70        7  5   9   7   2
4   ...  26   8   87  3.22        71        6  1   6   3   0
..  ...  ..  ..  ...   ...       ...      ... ..  ..  ..  ..
91  ...  20  10   74  2.74        46        8  4  10   5   1
92  ...  23   7   57  2.37        47        1  3   2   4   0
93  ...  30  15   75  2.78        51        7  5   7   3   2
94  ...  30   3   54  2.25        42        0  2   8   2   0
95  ...  31   9   67  2.48        43        6  7   5   4   2

[96 rows x 21 columns]

### Squad Defense Stats

In [48]:
squad_def_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Tackles                               \
                 # Pl                90s     Tkl TklW Def 3rd Mid 3rd Att 3rd
0                  28               27.0     394  243     187     163      44
1                  33               27.0     469  269     269     158      42
2                  25               27.0     429  245     177     173      79
3                  28               27.0     388  229     183     157      48
4                  28               27.0     435  268     200     169      66
..                ...                ...     ...  ...     ...     ...     ...
91                 32               27.0     416  251     206     162      48
92                 28               24.0     414  248     207     164      43
93                 24               27.0     486  307     249     181      56
94                 27               24.0     381  216     191     139      51
95                 25               27.0     512  305     296     164      52

    ... Challenges            Blocks           Unnamed: 17_level_0  \
    ...        Att  Tkl% Lost Blocks   Sh Pass                 Int
0   ...        426  46.2  229    258   77  181                 190
1   ...        426  48.1  221    308  100  208                 209
2   ...        379  53.6  176    302   76  226                 201
3   ...        383  48.0  199    271   72  199                 177
4   ...        421  48.5  217    347   83  264                 249
..  ...        ...   ...  ...    ...  ...  ...                 ...
91  ...        405  48.1  210    284   99  185                 218
92  ...        423  51.3  206    314  111  203                 194
93  ...        413  54.0  190    351  129  222                 268
94  ...        382  49.5  193    310   76  234                 212
95  ...        422  52.4  201    359  119  240                 223

   Unnamed: 18_level_0 Unnamed: 19_level_0 Unnamed: 20_level_0
               Tkl+Int                 Clr                 Err
0                  584                 601                   3
1                  678                 586                   9
2                  630                 339                  13
3                  565                 434                   6
4                  684                 430                   6
..                 ...                 ...                 ...
91                 634                 606                  12
92                 608                 553                   7
93                 754                 678                   6
94                 593                 567                   7
95                 735                 605                  12

[96 rows x 21 columns]

### Squad Possession Stats

In [49]:
squad_poss_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Touches          \
                 # Pl               Poss                90s Touches Def Pen
0                  28               42.6               27.0   13186    1560
1                  33               46.4               27.0   14618    1841
2                  25               61.1               27.0   19647    1329
3                  28               55.6               27.0   16940    1870
4                  28               50.2               27.0   17089    1623
..                ...                ...                ...     ...     ...
91                 32               50.4               27.0   16115    2039
92                 28               47.3               24.0   14417    1782
93                 24               41.4               27.0   15009    1857
94                 27               47.6               24.0   14347    1517
95                 25               47.9               27.0   16486    1934

                    ... Carries                                           \
   Def 3rd Mid 3rd  ... Carries TotDist PrgDist PrgC  1/3  CPA  Mis  Dis
0     4353    5595  ...    6305   35828   19298  422  281  106  399  218
1     5364    6474  ...    7876   42548   21670  418  296   88  377  185
2     4815    8617  ...   12350   60315   31078  609  411  224  368  273
3     5635    7355  ...   10701   58695   31128  585  372  165  345  305
4     5511    7454  ...    9497   49485   24181  513  346  116  450  266
..     ...     ...  ...     ...     ...     ...  ...  ...  ...  ...  ...
91    5701    6838  ...    8643   48059   24159  444  350  128  405  252
92    5428    6421  ...    8075   41749   20942  343  247   74  380  180
93    5250    6601  ...    8123   44123   21064  392  277  118  359  264
94    4852    6468  ...    7669   38298   18708  308  209   75  376  175
95    5930    7143  ...    9359   52213   26812  511  385  127  388  262

   Receiving
         Rec  PrgR
0       7312   928
1       8703   775
2      14269  1557
3      11681  1112
4      11234  1210
..       ...   ...
91     10609  1064
92      8929   809
93      8975   859
94      8990   881
95     10570   858

[96 rows x 28 columns]

### Squad Playing Time Stats

In [50]:
squad_playingtime_stats

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Playing Time                         \
                 # Pl                Age           MP   Min Mn/MP Min%   90s
0                  28               26.4           27  2430    90  100  27.0
1                  33               26.0           27  2430    90  100  27.0
2                  25               25.5           27  2430    90  100  27.0
3                  28               27.6           27  2430    90  100  27.0
4                  28               27.0           27  2430    90  100  27.0
..                ...                ...          ...   ...   ...  ...   ...
91                 32               28.5           27  2430    90  100  27.0
92                 28               27.8           24  2160    90  100  24.0
93                 24               28.8           27  2430    90  100  27.0
94                 27               26.2           24  2160    90  100  24.0
95                 25               27.5           27  2430    90  100  27.0

    ...  Subs Team Success                    Team Success (xG)              \
    ... unSub          PPM onG onGA +/- +/-90              onxG onxGA xG+/-
0   ...   186         1.07  25   33  -8 -0.30              33.5  32.4   1.1
1   ...   181         0.33  25   55 -30 -1.11              33.6  45.2 -11.7
2   ...   131         2.26  68   23  45  1.67              55.3  18.4  36.9
3   ...   133         2.04  59   37  22  0.81              50.2  38.3  11.9
4   ...   184         1.70  49   30  19  0.70              40.6  29.3  11.3
..  ...   ...          ...  ..  ...  ..   ...               ...   ...   ...
91  ...   135         1.19  43   49  -6 -0.22              38.6  42.5  -3.9
92  ...   103         1.25  33   37  -4 -0.17              32.1  38.4  -6.3
93  ...   168         1.56  43   47  -4 -0.15              36.9  49.6 -12.7
94  ...   107         1.04  30   39  -9 -0.37              29.4  33.0  -3.6
95  ...   141         1.41  40   43  -3 -0.11              36.7  45.3  -8.5


   xG+/-90
0     0.04
1    -0.43
2     1.37
3     0.44
4     0.42
..     ...
91   -0.15
92   -0.26
93   -0.47
94   -0.15
95   -0.32

[96 rows x 25 columns]

### Squad Miscellaneous Stats

In [51]:
squad_misc_stats

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2822               2715     Lovro Zvonarek             hr CRO
2823               2716    Martin Ødegaard             no NOR
2824               2717        Milan Đurić             ba BIH
2825               2718        Milan Đurić             ba BIH
2826               2719   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2822                 MF      Bayern Munich       de Bundesliga
2823                 MF            Arsenal  eng Premier League
2824                 FW      Hellas Verona          it Serie A
2825                 FW              Monza          it Serie A
2826                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Performance  \
                    Age               Born                90s        CrdY
0                24-063               2000               12.1           1
1                23-137               2000                6.7           3
2                20-194               2003                1.1           0
3                36-161               1987               20.9           3
4                23-347               2000               15.4           2
...                 ...                ...                ...         ...
2822             18-304               2005                0.0           0
2823             25-081               1998               23.5           2
2824             33-290               1990               13.4           2
2825             33-290               1990                4.3           1
2826             21-038               2003               10.3           3

      ...                               Aerial Duels              \
      ... Int TklW PKwon PKcon OG Recov          Won Lost   Won%
0     ...   6   18     0     1  0    69            4    9   30.8
1     ...   1    8     0     0  0    35            4   12   25.0
2     ...   0    2     0     0  0     5            3    0  100.0
3     ...  25   25     0     0  0   116           38   25   60.3
4     ...  10   12     0     3  0    81            2    6   25.0
...   ...  ..  ...   ...   ... ..   ...          ...  ...    ...
2822  ...   0    0     0     0  0     0            0    1    0.0
2823  ...   7   12     1     0  0   104            3    6   33.3
2824  ...   1    0     0     0  0    25          135   43   75.8
2825  ...   0    3     0     0  0    10           23   12   65.7
2826  ...   4    9     0     0  0    52           12   11   52.2

     Unnamed: 25_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2822             Matches
2823             Matches
2824             Matches
2825             Matches
2826             Matches

[2827 rows x 26 columns]