In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json

In [2]:
link = 'https://www.fotmob.com/leagues/55/overview/serie'
res = requests.get(link)
soup = BeautifulSoup(res.content, 'lxml')
scripts = soup.find_all('script')

In [11]:
data = scripts[31].string
before, sep, after = data.partition(',"seo"')

In [18]:
#correcting the JSON string in order to be able to parse it
data = json.loads(before)
data = data['props']['pageProps']

In [19]:
data['details']

{'id': 55,
 'type': 'league',
 'name': 'Serie A',
 'selectedSeason': '2023/2024',
 'latestSeason': '2023/2024',
 'shortName': 'Serie A',
 'country': 'ITA',
 'faqJSONLD': None,
 'breadcrumbJSONLD': {'@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  'itemListElement': [{'@type': 'ListItem',
    'position': 1,
    'name': 'Home',
    'item': 'https://www.fotmob.com'},
   {'@type': 'ListItem',
    'position': 2,
    'name': 'Serie A',
    'item': 'https://www.fotmob.com/leagues/55/overview/serie'}]}}

In [233]:
pd.json_normalize(data['table'][0]['data']['table']['all'])

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Inter,Inter,8636,/teams/8636/overview/inter,None,None,23,19,3,1,55-12,43,60,1,#2AD572
1,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,24,16,5,3,36-15,21,53,2,#2AD572
2,AC Milan,AC Milan,8564,/teams/8564/overview/ac-milan,None,None,24,16,4,4,47-27,20,52,3,#2AD572
3,Atalanta,Atalanta,8524,/teams/8524/overview/atalanta,None,None,23,13,3,7,44-23,21,42,4,#2AD572
4,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,24,11,9,4,35-22,13,42,5,#0046A7
5,Roma,Roma,8686,/teams/8686/overview/roma,None,None,24,11,5,8,42-30,12,38,6,#02CCF0
6,Lazio,Lazio,8543,/teams/8543/overview/lazio,None,None,23,11,4,8,28-24,4,37,7,None
7,Fiorentina,Fiorentina,8535,/teams/8535/overview/fiorentina,None,None,24,11,4,9,36-28,8,37,8,None
8,SSC Napoli,SSC Napoli,9875,/teams/9875/overview/ssc-napoli,None,None,23,10,5,8,32-27,5,35,9,None
9,Torino,Torino,9804,/teams/9804/overview/torino,None,None,23,8,9,6,21-20,1,33,10,None
10,Monza,Monza,6504,/teams/6504/overview/monza,None,None,24,7,9,8,21-28,-7,30,11,None
11,Genoa,Genoa,10233,/teams/10233/overview/genoa,None,None,24,7,8,9,25-30,-5,29,12,None
12,Lecce,Lecce,9888,/teams/9888/overview/lecce,None,None,24,5,9,10,24-37,-13,24,13,None
13,Frosinone,Frosinone,9891,/teams/9891/overview/frosinone,None,None,24,6,5,13,32-49,-17,23,14,None
14,Udinese,Udinese,8600,/teams/8600/overview/udinese,None,None,24,3,13,8,24-37,-13,22,15,None
15,Empoli,Empoli,8534,/teams/8534/overview/empoli,None,None,24,5,6,13,18-37,-19,21,16,None
16,Sassuolo,Sassuolo,7943,/teams/7943/overview/sassuolo,None,None,23,5,5,13,29-42,-13,20,17,None
17,Hellas Verona,Hellas Verona,9876,/teams/9876/overview/hellas-verona,None,None,24,4,7,13,21-32,-11,19,18,#FF4646
18,Cagliari,Cagliari,8529,/teams/8529/overview/cagliari,None,None,24,4,6,14,22-45,-23,18,19,#FF4646
19,Salernitana,Salernitana,6480,/teams/6480/overview/salernitana,None,None,24,2,7,15,20-47,-27,13,20,#FF4646

In [234]:
pd.json_normalize(data['table'][0]['data']['table']['home'])

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,13,10,2,1,24-7,17,32,1,#2AD572
1,Inter,Inter,8636,/teams/8636/overview/inter,None,None,11,9,1,1,26-6,20,28,2,#2AD572
2,Atalanta,Atalanta,8524,/teams/8524/overview/atalanta,None,None,12,9,1,2,27-8,19,28,3,#2AD572
3,AC Milan,AC Milan,8564,/teams/8564/overview/ac-milan,None,None,12,9,1,2,21-7,14,28,4,#2AD572
4,Roma,Roma,8686,/teams/8686/overview/roma,None,None,13,8,3,2,30-13,17,27,5,#0046A7
5,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,12,8,3,1,17-6,11,27,6,#02CCF0
6,Fiorentina,Fiorentina,8535,/teams/8535/overview/fiorentina,None,None,12,7,2,3,22-12,10,23,7,None
7,Lazio,Lazio,8543,/teams/8543/overview/lazio,None,None,11,6,3,2,12-7,5,21,8,None
8,Torino,Torino,9804,/teams/9804/overview/torino,None,None,11,5,5,1,12-6,6,20,9,None
9,Frosinone,Frosinone,9891,/teams/9891/overview/frosinone,None,None,12,6,2,4,22-19,3,20,10,None
10,Lecce,Lecce,9888,/teams/9888/overview/lecce,None,None,12,5,4,3,15-17,-2,19,11,None
11,SSC Napoli,SSC Napoli,9875,/teams/9875/overview/ssc-napoli,None,None,11,5,2,4,16-15,1,17,12,None
12,Monza,Monza,6504,/teams/6504/overview/monza,None,None,12,4,5,3,12-11,1,17,13,None
13,Genoa,Genoa,10233,/teams/10233/overview/genoa,None,None,12,4,5,3,15-16,-1,17,14,None
14,Cagliari,Cagliari,8529,/teams/8529/overview/cagliari,None,None,12,4,3,5,15-21,-6,15,15,None
15,Hellas Verona,Hellas Verona,9876,/teams/9876/overview/hellas-verona,None,None,11,3,4,4,12-14,-2,13,16,None
16,Sassuolo,Sassuolo,7943,/teams/7943/overview/sassuolo,None,None,11,3,3,5,14-16,-2,12,17,None
17,Udinese,Udinese,8600,/teams/8600/overview/udinese,None,None,12,1,7,4,15-19,-4,10,18,#FF4646
18,Empoli,Empoli,8534,/teams/8534/overview/empoli,None,None,12,2,3,7,8-17,-9,9,19,#FF4646
19,Salernitana,Salernitana,6480,/teams/6480/overview/salernitana,None,None,13,1,4,8,13-27,-14,7,20,#FF4646

In [235]:
pd.json_normalize(data['table'][0]['data']['table']['away'])

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Inter,Inter,8636,/teams/8636/overview/inter,None,None,12,10,2,0,29-6,23,32,1,#2AD572
1,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,12,8,2,2,19-9,10,26,2,#2AD572
2,AC Milan,AC Milan,8564,/teams/8564/overview/ac-milan,None,None,12,7,3,2,26-20,6,24,3,#2AD572
3,SSC Napoli,SSC Napoli,9875,/teams/9875/overview/ssc-napoli,None,None,12,5,3,4,16-12,4,18,4,#2AD572
4,Lazio,Lazio,8543,/teams/8543/overview/lazio,None,None,12,5,1,6,16-17,-1,16,5,#0046A7
5,Atalanta,Atalanta,8524,/teams/8524/overview/atalanta,None,None,11,4,2,5,17-15,2,14,6,#02CCF0
6,Fiorentina,Fiorentina,8535,/teams/8535/overview/fiorentina,None,None,12,4,2,6,14-16,-2,14,7,None
7,Torino,Torino,9804,/teams/9804/overview/torino,None,None,12,3,4,5,9-14,-5,13,8,None
8,Monza,Monza,6504,/teams/6504/overview/monza,None,None,12,3,4,5,9-17,-8,13,9,None
9,Genoa,Genoa,10233,/teams/10233/overview/genoa,None,None,12,3,3,6,10-14,-4,12,10,None
10,Udinese,Udinese,8600,/teams/8600/overview/udinese,None,None,12,2,6,4,9-18,-9,12,11,None
11,Empoli,Empoli,8534,/teams/8534/overview/empoli,None,None,12,3,3,6,10-20,-10,12,12,None
12,Roma,Roma,8686,/teams/8686/overview/roma,None,None,11,3,2,6,12-17,-5,11,13,None
13,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,11,1,7,3,11-15,-4,10,14,None
14,Sassuolo,Sassuolo,7943,/teams/7943/overview/sassuolo,None,None,12,2,2,8,15-26,-11,8,15,None
15,Hellas Verona,Hellas Verona,9876,/teams/9876/overview/hellas-verona,None,None,13,1,3,9,9-18,-9,6,16,None
16,Salernitana,Salernitana,6480,/teams/6480/overview/salernitana,None,None,11,1,3,7,7-20,-13,6,17,None
17,Lecce,Lecce,9888,/teams/9888/overview/lecce,None,None,12,0,5,7,9-20,-11,5,18,#FF4646
18,Cagliari,Cagliari,8529,/teams/8529/overview/cagliari,None,None,12,0,3,9,7-24,-17,3,19,#FF4646
19,Frosinone,Frosinone,9891,/teams/9891/overview/frosinone,None,None,12,0,3,9,10-30,-20,3,20,#FF4646

In [236]:
pd.json_normalize(data['table'][0]['data']['table']['form'])

,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,pts,ongoing,idx,qualColor
0,Inter,Inter,False,8636,/teams/8636/overview/inter,5,5,0,0,13-4,9,15,None,1,#2AD572
1,Atalanta,Atalanta,False,8524,/teams/8524/overview/atalanta,5,4,1,0,15-3,12,13,None,2,#2AD572
2,AC Milan,AC Milan,False,8564,/teams/8564/overview/ac-milan,5,4,1,0,12-7,5,13,None,3,#2AD572
3,Bologna,Bologna,False,9857,/teams/9857/overview/bologna,5,3,1,1,13-6,7,10,None,4,#2AD572
4,Lazio,Lazio,False,8543,/teams/8543/overview/lazio,5,3,1,1,7-5,2,10,None,5,#0046A7
5,Torino,Torino,False,9804,/teams/9804/overview/torino,5,2,3,0,6-2,4,9,None,6,#02CCF0
6,Roma,Roma,False,8686,/teams/8686/overview/roma,5,3,0,2,11-9,2,9,None,7,None
7,Empoli,Empoli,False,8534,/teams/8534/overview/empoli,5,2,2,1,8-4,4,8,None,8,None
8,Genoa,Genoa,False,10233,/teams/10233/overview/genoa,5,2,2,1,5-6,-1,8,None,9,None
9,Juventus,Juventus,False,9885,/teams/9885/overview/juventus,5,2,1,2,7-3,4,7,None,10,None
10,SSC Napoli,SSC Napoli,False,9875,/teams/9875/overview/ssc-napoli,5,2,1,2,4-6,-2,7,None,11,None
11,Hellas Verona,Hellas Verona,False,9876,/teams/9876/overview/hellas-verona,5,1,2,2,5-6,-1,5,None,12,None
12,Udinese,Udinese,False,8600,/teams/8600/overview/udinese,5,1,2,2,5-7,-2,5,None,13,None
13,Monza,Monza,False,6504,/teams/6504/overview/monza,5,1,2,2,2-8,-6,5,None,14,None
14,Fiorentina,Fiorentina,False,8535,/teams/8535/overview/fiorentina,5,1,1,3,9-9,0,4,None,15,None
15,Sassuolo,Sassuolo,False,7943,/teams/7943/overview/sassuolo,5,1,1,3,4-9,-5,4,None,16,None
16,Frosinone,Frosinone,False,9891,/teams/9891/overview/frosinone,5,1,1,3,7-15,-8,4,None,17,None
17,Cagliari,Cagliari,False,8529,/teams/8529/overview/cagliari,5,1,0,4,5-13,-8,3,None,18,#FF4646
18,Lecce,Lecce,False,9888,/teams/9888/overview/lecce,5,1,0,4,4-12,-8,3,None,19,#FF4646
19,Salernitana,Salernitana,False,6480,/teams/6480/overview/salernitana,5,0,1,4,4-9,-5,1,None,20,#FF4646

In [237]:
pd.json_normalize(data['table'][0]['data']['table']['xg'])

,name,shortName,id,pageUrl,ongoing,played,wins,draws,losses,scoresStr,...,xgConceded,xPoints,position,xgDiff,xgConcededDiff,xPointsDiff,xPosition,idx,xPositionDiff,qualColor
0,Inter,Inter,8636,/teams/8636/overview/inter,None,23,19,3,1,55-12,...,19.0437,49.263657,1,-7.0798,7.0437,-10.736343,1,1,0,#2AD572
1,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,24,16,5,3,36-15,...,17.3265,46.288386,2,0.8949,2.3265,-6.711614,2,2,0,#2AD572
2,Roma,Roma,8686,/teams/8686/overview/roma,None,24,11,5,8,42-30,...,22.7273,40.547762,3,-8.2586,-7.2727,2.547762,3,3,3,#2AD572
3,SSC Napoli,SSC Napoli,9875,/teams/9875/overview/ssc-napoli,None,23,10,5,8,32-27,...,24.1515,39.881959,4,5.2181,-2.8485,4.881959,4,4,5,#2AD572
4,AC Milan,AC Milan,8564,/teams/8564/overview/ac-milan,None,24,16,4,4,47-27,...,29.7261,39.286394,5,-8.1784,2.7261,-12.713606,5,5,-2,#0046A7
5,Atalanta,Atalanta,8524,/teams/8524/overview/atalanta,None,23,13,3,7,44-23,...,23.4711,38.788038,6,-9.8888,0.4711,-3.211962,6,6,-2,#02CCF0
6,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,24,11,9,4,35-22,...,23.7192,37.061226,7,-5.3924,1.7192,-4.938774,7,7,-2,None
7,Lazio,Lazio,8543,/teams/8543/overview/lazio,None,23,11,4,8,28-24,...,24.4080,34.372868,8,0.2396,0.4080,-2.627132,8,8,-1,None
8,Fiorentina,Fiorentina,8535,/teams/8535/overview/fiorentina,None,24,11,4,9,36-28,...,31.8138,34.220998,9,-5.5344,3.8138,-2.779002,9,9,-1,None
9,Torino,Torino,9804,/teams/9804/overview/torino,None,23,8,9,6,21-20,...,22.1147,32.969916,10,2.7076,2.1147,-0.030084,10,10,0,None
10,Udinese,Udinese,8600,/teams/8600/overview/udinese,None,24,3,13,8,24-37,...,33.2107,29.871246,11,2.3433,-3.7893,7.871246,11,11,4,None
11,Genoa,Genoa,10233,/teams/10233/overview/genoa,None,24,7,8,9,25-30,...,24.9686,28.793100,12,-4.1466,-5.0314,-0.206900,12,12,0,None
12,Hellas Verona,Hellas Verona,9876,/teams/9876/overview/hellas-verona,None,24,4,7,13,21-32,...,30.1052,27.396663,13,1.9379,-1.8948,8.396663,13,13,5,None
13,Cagliari,Cagliari,8529,/teams/8529/overview/cagliari,None,24,4,6,14,22-45,...,36.3604,26.525935,14,4.7304,-8.6396,8.525935,14,14,5,None
14,Frosinone,Frosinone,9891,/teams/9891/overview/frosinone,None,24,6,5,13,32-49,...,38.8518,26.472962,15,-3.9120,-10.1482,3.472962,15,15,-1,None
15,Empoli,Empoli,8534,/teams/8534/overview/empoli,None,24,5,6,13,18-37,...,32.5412,26.457465,16,5.3980,-4.4588,5.457465,16,16,0,None
16,Sassuolo,Sassuolo,7943,/teams/7943/overview/sassuolo,None,23,5,5,13,29-42,...,35.0779,26.408750,17,-2.6493,-6.9221,6.408750,17,17,0,None
17,Lecce,Lecce,9888,/teams/9888/overview/lecce,None,24,5,9,10,24-37,...,37.1280,25.868457,18,2.7321,0.1280,1.868457,18,18,-5,#FF4646
18,Monza,Monza,6504,/teams/6504/overview/monza,None,24,7,9,8,21-28,...,35.0321,25.447200,19,3.5207,7.0321,-4.552800,19,19,-8,#FF4646
19,Salernitana,Salernitana,6480,/teams/6480/overview/salernitana,None,24,2,7,15,20-47,...,43.8547,16.487730,20,-1.0498,-3.1453,3.487730,20,20,0,#FF4646

In [239]:
data['table'][0]['teamForm']

{'6480': [{'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9875_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-ssc-napoli/27myp5#4230730',
   'date': None,
   'teamPageUrl': '/teams/9875/overview/ssc-napoli',
   'tooltipText': {'utcTime': '2024-01-13T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'SSC Napoli',
    'homeTeamId': 9875,
    'homeScore': 2,
    'awayTeam': 'Salernitana',
    'awayTeamId': 6480,
    'awayScore': 1},
   'score': '2 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/10233_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-genoa/2b5rh9#4230738',
   'date': None,
   'teamPageUrl': '/teams/10233/overview/genoa',
   'tooltipText': {'utcTime': '2024-01-21T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Salernitana',
    'homeTeamId': 6480,
    'homeScore': 1,
    'awayTeam': 'Genoa',
    'awayTeamId': 10233,
    'awayScore': 2},
   'score': '1 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8686_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-roma/1wha1b#4230753',
   'date': None,
   'teamPageUrl': '/teams/8686/overview/roma',
   'tooltipText': {'utcTime': '2024-01-29T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Salernitana',
    'homeTeamId': 6480,
    'homeScore': 1,
    'awayTeam': 'Roma',
    'awayTeamId': 8686,
    'awayScore': 2},
   'score': '1 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9804_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-torino/26y4ki#4230763',
   'date': None,
   'teamPageUrl': '/teams/9804/overview/torino',
   'tooltipText': {'utcTime': '2024-02-04T11:30:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Torino',
    'homeTeamId': 9804,
    'homeScore': 0,
    'awayTeam': 'Salernitana',
    'awayTeamId': 6480,
    'awayScore': 0},
   'score': '0 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8534_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-empoli/1v441n#4230771',
   'date': None,
   'teamPageUrl': '/teams/8534/overview/empoli',
   'tooltipText': {'utcTime': '2024-02-09T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Salernitana',
    'homeTeamId': 6480,
    'homeScore': 1,
    'awayTeam': 'Empoli',
    'awayTeamId': 8534,
    'awayScore': 3},
   'score': '1 - 3',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '6504': [{'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8636_xsmall.png',
   'linkToMatch': '/matches/monza-vs-inter/1w8tzq#4230733',
   'date': None,
   'teamPageUrl': '/teams/8636/overview/inter',
   'tooltipText': {'utcTime': '2024-01-13T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Monza',
    'homeTeamId': 6504,
    'homeScore': 1,
    'awayTeam': 'Inter',
    'awayTeamId': 8636,
    'awayScore': 5},
   'score': '1 - 5',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8534_xsmall.png',
   'linkToMatch': '/matches/monza-vs-empoli/1vbubb#4230735',
   'date': None,
   'teamPageUrl': '/teams/8534/overview/empoli',
   'tooltipText': {'utcTime': '2024-01-21T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Empoli',
    'homeTeamId': 8534,
    'homeScore': 3,
    'awayTeam': 'Monza',
    'awayTeamId': 6504,
    'awayScore': 0},
   'score': '3 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/7943_xsmall.png',
   'linkToMatch': '/matches/monza-vs-sassuolo/1q52rz#4230749',
   'date': None,
   'teamPageUrl': '/teams/7943/overview/sassuolo',
   'tooltipText': {'utcTime': '2024-01-28T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Monza',
    'homeTeamId': 6504,
    'homeScore': 1,
    'awayTeam': 'Sassuolo',
    'awayTeamId': 7943,
    'awayScore': 0},
   'score': '1 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8600_xsmall.png',
   'linkToMatch': '/matches/monza-vs-udinese/1vx5w8#4230762',
   'date': None,
   'teamPageUrl': '/teams/8600/overview/udinese',
   'tooltipText': {'utcTime': '2024-02-03T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Udinese',
    'homeTeamId': 8600,
    'homeScore': 0,
    'awayTeam': 'Monza',
    'awayTeamId': 6504,
    'awayScore': 0},
   'score': '0 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9876_xsmall.png',
   'linkToMatch': '/matches/monza-vs-hellas-verona/27vqfu#4230772',
   'date': None,
   'teamPageUrl': '/teams/9876/overview/hellas-verona',
   'tooltipText': {'utcTime': '2024-02-11T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Monza',
    'homeTeamId': 6504,
    'homeScore': 0,
    'awayTeam': 'Hellas Verona',
    'awayTeamId': 9876,
    'awayScore': 0},
   'score': '0 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '7943': [{'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8535_xsmall.png',
   'linkToMatch': '/matches/sassuolo-vs-fiorentina/28u7rc#4230719',
   'date': None,
   'teamPageUrl': '/teams/8535/overview/fiorentina',
   'tooltipText': {'utcTime': '2024-01-06T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Sassuolo',
    'homeTeamId': 7943,
    'homeScore': 1,
    'awayTeam': 'Fiorentina',
    'awayTeamId': 8535,
    'awayScore': 0},
   'score': '1 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9885_xsmall.png',
   'linkToMatch': '/matches/sassuolo-vs-juventus/2mml13#4230727',
   'date': None,
   'teamPageUrl': '/teams/9885/overview/juventus',
   'tooltipText': {'utcTime': '2024-01-16T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Juventus',
    'homeTeamId': 9885,
    'homeScore': 3,
    'awayTeam': 'Sassuolo',
    'awayTeamId': 7943,
    'awayScore': 0},
   'score': '3 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/6504_xsmall.png',
   'linkToMatch': '/matches/monza-vs-sassuolo/1q52rz#4230749',
   'date': None,
   'teamPageUrl': '/teams/6504/overview/monza',
   'tooltipText': {'utcTime': '2024-01-28T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Monza',
    'homeTeamId': 6504,
    'homeScore': 1,
    'awayTeam': 'Sassuolo',
    'awayTeamId': 7943,
    'awayScore': 0},
   'score': '1 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9857_xsmall.png',
   'linkToMatch': '/matches/sassuolo-vs-bologna/2mbw4l#4230755',
   'date': None,
   'teamPageUrl': '/teams/9857/overview/bologna',
   'tooltipText': {'utcTime': '2024-02-03T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Bologna',
    'homeTeamId': 9857,
    'homeScore': 4,
    'awayTeam': 'Sassuolo',
    'awayTeamId': 7943,
    'awayScore': 2},
   'score': '4 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9804_xsmall.png',
   'linkToMatch': '/matches/sassuolo-vs-torino/2lrp7u#4230769',
   'date': None,
   'teamPageUrl': '/teams/9804/overview/torino',
   'tooltipText': {'utcTime': '2024-02-10T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Sassuolo',
    'homeTeamId': 7943,
    'homeScore': 1,
    'awayTeam': 'Torino',
    'awayTeamId': 9804,
    'awayScore': 1},
   'score': '1 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '8524': [{'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8686_xsmall.png',
   'linkToMatch': '/matches/atalanta-vs-roma/2g6hwd#4230717',
   'date': None,
   'teamPageUrl': '/teams/8686/overview/roma',
   'tooltipText': {'utcTime': '2024-01-07T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Roma',
    'homeTeamId': 8686,
    'homeScore': 1,
    'awayTeam': 'Atalanta',
    'awayTeamId': 8524,
    'awayScore': 1},
   'score': '1 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9891_xsmall.png',
   'linkToMatch': '/matches/atalanta-vs-frosinone/2syl2j#4230724',
   'date': None,
   'teamPageUrl': '/teams/9891/overview/frosinone',
   'tooltipText': {'utcTime': '2024-01-15T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Atalanta',
    'homeTeamId': 8524,
    'homeScore': 5,
    'awayTeam': 'Frosinone',
    'awayTeamId': 9891,
    'awayScore': 0},
   'score': '5 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8600_xsmall.png',
   'linkToMatch': '/matches/atalanta-vs-udinese/2faumq#4230744',
   'date': None,
   'teamPageUrl': '/teams/8600/overview/udinese',
   'tooltipText': {'utcTime': '2024-01-27T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Atalanta',
    'homeTeamId': 8524,
    'homeScore': 2,
    'awayTeam': 'Udinese',
    'awayTeamId': 8600,
    'awayScore': 0},
   'score': '2 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8543_xsmall.png',
   'linkToMatch': '/matches/atalanta-vs-lazio/2epyoh#4230754',
   'date': None,
   'teamPageUrl': '/teams/8543/overview/lazio',
   'tooltipText': {'utcTime': '2024-02-04T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Atalanta',
    'homeTeamId': 8524,
    'homeScore': 3,
    'awayTeam': 'Lazio',
    'awayTeamId': 8543,
    'awayScore': 1},
   'score': '3 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/10233_xsmall.png',
   'linkToMatch': '/matches/atalanta-vs-genoa/2wqssb#4230770',
   'date': None,
   'teamPageUrl': '/teams/10233/overview/genoa',
   'tooltipText': {'utcTime': '2024-02-11T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Genoa',
    'homeTeamId': 10233,
    'homeScore': 1,
    'awayTeam': 'Atalanta',
    'awayTeamId': 8524,
    'awayScore': 4},
   'score': '1 - 4',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '8529': [{'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9857_xsmall.png',
   'linkToMatch': '/matches/cagliari-vs-bologna/2sn5ak#4230731',
   'date': None,
   'teamPageUrl': '/teams/9857/overview/bologna',
   'tooltipText': {'utcTime': '2024-01-14T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Cagliari',
    'homeTeamId': 8529,
    'homeScore': 2,
    'awayTeam': 'Bologna',
    'awayTeamId': 9857,
    'awayScore': 1},
   'score': '2 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9891_xsmall.png',
   'linkToMatch': '/matches/cagliari-vs-frosinone/2t0k4l#4230737',
   'date': None,
   'teamPageUrl': '/teams/9891/overview/frosinone',
   'tooltipText': {'utcTime': '2024-01-21T11:30:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Frosinone',
    'homeTeamId': 9891,
    'homeScore': 3,
    'awayTeam': 'Cagliari',
    'awayTeamId': 8529,
    'awayScore': 1},
   'score': '3 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9804_xsmall.png',
   'linkToMatch': '/matches/cagliari-vs-torino/2s2af3#4230745',
   'date': None,
   'teamPageUrl': '/teams/9804/overview/torino',
   'tooltipText': {'utcTime': '2024-01-26T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Cagliari',
    'homeTeamId': 8529,
    'homeScore': 1,
    'awayTeam': 'Torino',
    'awayTeamId': 9804,
    'awayScore': 2},
   'score': '1 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8686_xsmall.png',
   'linkToMatch': '/matches/cagliari-vs-roma/2g8cb2#4230759',
   'date': None,
   'teamPageUrl': '/teams/8686/overview/roma',
   'tooltipText': {'utcTime': '2024-02-05T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Roma',
    'homeTeamId': 8686,
    'homeScore': 4,
    'awayTeam': 'Cagliari',
    'awayTeamId': 8529,
    'awayScore': 0},
   'score': '4 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8543_xsmall.png',
   'linkToMatch': '/matches/cagliari-vs-lazio/2ersjb#4230765',
   'date': None,
   'teamPageUrl': '/teams/8543/overview/lazio',
   'tooltipText': {'utcTime': '2024-02-10T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Cagliari',
    'homeTeamId': 8529,
    'homeScore': 1,
    'awayTeam': 'Lazio',
    'awayTeamId': 8543,
    'awayScore': 3},
   'score': '1 - 3',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '8534': [{'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9876_xsmall.png',
   'linkToMatch': '/matches/empoli-vs-hellas-verona/2swm0r#4230732',
   'date': None,
   'teamPageUrl': '/teams/9876/overview/hellas-verona',
   'tooltipText': {'utcTime': '2024-01-13T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Hellas Verona',
    'homeTeamId': 9876,
    'homeScore': 2,
    'awayTeam': 'Empoli',
    'awayTeamId': 8534,
    'awayScore': 1},
   'score': '2 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/6504_xsmall.png',
   'linkToMatch': '/matches/monza-vs-empoli/1vbubb#4230735',
   'date': None,
   'teamPageUrl': '/teams/6504/overview/monza',
   'tooltipText': {'utcTime': '2024-01-21T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Empoli',
    'homeTeamId': 8534,
    'homeScore': 3,
    'awayTeam': 'Monza',
    'awayTeamId': 6504,
    'awayScore': 0},
   'score': '3 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9885_xsmall.png',
   'linkToMatch': '/matches/empoli-vs-juventus/2t05wr#4230751',
   'date': None,
   'teamPageUrl': '/teams/9885/overview/juventus',
   'tooltipText': {'utcTime': '2024-01-27T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Juventus',
    'homeTeamId': 9885,
    'homeScore': 1,
    'awayTeam': 'Empoli',
    'awayTeamId': 8534,
    'awayScore': 1},
   'score': '1 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/10233_xsmall.png',
   'linkToMatch': '/matches/empoli-vs-genoa/2wutke#4230756',
   'date': None,
   'teamPageUrl': '/teams/10233/overview/genoa',
   'tooltipText': {'utcTime': '2024-02-03T14:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Empoli',
    'homeTeamId': 8534,
    'homeScore': 0,
    'awayTeam': 'Genoa',
    'awayTeamId': 10233,
    'awayScore': 0},
   'score': '0 - 0',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/6480_xsmall.png',
   'linkToMatch': '/matches/salernitana-vs-empoli/1v441n#4230771',
   'date': None,
   'teamPageUrl': '/teams/6480/overview/salernitana',
   'tooltipText': {'utcTime': '2024-02-09T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Salernitana',
    'homeTeamId': 6480,
    'homeScore': 1,
    'awayTeam': 'Empoli',
    'awayTeamId': 8534,
    'awayScore': 3},
   'score': '1 - 3',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}}],
 '8535': [{'result': 0,
   'resultString': 'D',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8600_xsmall.png',
   'linkToMatch': '/matches/fiorentina-vs-udinese/2few0w#4230725',
   'date': None,
   'teamPageUrl': '/teams/8600/overview/udinese',
   'tooltipText': {'utcTime': '2024-01-14T17:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Fiorentina',
    'homeTeamId': 8535,
    'homeScore': 2,
    'awayTeam': 'Udinese',
    'awayTeamId': 8600,
    'awayScore': 2},
   'score': '2 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/8636_xsmall.png',
   'linkToMatch': '/matches/fiorentina-vs-inter/2fs4je#4230746',
   'date': None,
   'teamPageUrl': '/teams/8636/overview/inter',
   'tooltipText': {'utcTime': '2024-01-28T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Fiorentina',
    'homeTeamId': 8535,
    'homeScore': 0,
    'awayTeam': 'Inter',
    'awayTeamId': 8636,
    'awayScore': 1},
   'score': '0 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9888_xsmall.png',
   'linkToMatch': '/matches/fiorentina-vs-lecce/2t1qro#4230760',
   'date': None,
   'teamPageUrl': '/teams/9888/overview/lecce',
   'tooltipText': {'utcTime': '2024-02-02T19:45:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Lecce',
    'homeTeamId': 9888,
    'homeScore': 3,
    'awayTeam': 'Fiorentina',
    'awayTeamId': 8535,
    'awayScore': 2},
   'score': '3 - 2',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': 1,
   'resultString': 'W',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9891_xsmall.png',
   'linkToMatch': '/matches/fiorentina-vs-frosinone/2t2xf6#4230766',
   'date': None,
   'teamPageUrl': '/teams/9891/overview/frosinone',
   'tooltipText': {'utcTime': '2024-02-11T11:30:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Fiorentina',
    'homeTeamId': 8535,
    'homeScore': 5,
    'awayTeam': 'Frosinone',
    'awayTeamId': 9891,
    'awayScore': 1},
   'score': '5 - 1',
   'home': {'isOurTeam': False},
   'away': {'isOurTeam': False}},
  {'result': -1,
   'resultString': 'L',
   'imageUrl': 'https://images.fotmob.com/image_resources/logo/teamlogo/9857_xsmall.png',
   'linkToMatch': '/matches/fiorentina-vs-bologna/2spifh#4230734',
   'date': None,
   'teamPageUrl': '/teams/9857/overview/bologna',
   'tooltipText': {'utcTime': '2024-02-14T18:00:00.000Z',
    'timezone': 'UTC',
    'homeTeam': 'Bologna',

In [227]:
pd.json_normalize(data['stats']['players'][0]['topThree']).T

,0,1,2
id,690230,737857,46469
name,Lautaro Martinez,Dusan Vlahovic,Olivier Giroud
rank,1,2,3
ccode,ARG,SRB,FRA
teamId,8636,9885,8564
teamName,Internazionale,Juventus,Milan
stat.name,goals,goals,goals
stat.value,19,12,11
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#FFFFFF,#CF2C27
teamColors.lightMode,#010E80,#000001,#CF2C27
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [232]:
goals = requests.get(data['stats']['players'][0]['fetchAllUrl'])
goals = goals.json()
pd.json_normalize(goals['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Lautaro Martinez,690230,8636,#010E80,19.0,2.0,1767,21,13,1,ARG,Internazionale
1,Dusan Vlahovic,737857,9885,#000001,12.0,1.0,1419,21,9,2,SRB,Juventus
2,Olivier Giroud,46469,8564,#CF2C27,11.0,4.0,1594,21,9,3,FRA,Milan
3,Matias Soulé,1280082,9891,#d5a300,10.0,4.0,1920,22,9,4,ARG,Frosinone
4,Marcus Thuram,621562,8636,#010E80,9.0,0.0,1782,23,9,5,FRA,Internazionale
...,...,...,...,...,...,...,...,...,...,...,...,...
218,Leandro Paredes,237606,8686,#9c0922,1.0,1.0,1690,22,1,218,ARG,Roma
219,M'Baye Niang,46241,8534,#005098,1.0,1.0,20,1,1,218,SEN,Empoli
220,Nahitan Nández,643573,8529,#B51F2B,1.0,1.0,1385,20,1,218,URU,Cagliari
221,Tomas Suslov,1127054,9876,#002F6C,1.0,1.0,1242,18,1,218,SVK,Verona
222,Walid Cheddira,1078113,9891,#d5a300,1.0,1.0,1027,22,1,218,MAR,Frosinone

In [226]:
pd.json_normalize(data['stats']['players'][1]['topThree']).T #assists

,0,1,2
id,46469,848844,621562
name,Olivier Giroud,Rafael Leao,Marcus Thuram
rank,1,2,3
ccode,FRA,POR,FRA
teamId,8564,8564,8636
teamName,Milan,Milan,Internazionale
stat.name,goal_assist,goal_assist,goal_assist
stat.value,8,7,7
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#CF2C27,#CF2C27,#1A5DD4
teamColors.lightMode,#CF2C27,#CF2C27,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [231]:
assists = requests.get(data['stats']['players'][1]['fetchAllUrl'])
assists = assists.json()
pd.json_normalize(assists['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Olivier Giroud,46469,8564,#CF2C27,8.0,1.8,1594,21,8,1,FRA,Milan
1,Rafael Leao,848844,8564,#CF2C27,7.0,5.1,1586,21,6,2,POR,Milan
2,Marcus Thuram,621562,8636,#010E80,7.0,2.2,1782,23,7,3,FRA,Internazionale
3,Felipe Anderson,230190,8543,#75acd4,6.0,3.3,1680,23,5,4,BRA,Lazio
4,Henrikh Mkhitaryan,73167,8636,#010E80,6.0,3.3,1883,23,6,4,ARM,Internazionale
...,...,...,...,...,...,...,...,...,...,...,...,...
212,Simone Romagnoli,111739,9891,#d5a300,1.0,0.1,1653,21,1,206,ITA,Frosinone
213,Christian Kabasele,149219,8600,#101010,1.0,0.0,859,11,1,214,BEL,Udinese
214,M'Baye Niang,46241,8534,#005098,1.0,0.0,20,1,1,214,SEN,Empoli
215,Mike Maignan,466439,8564,#CF2C27,1.0,0.0,1889,21,1,214,FRA,Milan
216,Rares Burnete,1286272,9888,#e12300,1.0,0.0,7,1,1,214,ROU,Lecce

In [225]:
pd.json_normalize(data['stats']['players'][2]['topThree']).T

,0,1,2
id,690230,46469,621562
name,Lautaro Martinez,Olivier Giroud,Marcus Thuram
rank,1,2,3
ccode,ARG,FRA,FRA
teamId,8636,8564,8636
teamName,Internazionale,Milan,Internazionale
stat.name,_goals_and_goal_assist,_goals_and_goal_assist,_goals_and_goal_assist
stat.value,21,19,16
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#CF2C27,#1A5DD4
teamColors.lightMode,#010E80,#CF2C27,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [230]:
goals_and_assists = requests.get(data['stats']['players'][2]['fetchAllUrl'])
goals_and_assists = goals_and_assists.json()
pd.json_normalize(goals_and_assists['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Lautaro Martinez,690230,8636,#010E80,21.0,13.0,1767,21,1,1,ARG,Internazionale
1,Olivier Giroud,46469,8564,#CF2C27,19.0,12.0,1594,21,1,2,FRA,Milan
2,Marcus Thuram,621562,8636,#010E80,16.0,12.8,1782,23,1,3,FRA,Internazionale
3,Dusan Vlahovic,737857,9885,#000001,15.0,11.1,1419,21,1,4,SRB,Juventus
4,Paulo Dybala,325916,8686,#9c0922,14.0,10.4,1271,17,1,5,ARG,Roma
...,...,...,...,...,...,...,...,...,...,...,...,...
302,Lorenzo Montipo,491784,9876,#002F6C,1.0,0.1,2160,24,1,300,ITA,Verona
303,Michel Ndary Adopo,936164,8524,#004ca6,1.0,0.1,45,7,1,300,FRA,Atalanta
304,Oussama El Azzouzi,1283469,9857,#102880,1.0,0.1,214,10,1,300,MAR,Bologna
305,Mike Maignan,466439,8564,#CF2C27,1.0,0.0,1889,21,1,306,FRA,Milan
306,Rares Burnete,1286272,9888,#e12300,1.0,0.0,7,1,1,306,ROU,Lecce

In [224]:
pd.json_normalize(data['stats']['players'][3]['topThree']).T

,0,1,2
id,690230,304733,73167
name,Lautaro Martinez,Hakan Calhanoglu,Henrikh Mkhitaryan
rank,1,2,3
ccode,ARG,TUR,ARM
teamId,8636,8636,8636
teamName,Internazionale,Internazionale,Internazionale
stat.name,rating,rating,rating
stat.value,7.88,7.88,7.59
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#1A5DD4,#1A5DD4,#1A5DD4
teamColors.lightMode,#010E80,#010E80,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [223]:
pd.json_normalize(data['stats']['players'][4]['topThree']).T

,0,1,2
id,690230,463291,915797
name,Lautaro Martinez,Luka Jovic,Noah Okafor
rank,1,2,3
ccode,ARG,SRB,SUI
teamId,8636,8564,8564
teamName,Internazionale,Milan,Milan
stat.name,goals_per_90,goals_per_90,goals_per_90
stat.value,0.97,0.86,0.81
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#1A5DD4,#CF2C27,#CF2C27
teamColors.lightMode,#010E80,#CF2C27,#CF2C27
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [222]:
pd.json_normalize(data['stats']['players'][5]['topThree']).T

,0,1,2
id,690230,621562,737857
name,Lautaro Martinez,Marcus Thuram,Dusan Vlahovic
rank,1,2,3
ccode,ARG,FRA,SRB
teamId,8636,8636,9885
teamName,Internazionale,Internazionale,Juventus
stat.name,expected_goals,expected_goals,expected_goals
stat.value,12.0,10.6,10.2
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#1A5DD4,#1A5DD4,#FFFFFF
teamColors.lightMode,#010E80,#010E80,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [221]:
pd.json_normalize(data['stats']['players'][6]['topThree']).T

,0,1,2
id,737857,690230,441309
name,Dusan Vlahovic,Lautaro Martinez,Sardar Azmoun
rank,1,2,3
ccode,SRB,ARG,IRN
teamId,9885,8636,8686
teamName,Juventus,Internazionale,Roma
stat.name,expected_goals_per_90,expected_goals_per_90,expected_goals_per_90
stat.value,0.65,0.61,0.61
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#FFFFFF,#1A5DD4,#b90926
teamColors.lightMode,#000001,#010E80,#9c0922
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [229]:
xG90 = requests.get(data['stats']['players'][6]['fetchAllUrl'])
xG90 = xG90.json()
pd.json_normalize(xG90['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Dusan Vlahovic,737857,9885,#000001,0.65,0.76,1419,21,20,1,SRB,Juventus
1,Lautaro Martinez,690230,8636,#010E80,0.61,0.97,1767,21,20,2,ARG,Internazionale
2,Sardar Azmoun,441309,8686,#9c0922,0.61,0.37,241,14,7,3,IRN,Roma
3,Luka Jovic,463291,8564,#CF2C27,0.60,0.86,521,16,7,4,SRB,Milan
4,Victor Osimhen,687681,9875,#12A0D7,0.60,0.63,997,13,12,5,NGA,Napoli
...,...,...,...,...,...,...,...,...,...,...,...,...
313,Tommaso Augello,693160,8529,#B51F2B,0.01,0.00,1345,19,7,296,ITA,Cagliari
314,Victor Kristiansen,1211437,9857,#102880,0.01,0.00,1330,20,4,296,DEN,Bologna
315,Adam Marusic,478447,8543,#75acd4,0.00,0.00,1935,23,3,316,MNE,Lazio
316,Bartosz Bereszynski,198099,8534,#005098,0.00,0.00,870,12,1,316,POL,Empoli
317,Diego Llorente,420568,8686,#9c0922,0.00,0.00,1587,21,3,316,ESP,Roma

In [220]:
pd.json_normalize(data['stats']['players'][7]['topThree']).T

,0,1,2
id,690230,46469,737857
name,Lautaro Martinez,Olivier Giroud,Dusan Vlahovic
rank,1,2,3
ccode,ARG,FRA,SRB
teamId,8636,8564,9885
teamName,Internazionale,Milan,Juventus
stat.name,expected_goalsontarget,expected_goalsontarget,expected_goalsontarget
stat.value,13.1,11.8,10.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#1A5DD4,#CF2C27,#FFFFFF
teamColors.lightMode,#010E80,#CF2C27,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [219]:
pd.json_normalize(data['stats']['players'][8]['topThree']).T #SOT per 90

,0,1,2
id,196484,721089,737857
name,Luis Muriel,Gianluca Scamacca,Dusan Vlahovic
rank,1,2,3
ccode,COL,ITA,SRB
teamId,8524,8524,9885
teamName,Atalanta,Atalanta,Juventus
stat.name,ontarget_scoring_att,ontarget_scoring_att,ontarget_scoring_att
stat.value,2.1,1.7,1.7
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#0D68B1,#FFFFFF
teamColors.lightMode,#004ca6,#004ca6,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [217]:
pd.json_normalize(data['stats']['players'][9]['topThree']).T #shots per 90

,0,1,2
id,196484,469615,737857
name,Luis Muriel,Giovanni Simeone,Dusan Vlahovic
rank,1,2,3
ccode,COL,ARG,SRB
teamId,8524,9875,9885
teamName,Atalanta,Napoli,Juventus
stat.name,total_scoring_att,total_scoring_att,total_scoring_att
stat.value,5.2,4.5,4.4
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#12A0D7,#FFFFFF
teamColors.lightMode,#004ca6,#12A0D7,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [215]:
pd.json_normalize(data['stats']['players'][10]['topThree']).T

,0,1,2
id,544693,860913,197352
name,Amir Rrahmani,Jhon Lucumi,Juan Jesus
rank,1,2,3
ccode,KVX,COL,BRA
teamId,9875,9857,9875
teamName,Napoli,Bologna,Napoli
stat.name,accurate_pass,accurate_pass,accurate_pass
stat.value,68.1,67.9,67.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#12A0D7,#203faf,#12A0D7
teamColors.lightMode,#12A0D7,#102880,#12A0D7
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [216]:
acc_passes = requests.get(data['stats']['players'][10]['fetchAllUrl'])
acc_passes = acc_passes.json()
pd.json_normalize(acc_passes['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Amir Rrahmani,544693,9875,#12A0D7,68.1,90.0,1575,18,18,1,KVX,Napoli
1,Jhon Lucumi,860913,9857,#102880,67.9,93.1,999,15,15,2,COL,Bologna
2,Juan Jesus,197352,9875,#12A0D7,67.9,91.3,1217,14,14,3,BRA,Napoli
3,Fikayo Tomori,749662,8564,#CF2C27,67.2,91.1,1386,16,16,4,ENG,Milan
4,Hakan Calhanoglu,304733,8636,#010E80,65.2,91.6,1813,22,22,5,TUR,Internazionale
...,...,...,...,...,...,...,...,...,...,...,...,...
334,Chukwubuikem Ikwuemesi,1297995,6480,#59181C,9.3,70.0,608,18,17,335,NGA,Salernitana
335,Lorenzo Lucca,1212630,8600,#101010,9.3,60.2,1524,24,23,336,ITA,Udinese
336,Roberto Piccoli,1017401,9888,#e12300,9.1,58.1,601,24,22,337,ITA,Lecce
337,Moise Kean,747926,9885,#000001,9.0,71.2,472,12,11,338,ITA,Juventus
338,Victor Osimhen,687681,9875,#12A0D7,8.0,71.8,997,13,13,339,NGA,Napoli

In [214]:
pd.json_normalize(data['stats']['players'][11]['topThree']).T

,0,1,2
id,848844,605224,281012
name,Rafael Leao,Federico Dimarco,Filip Kostic
rank,1,2,3
ccode,POR,ITA,SRB
teamId,8564,8636,9885
teamName,Milan,Internazionale,Juventus
stat.name,big_chance_created,big_chance_created,big_chance_created
stat.value,12,11,10
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#CF2C27,#1A5DD4,#FFFFFF
teamColors.lightMode,#CF2C27,#010E80,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [228]:
big_chances_created = requests.get(data['stats']['players'][11]['fetchAllUrl'])
big_chances_created = big_chances_created.json()
pd.json_normalize(big_chances_created['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Rafael Leao,848844,8564,#CF2C27,12.0,7.0,1586,21,10,1,POR,Milan
1,Federico Dimarco,605224,8636,#010E80,11.0,5.0,1307,19,8,2,ITA,Internazionale
2,Filip Kostic,281012,9885,#000001,10.0,4.0,1393,21,6,3,SRB,Juventus
3,Olivier Giroud,46469,8564,#CF2C27,9.0,8.0,1594,21,7,4,FRA,Milan
4,Joshua Zirkzee,950830,9857,#102880,8.0,3.0,1924,23,8,5,NED,Bologna
...,...,...,...,...,...,...,...,...,...,...,...,...
262,Samuel Castillejo,562062,7943,#084018,1.0,0.0,487,15,1,212,ESP,Sassuolo
263,Samuele Mulattieri,923222,7943,#084018,1.0,0.0,201,18,1,212,ITA,Sassuolo
264,Walace,538540,8600,#101010,1.0,0.0,2077,24,1,212,BRA,Udinese
265,Yann Aurel Bisseck,889535,8636,#010E80,1.0,0.0,386,9,1,212,GER,Internazionale
266,Youssef Maleh,789243,8534,#005098,1.0,0.0,1673,21,1,212,MAR,Empoli

In [218]:
pd.json_normalize(data['stats']['players'][12]['topThree']).T #chances created

,0,1,2
id,665188,1280082,11685
name,Albert Gudmundsson,Matias Soulé,Antonio Candreva
rank,1,2,3
ccode,ISL,ARG,ITA
teamId,10233,9891,6480
teamName,Genoa,Frosinone,Salernitana
stat.name,total_att_assist,total_att_assist,total_att_assist
stat.value,56,54,49
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#CB1111,#E3AD00,#ac4f47
teamColors.lightMode,#CB1111,#d5a300,#59181C
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [212]:
pd.json_normalize(data['stats']['players'][13]['topThree']).T

,0,1,2
id,358149,638771,624166
name,Patric,Lucas Martinez Quarta,Manuel Locatelli
rank,1,2,3
ccode,ESP,ARG,ITA
teamId,8543,8535,9885
teamName,Lazio,Fiorentina,Juventus
stat.name,accurate_long_balls,accurate_long_balls,accurate_long_balls
stat.value,6.7,6.2,5.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#75acd4,#6f34af,#FFFFFF
teamColors.lightMode,#75acd4,#5F259F,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [211]:
pd.json_normalize(data['stats']['players'][14]['topThree']).T

,0,1,2
id,848844,605224,127460
name,Rafael Leao,Federico Dimarco,Giacomo Bonaventura
rank,1,2,3
ccode,POR,ITA,ITA
teamId,8564,8636,8535
teamName,Milan,Internazionale,Fiorentina
stat.name,expected_assists,expected_assists,expected_assists
stat.value,5.1,4.9,4.5
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#CF2C27,#1A5DD4,#6f34af
teamColors.lightMode,#CF2C27,#010E80,#5F259F
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [210]:
pd.json_normalize(data['stats']['players'][15]['topThree']).T

,0,1,2
id,442581,110148,605224
name,Aleksey Miranchuk,Marko Arnautovic,Federico Dimarco
rank,1,2,3
ccode,RUS,AUT,ITA
teamId,8524,8636,8636
teamName,Atalanta,Internazionale,Internazionale
stat.name,expected_assists_per_90,expected_assists_per_90,expected_assists_per_90
stat.value,0.42,0.41,0.34
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#0D68B1,#1A5DD4,#1A5DD4
teamColors.lightMode,#004ca6,#010E80,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [209]:
pd.json_normalize(data['stats']['players'][16]['topThree']).T

,0,1,2
id,110148,442581,325916
name,Marko Arnautovic,Aleksey Miranchuk,Paulo Dybala
rank,1,2,3
ccode,AUT,RUS,ARG
teamId,8636,8524,8686
teamName,Internazionale,Atalanta,Roma
stat.name,_expected_goals_and_expected_assists_per_90,_expected_goals_and_expected_assists_per_90,_expected_goals_and_expected_assists_per_90
stat.value,0.97,0.75,0.74
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#1A5DD4,#0D68B1,#b90926
teamColors.lightMode,#010E80,#004ca6,#9c0922
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [208]:
pd.json_normalize(data['stats']['players'][17]['topThree']).T #successful dribbles per 90

,0,1,2
id,979789,1280082,896377
name,Giuseppe Caso,Matias Soulé,Lameck Banda
rank,1,2,3
ccode,ITA,ARG,ZAM
teamId,9891,9891,9888
teamName,Frosinone,Frosinone,Lecce
stat.name,won_contest,won_contest,won_contest
stat.value,3.5,3.4,3.2
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#E3AD00,#E3AD00,#e12300
teamColors.lightMode,#d5a300,#d5a300,#e12300
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [207]:
pd.json_normalize(data['stats']['players'][18]['topThree']).T

,0,1,2
id,900433,737857,833638
name,Khvicha Kvaratskhelia,Dusan Vlahovic,Nikola Krstovic
rank,1,2,3
ccode,GEO,SRB,MNE
teamId,9875,9885,9888
teamName,Napoli,Juventus,Lecce
stat.name,big_chance_missed,big_chance_missed,big_chance_missed
stat.value,10,9,9
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#12A0D7,#FFFFFF,#e12300
teamColors.lightMode,#12A0D7,#000001,#e12300
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [206]:
pd.json_normalize(data['stats']['players'][19]['topThree']).T

,0,1,2
id,621562,161660,690230
name,Marcus Thuram,Ciro Immobile,Lautaro Martinez
rank,1,2,3
ccode,FRA,ITA,ARG
teamId,8636,8543,8636
teamName,Internazionale,Lazio,Internazionale
stat.name,penalty_won,penalty_won,penalty_won
stat.value,3,2,2
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#75acd4,#1A5DD4
teamColors.lightMode,#010E80,#75acd4,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [205]:
pd.json_normalize(data['stats']['players'][20]['topThree']).T

,0,1,2
id,667790,1368061,801120
name,Suat Serdar,Samuel Iling-Junior,Jens-Lys Cajuste
rank,1,2,3
ccode,GER,ENG,SWE
teamId,9876,9885,9875
teamName,Verona,Juventus,Napoli
stat.name,won_tackle,won_tackle,won_tackle
stat.value,2.6,2.6,2.5
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#00449f,#FFFFFF,#12A0D7
teamColors.lightMode,#002F6C,#000001,#12A0D7
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [204]:
pd.json_normalize(data['stats']['players'][21]['topThree']).T

,0,1,2
id,823018,426393,575364
name,Alessandro Buongiorno,Adrien Tamèze,Alberto Grassi
rank,1,2,2
ccode,ITA,FRA,ITA
teamId,9804,9804,8534
teamName,Torino,Torino,Empoli
stat.name,interception,interception,interception
stat.value,2.5,2.3,2.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#9b2d22,#9b2d22,#0767e5
teamColors.lightMode,#680903,#680903,#005098
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [203]:
pd.json_normalize(data['stats']['players'][22]['topThree']).T

,0,1,2
id,860592,111739,861805
name,Sebastian Walukiewicz,Simone Romagnoli,Jaka Bijol
rank,1,2,3
ccode,POL,ITA,SVN
teamId,8534,9891,8600
teamName,Empoli,Frosinone,Udinese
stat.name,effective_clearance,effective_clearance,effective_clearance
stat.value,5.5,5.1,5.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0767e5,#E3AD00,#ffffff
teamColors.lightMode,#005098,#d5a300,#101010
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [202]:
pd.json_normalize(data['stats']['players'][23]['topThree']).T

,0,1,2
id,415017,35112,1006676
name,Mattia Bani,Simon Kjær,Memeh Caleb Okoli
rank,1,2,3
ccode,ITA,DEN,ITA
teamId,10233,8564,9891
teamName,Genoa,Milan,Frosinone
stat.name,outfielder_block,outfielder_block,outfielder_block
stat.value,1.4,1.4,1.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#CB1111,#CF2C27,#E3AD00
teamColors.lightMode,#CB1111,#CF2C27,#d5a300
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [201]:
pd.json_normalize(data['stats']['players'][24]['topThree']).T

,0,1,2
id,1060654,187288,149219
name,Festy Ebosele,Mehdi Bourabia,Christian Kabasele
rank,1,2,3
ccode,IRL,MAR,BEL
teamId,8600,9891,8600
teamName,Udinese,Frosinone,Udinese
stat.name,penalty_conceded,penalty_conceded,penalty_conceded
stat.value,3,2,2
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#ffffff,#E3AD00,#ffffff
teamColors.lightMode,#101010,#d5a300,#101010
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(29, 29, 29, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [200]:
pd.json_normalize(data['stats']['players'][25]['topThree']).T

,0,1,2
id,923222,196484,1368061
name,Samuele Mulattieri,Luis Muriel,Samuel Iling-Junior
rank,1,2,3
ccode,ITA,COL,ENG
teamId,7943,8524,9885
teamName,Sassuolo,Atalanta,Juventus
stat.name,poss_won_att_3rd,poss_won_att_3rd,poss_won_att_3rd
stat.value,2.2,1.4,1.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#00A752,#0D68B1,#FFFFFF
teamColors.lightMode,#084018,#004ca6,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [199]:
pd.json_normalize(data['stats']['players'][26]['topThree']).T

,0,1,2
id,41618,543021,169718
name,Yann Sommer,Vanja Milinkovic-Savic,Wojciech Szczesny
rank,1,2,3
ccode,SUI,SRB,POL
teamId,8636,9804,9885
teamName,Internazionale,Torino,Juventus
stat.name,clean_sheet,clean_sheet,clean_sheet
stat.value,14,11,11
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#9b2d22,#FFFFFF
teamColors.lightMode,#010E80,#680903,#000001
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [198]:
pd.json_normalize(data['stats']['players'][27]['topThree']).T

,0,1,2
id,766062,41618,543021
name,Michele Di Gregorio,Yann Sommer,Vanja Milinkovic-Savic
rank,1,2,3
ccode,ITA,SUI,SRB
teamId,6504,8636,9804
teamName,Monza,Internazionale,Torino
stat.name,_save_percentage,_save_percentage,_save_percentage
stat.value,83.0,81.5,79.1
stat.format,percent,percent,percent
stat.fractions,1,1,1
teamColors.darkMode,#EC173A,#1A5DD4,#9b2d22
teamColors.lightMode,#EC173A,#010E80,#680903
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [197]:
pd.json_normalize(data['stats']['players'][28]['topThree']).T

,0,1,2
id,766062,150747,362200
name,Michele Di Gregorio,Etrit Berisha,Wladimiro Falcone
rank,1,2,3
ccode,ITA,ALB,ITA
teamId,6504,8534,9888
teamName,Monza,Empoli,Lecce
stat.name,saves,saves,saves
stat.value,4.1,3.6,3.2
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#EC173A,#0767e5,#e12300
teamColors.lightMode,#EC173A,#005098,#e12300
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [196]:
pd.json_normalize(data['stats']['players'][29]['topThree']).T

,0,1,2
id,766062,281762,41618
name,Michele Di Gregorio,Pietro Terracciano,Yann Sommer
rank,1,2,3
ccode,ITA,ITA,SUI
teamId,6504,8535,8636
teamName,Monza,Fiorentina,Internazionale
stat.name,_goals_prevented,_goals_prevented,_goals_prevented
stat.value,8.7,5.2,4.7
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#EC173A,#6f34af,#1A5DD4
teamColors.lightMode,#EC173A,#5F259F,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [195]:
pd.json_normalize(data['stats']['players'][30]['topThree']).T

,0,1,2
id,869054,423223,31047
name,Stefano Turati,Simone Scuffet,Guillermo Ochoa
rank,1,2,3
ccode,ITA,ITA,MEX
teamId,9891,8529,6480
teamName,Frosinone,Cagliari,Salernitana
stat.name,goals_conceded,goals_conceded,goals_conceded
stat.value,2.1,1.9,1.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#E3AD00,#B51F2B,#ac4f47
teamColors.lightMode,#d5a300,#B51F2B,#59181C
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [194]:
pd.json_normalize(data['stats']['players'][31]['topThree']).T

,0,1,2
id,1297995,534484,1110045
name,Chukwubuikem Ikwuemesi,Isaac Success,Gaetano Oristanio
rank,1,2,3
ccode,NGA,NGA,ITA
teamId,6480,8600,8529
teamName,Salernitana,Udinese,Cagliari
stat.name,fouls,fouls,fouls
stat.value,3.4,3.1,3.0
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#ac4f47,#ffffff,#B51F2B
teamColors.lightMode,#59181C,#101010,#B51F2B
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [193]:
pd.json_normalize(data['stats']['players'][32]['topThree']).T

,0,1,2
id,237606,935406,762028
name,Leandro Paredes,Luca Ranieri,Ylber Ramadani
rank,1,2,2
ccode,ARG,ITA,ALB
teamId,8686,8535,9888
teamName,Roma,Fiorentina,Lecce
stat.name,yellow_card,yellow_card,yellow_card
stat.value,11,10,10
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#b90926,#6f34af,#e12300
teamColors.lightMode,#9c0922,#5F259F,#e12300
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [192]:
pd.json_normalize(data['stats']['players'][33]['topThree']).T

,0,1,2
id,350634,915238,776571
name,Ondrej Duda,Antoine Makoumbou,Giulio Maggiore
rank,1,2,3
ccode,SVK,CGO,ITA
teamId,9876,8529,6480
teamName,Verona,Cagliari,Salernitana
stat.name,red_card,red_card,red_card
stat.value,2,2,1
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#00449f,#B51F2B,#ac4f47
teamColors.lightMode,#002F6C,#B51F2B,#59181C
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [144]:
pd.json_normalize(data['stats']['teams'][0]['topThree']).T

,0,1,2
id,0,0,0
name,Inter,Juventus,Atalanta
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,9885,8524
teamName,None,None,None
stat.name,rating_team,rating_team,rating_team
stat.value,7.18,7.03,7.02
stat.format,fraction,fraction,fraction
stat.fractions,2,2,2
teamColors.darkMode,#1A5DD4,#FFFFFF,#0D68B1
teamColors.lightMode,#010E80,#000001,#004ca6
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [145]:
fotmob_json = requests.get(data['stats']['teams'][0]['fetchAllUrl'])
fotmob_rating = fotmob_json.json()
pd.json_normalize(fotmob_rating['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,7.18,0.0,0,23,23,1,ITA,None
1,Juventus,0,9885,#000001,7.03,0.0,0,24,24,2,ITA,None
2,Atalanta,0,8524,#004ca6,7.02,0.0,0,23,23,3,ITA,None
3,AC Milan,0,8564,#CF2C27,7.00,0.0,0,24,24,4,ITA,None
4,Bologna,0,9857,#102880,6.95,0.0,0,24,24,5,ITA,None
5,SSC Napoli,0,9875,#12A0D7,6.93,0.0,0,23,23,6,ITA,None
6,Fiorentina,0,8535,#5F259F,6.89,0.0,0,24,24,7,ITA,None
7,Roma,0,8686,#9c0922,6.88,0.0,0,24,24,8,ITA,None
8,Torino,0,9804,#680903,6.85,0.0,0,23,23,9,ITA,None
9,Lazio,0,8543,#75acd4,6.82,0.0,0,23,23,10,ITA,None
10,Genoa,0,10233,#CB1111,6.79,0.0,0,24,24,11,ITA,None
11,Udinese,0,8600,#101010,6.77,0.0,0,24,24,12,ITA,None
12,Monza,0,6504,#EC173A,6.74,0.0,0,24,24,13,ITA,None
13,Lecce,0,9888,#e12300,6.70,0.0,0,24,24,14,ITA,None
14,Hellas Verona,0,9876,#002F6C,6.70,0.0,0,24,24,14,ITA,None
15,Sassuolo,0,7943,#084018,6.67,0.0,0,23,23,16,ITA,None
16,Frosinone,0,9891,#d5a300,6.64,0.0,0,24,24,17,ITA,None
17,Empoli,0,8534,#005098,6.59,0.0,0,24,24,18,ITA,None
18,Salernitana,0,6480,#59181C,6.58,0.0,0,24,24,19,ITA,None
19,Cagliari,0,8529,#B51F2B,6.56,0.0,0,24,24,20,ITA,None

In [178]:
pd.json_normalize(data['stats']['teams'][1]['topThree']).T #goal per match

,0,1,2
id,0,0,0
name,Inter,AC Milan,Atalanta
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,8564,8524
teamName,None,None,None
stat.name,goals_team_match,goals_team_match,goals_team_match
stat.value,2.4,2.0,1.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#1A5DD4,#CF2C27,#0D68B1
teamColors.lightMode,#010E80,#CF2C27,#004ca6
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [179]:
goals_permatch = requests.get(data['stats']['teams'][1]['fetchAllUrl'])
goals_permatch = goals_permatch.json()
pd.json_normalize(goals_permatch['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,2.4,55.0,0,23,23,1,ITA,None
1,AC Milan,0,8564,#CF2C27,2.0,47.0,0,24,22,2,ITA,None
2,Atalanta,0,8524,#004ca6,1.9,44.0,0,23,20,3,ITA,None
3,Roma,0,8686,#9c0922,1.8,42.0,0,24,20,4,ITA,None
4,Fiorentina,0,8535,#5F259F,1.5,36.0,0,24,16,5,ITA,None
5,Juventus,0,9885,#000001,1.5,36.0,0,24,21,5,ITA,None
6,Bologna,0,9857,#102880,1.5,35.0,0,24,19,7,ITA,None
7,SSC Napoli,0,9875,#12A0D7,1.4,32.0,0,23,14,8,ITA,None
8,Frosinone,0,9891,#d5a300,1.3,32.0,0,24,19,9,ITA,None
9,Sassuolo,0,7943,#084018,1.3,29.0,0,23,16,10,ITA,None
10,Lazio,0,8543,#75acd4,1.2,28.0,0,23,17,11,ITA,None
11,Genoa,0,10233,#CB1111,1.0,25.0,0,24,17,12,ITA,None
12,Lecce,0,9888,#e12300,1.0,24.0,0,24,16,13,ITA,None
13,Udinese,0,8600,#101010,1.0,24.0,0,24,16,13,ITA,None
14,Cagliari,0,8529,#B51F2B,0.9,22.0,0,24,15,15,ITA,None
15,Hellas Verona,0,9876,#002F6C,0.9,21.0,0,24,15,16,ITA,None
16,Monza,0,6504,#EC173A,0.9,21.0,0,24,14,16,ITA,None
17,Torino,0,9804,#680903,0.9,21.0,0,23,13,16,ITA,None
18,Salernitana,0,6480,#59181C,0.8,20.0,0,24,15,19,ITA,None
19,Empoli,0,8534,#005098,0.8,18.0,0,24,11,20,ITA,None

In [177]:
pd.json_normalize(data['stats']['teams'][2]['topThree']).T #goals conceded per match

,0,1,2
id,0,0,0
name,Inter,Juventus,Torino
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,9885,9804
teamName,None,None,None
stat.name,goals_conceded_team_match,goals_conceded_team_match,goals_conceded_team_match
stat.value,0.5,0.6,0.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#1A5DD4,#FFFFFF,#9b2d22
teamColors.lightMode,#010E80,#000001,#680903
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [180]:
ga_permatch = requests.get(data['stats']['teams'][2]['fetchAllUrl'])
ga_permatch = ga_permatch.json()
pd.json_normalize(ga_permatch['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,0.5,12.0,0,23,9,1,ITA,None
1,Juventus,0,9885,#000001,0.6,15.0,0,24,12,2,ITA,None
2,Torino,0,9804,#680903,0.9,20.0,0,23,12,3,ITA,None
3,Bologna,0,9857,#102880,0.9,22.0,0,24,14,4,ITA,None
4,Atalanta,0,8524,#004ca6,1.0,23.0,0,23,13,5,ITA,None
5,Lazio,0,8543,#75acd4,1.0,24.0,0,23,15,6,ITA,None
6,AC Milan,0,8564,#CF2C27,1.1,27.0,0,24,15,7,ITA,None
7,SSC Napoli,0,9875,#12A0D7,1.2,27.0,0,23,17,8,ITA,None
8,Monza,0,6504,#EC173A,1.2,28.0,0,24,15,9,ITA,None
9,Fiorentina,0,8535,#5F259F,1.2,28.0,0,24,18,9,ITA,None
10,Roma,0,8686,#9c0922,1.3,30.0,0,24,18,11,ITA,None
11,Genoa,0,10233,#CB1111,1.3,30.0,0,24,19,11,ITA,None
12,Hellas Verona,0,9876,#002F6C,1.3,32.0,0,24,19,13,ITA,None
13,Udinese,0,8600,#101010,1.5,37.0,0,24,17,14,ITA,None
14,Lecce,0,9888,#e12300,1.5,37.0,0,24,22,14,ITA,None
15,Empoli,0,8534,#005098,1.5,37.0,0,24,17,14,ITA,None
16,Sassuolo,0,7943,#084018,1.8,42.0,0,23,22,17,ITA,None
17,Cagliari,0,8529,#B51F2B,1.9,45.0,0,24,21,18,ITA,None
18,Salernitana,0,6480,#59181C,2.0,47.0,0,24,22,19,ITA,None
19,Frosinone,0,9891,#d5a300,2.0,49.0,0,24,22,20,ITA,None

In [176]:
pd.json_normalize(data['stats']['teams'][3]['topThree']).T #average possession

,0,1,2
id,0,0,0
name,SSC Napoli,Bologna,Fiorentina
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9875,9857,8535
teamName,None,None,None
stat.name,possession_percentage_team,possession_percentage_team,possession_percentage_team
stat.value,60.0,57.9,57.4
stat.format,percent,percent,percent
stat.fractions,1,1,1
teamColors.darkMode,#12A0D7,#203faf,#6f34af
teamColors.lightMode,#12A0D7,#102880,#5F259F
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [181]:
possession = requests.get(data['stats']['teams'][3]['fetchAllUrl'])
possession = possession.json()
pd.json_normalize(possession['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,SSC Napoli,0,9875,#12A0D7,60.0,32.0,0,23,23,1,ITA,None
1,Bologna,0,9857,#102880,57.9,35.0,0,24,24,2,ITA,None
2,Fiorentina,0,8535,#5F259F,57.4,36.0,0,24,24,3,ITA,None
3,AC Milan,0,8564,#CF2C27,55.5,47.0,0,24,24,4,ITA,None
4,Inter,0,8636,#010E80,54.9,55.0,0,23,23,5,ITA,None
5,Monza,0,6504,#EC173A,54.7,21.0,0,24,24,6,ITA,None
6,Roma,0,8686,#9c0922,53.6,42.0,0,24,24,7,ITA,None
7,Lazio,0,8543,#75acd4,52.4,28.0,0,23,23,8,ITA,None
8,Torino,0,9804,#680903,52.3,21.0,0,23,23,9,ITA,None
9,Frosinone,0,9891,#d5a300,52.1,32.0,0,24,24,10,ITA,None
10,Atalanta,0,8524,#004ca6,51.2,44.0,0,23,23,11,ITA,None
11,Juventus,0,9885,#000001,48.0,36.0,0,24,24,12,ITA,None
12,Empoli,0,8534,#005098,45.4,18.0,0,24,24,13,ITA,None
13,Sassuolo,0,7943,#084018,44.8,29.0,0,23,23,14,ITA,None
14,Lecce,0,9888,#e12300,44.6,24.0,0,24,24,15,ITA,None
15,Salernitana,0,6480,#59181C,44.5,20.0,0,24,24,16,ITA,None
16,Hellas Verona,0,9876,#002F6C,44.4,21.0,0,24,24,17,ITA,None
17,Cagliari,0,8529,#B51F2B,43.9,22.0,0,24,24,18,ITA,None
18,Genoa,0,10233,#CB1111,43.7,25.0,0,24,24,19,ITA,None
19,Udinese,0,8600,#101010,39.5,24.0,0,24,24,20,ITA,None

In [175]:
pd.json_normalize(data['stats']['teams'][4]['topThree']).T #clean sheets

,0,1,2
id,0,0,0
name,Inter,Juventus,Torino
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,9885,9804
teamName,None,None,None
stat.name,clean_sheet_team,clean_sheet_team,clean_sheet_team
stat.value,14,12,11
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#FFFFFF,#9b2d22
teamColors.lightMode,#010E80,#000001,#680903
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [182]:
clean_sheets = requests.get(data['stats']['teams'][4]['fetchAllUrl'])
clean_sheets = clean_sheets.json()
pd.json_normalize(clean_sheets['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,14.0,23.0,0,23,14,1,ITA,None
1,Juventus,0,9885,#000001,12.0,24.0,0,24,12,2,ITA,None
2,Torino,0,9804,#680903,11.0,23.0,0,23,11,3,ITA,None
3,Bologna,0,9857,#102880,10.0,24.0,0,24,10,4,ITA,None
4,Atalanta,0,8524,#004ca6,10.0,23.0,0,23,10,5,ITA,None
5,AC Milan,0,8564,#CF2C27,9.0,24.0,0,24,9,6,ITA,None
6,Monza,0,6504,#EC173A,9.0,24.0,0,24,9,6,ITA,None
7,Lazio,0,8543,#75acd4,8.0,23.0,0,23,8,8,ITA,None
8,Empoli,0,8534,#005098,7.0,24.0,0,24,7,9,ITA,None
9,Udinese,0,8600,#101010,7.0,24.0,0,24,7,9,ITA,None
10,Fiorentina,0,8535,#5F259F,6.0,24.0,0,24,6,11,ITA,None
11,Roma,0,8686,#9c0922,6.0,24.0,0,24,6,11,ITA,None
12,SSC Napoli,0,9875,#12A0D7,6.0,23.0,0,23,6,13,ITA,None
13,Genoa,0,10233,#CB1111,5.0,24.0,0,24,5,14,ITA,None
14,Hellas Verona,0,9876,#002F6C,5.0,24.0,0,24,5,14,ITA,None
15,Cagliari,0,8529,#B51F2B,3.0,24.0,0,24,3,16,ITA,None
16,Frosinone,0,9891,#d5a300,2.0,24.0,0,24,2,17,ITA,None
17,Lecce,0,9888,#e12300,2.0,24.0,0,24,2,17,ITA,None
18,Salernitana,0,6480,#59181C,2.0,24.0,0,24,2,17,ITA,None
19,Sassuolo,0,7943,#084018,1.0,23.0,0,23,1,20,ITA,None

In [174]:
pd.json_normalize(data['stats']['teams'][5]['topThree']).T #expected goals (xG)

,0,1,2
id,0,0,0
name,Inter,AC Milan,SSC Napoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,8564,9875
teamName,None,None,None
stat.name,expected_goals_team,expected_goals_team,expected_goals_team
stat.value,47.9,38.8,37.2
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#1A5DD4,#CF2C27,#12A0D7
teamColors.lightMode,#010E80,#CF2C27,#12A0D7
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [183]:
xG = requests.get(data['stats']['teams'][5]['fetchAllUrl'])
xG = xG.json()
pd.json_normalize(xG['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,47.9,55.0,0,23,23,1,ITA,None
1,AC Milan,0,8564,#CF2C27,38.8,47.0,0,24,24,2,ITA,None
2,SSC Napoli,0,9875,#12A0D7,37.2,32.0,0,23,23,3,ITA,None
3,Juventus,0,9885,#000001,36.9,36.0,0,24,24,4,ITA,None
4,Atalanta,0,8524,#004ca6,34.1,44.0,0,23,23,5,ITA,None
5,Roma,0,8686,#9c0922,33.7,42.0,0,24,24,6,ITA,None
6,Fiorentina,0,8535,#5F259F,30.5,36.0,0,24,24,7,ITA,None
7,Bologna,0,9857,#102880,29.6,35.0,0,24,24,8,ITA,None
8,Lazio,0,8543,#75acd4,28.2,28.0,0,23,23,9,ITA,None
9,Frosinone,0,9891,#d5a300,28.1,32.0,0,24,24,10,ITA,None
10,Lecce,0,9888,#e12300,26.7,24.0,0,24,24,11,ITA,None
11,Cagliari,0,8529,#B51F2B,26.7,22.0,0,24,24,12,ITA,None
12,Sassuolo,0,7943,#084018,26.4,29.0,0,23,23,13,ITA,None
13,Udinese,0,8600,#101010,26.3,24.0,0,24,24,14,ITA,None
14,Monza,0,6504,#EC173A,24.5,21.0,0,24,24,15,ITA,None
15,Torino,0,9804,#680903,23.7,21.0,0,23,23,16,ITA,None
16,Empoli,0,8534,#005098,23.4,18.0,0,24,24,17,ITA,None
17,Hellas Verona,0,9876,#002F6C,22.9,21.0,0,24,24,18,ITA,None
18,Genoa,0,10233,#CB1111,20.9,25.0,0,24,24,19,ITA,None
19,Salernitana,0,6480,#59181C,19.0,20.0,0,24,24,20,ITA,None

In [173]:
pd.json_normalize(data['stats']['teams'][6]['topThree']).T #shots on target per match

,0,1,2
id,0,0,0
name,Atalanta,Inter,AC Milan
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8524,8636,8564
teamName,None,None,None
stat.name,ontarget_scoring_att_team,ontarget_scoring_att_team,ontarget_scoring_att_team
stat.value,5.5,5.3,5.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#1A5DD4,#CF2C27
teamColors.lightMode,#004ca6,#010E80,#CF2C27
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [184]:
SOT = requests.get(data['stats']['teams'][6]['fetchAllUrl'])
SOT = SOT.json()
pd.json_normalize(SOT['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Atalanta,0,8524,#004ca6,5.5,13.3,0,23,23,1,ITA,None
1,Inter,0,8636,#010E80,5.3,15.5,0,23,23,2,ITA,None
2,AC Milan,0,8564,#CF2C27,5.1,14.7,0,24,24,3,ITA,None
3,SSC Napoli,0,9875,#12A0D7,5.1,8.4,0,23,22,4,ITA,None
4,Bologna,0,9857,#102880,4.5,11.7,0,24,24,5,ITA,None
5,Fiorentina,0,8535,#5F259F,4.5,11.4,0,24,24,6,ITA,None
6,Sassuolo,0,7943,#084018,4.5,9.5,0,23,23,7,ITA,None
7,Udinese,0,8600,#101010,4.2,8.1,0,24,24,8,ITA,None
8,Juventus,0,9885,#000001,4.1,11.0,0,24,24,9,ITA,None
9,Lecce,0,9888,#e12300,4.0,7.5,0,24,23,10,ITA,None
10,Roma,0,8686,#9c0922,3.9,14.3,0,24,24,11,ITA,None
11,Frosinone,0,9891,#d5a300,3.9,12.0,0,24,23,12,ITA,None
12,Hellas Verona,0,9876,#002F6C,3.6,7.8,0,24,23,13,ITA,None
13,Cagliari,0,8529,#B51F2B,3.6,7.3,0,24,23,14,ITA,None
14,Monza,0,6504,#EC173A,3.4,7.2,0,24,24,15,ITA,None
15,Empoli,0,8534,#005098,3.4,6.3,0,24,23,16,ITA,None
16,Lazio,0,8543,#75acd4,3.3,11.0,0,23,23,17,ITA,None
17,Genoa,0,10233,#CB1111,3.3,9.9,0,24,24,18,ITA,None
18,Salernitana,0,6480,#59181C,3.3,7.8,0,24,24,19,ITA,None
19,Torino,0,9804,#680903,3.2,8.4,0,23,22,20,ITA,None

In [172]:
pd.json_normalize(data['stats']['teams'][7]['topThree']).T #big chances

,0,1,2
id,0,0,0
name,Inter,Atalanta,Roma
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,8524,8686
teamName,None,None,None
stat.name,big_chance_team,big_chance_team,big_chance_team
stat.value,68,60,59
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#0D68B1,#b90926
teamColors.lightMode,#010E80,#004ca6,#9c0922
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [185]:
big_chances = requests.get(data['stats']['teams'][7]['fetchAllUrl'])
big_chances = big_chances.json()
pd.json_normalize(big_chances['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,68.0,55.0,0,23,1,1,ITA,None
1,Atalanta,0,8524,#004ca6,60.0,44.0,0,23,1,2,ITA,None
2,Roma,0,8686,#9c0922,59.0,42.0,0,24,1,3,ITA,None
3,AC Milan,0,8564,#CF2C27,57.0,47.0,0,24,1,4,ITA,None
4,Juventus,0,9885,#000001,57.0,36.0,0,24,1,5,ITA,None
5,SSC Napoli,0,9875,#12A0D7,56.0,32.0,0,23,1,6,ITA,None
6,Frosinone,0,9891,#d5a300,49.0,32.0,0,24,1,7,ITA,None
7,Bologna,0,9857,#102880,48.0,35.0,0,24,1,8,ITA,None
8,Cagliari,0,8529,#B51F2B,42.0,22.0,0,24,1,9,ITA,None
9,Fiorentina,0,8535,#5F259F,41.0,36.0,0,24,1,10,ITA,None
10,Lazio,0,8543,#75acd4,41.0,28.0,0,23,1,11,ITA,None
11,Lecce,0,9888,#e12300,41.0,24.0,0,24,1,12,ITA,None
12,Udinese,0,8600,#101010,41.0,24.0,0,24,1,12,ITA,None
13,Hellas Verona,0,9876,#002F6C,38.0,21.0,0,24,1,14,ITA,None
14,Sassuolo,0,7943,#084018,37.0,29.0,0,23,1,15,ITA,None
15,Monza,0,6504,#EC173A,37.0,21.0,0,24,1,16,ITA,None
16,Torino,0,9804,#680903,37.0,21.0,0,23,1,16,ITA,None
17,Genoa,0,10233,#CB1111,31.0,25.0,0,24,1,18,ITA,None
18,Empoli,0,8534,#005098,30.0,18.0,0,24,1,19,ITA,None
19,Salernitana,0,6480,#59181C,23.0,20.0,0,24,1,20,ITA,None

In [171]:
pd.json_normalize(data['stats']['teams'][8]['topThree']).T #big chances missed

,0,1,2
id,0,0,0
name,Juventus,Atalanta,SSC Napoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9885,8524,9875
teamName,None,None,None
stat.name,big_chance_missed_team,big_chance_missed_team,big_chance_missed_team
stat.value,40,37,35
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#FFFFFF,#0D68B1,#12A0D7
teamColors.lightMode,#000001,#004ca6,#12A0D7
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [186]:
big_chances_missed = requests.get(data['stats']['teams'][8]['fetchAllUrl'])
big_chances_missed = big_chances_missed.json()
pd.json_normalize(big_chances_missed['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Juventus,0,9885,#000001,40.0,36.0,0,24,18,1,ITA,None
1,Atalanta,0,8524,#004ca6,37.0,44.0,0,23,17,2,ITA,None
2,SSC Napoli,0,9875,#12A0D7,35.0,32.0,0,23,16,3,ITA,None
3,Inter,0,8636,#010E80,34.0,55.0,0,23,16,4,ITA,None
4,Lecce,0,9888,#e12300,32.0,24.0,0,24,16,5,ITA,None
5,Frosinone,0,9891,#d5a300,31.0,32.0,0,24,13,6,ITA,None
6,Cagliari,0,8529,#B51F2B,31.0,22.0,0,24,15,7,ITA,None
7,Hellas Verona,0,9876,#002F6C,29.0,21.0,0,24,15,8,ITA,None
8,Roma,0,8686,#9c0922,27.0,42.0,0,24,16,9,ITA,None
9,Bologna,0,9857,#102880,27.0,35.0,0,24,13,10,ITA,None
10,Udinese,0,8600,#101010,27.0,24.0,0,24,15,11,ITA,None
11,Monza,0,6504,#EC173A,26.0,21.0,0,24,14,12,ITA,None
12,Fiorentina,0,8535,#5F259F,24.0,36.0,0,24,15,13,ITA,None
13,Lazio,0,8543,#75acd4,24.0,28.0,0,23,14,14,ITA,None
14,Torino,0,9804,#680903,24.0,21.0,0,23,12,15,ITA,None
15,AC Milan,0,8564,#CF2C27,22.0,47.0,0,24,13,16,ITA,None
16,Sassuolo,0,7943,#084018,20.0,29.0,0,23,13,17,ITA,None
17,Empoli,0,8534,#005098,20.0,18.0,0,24,11,18,ITA,None
18,Genoa,0,10233,#CB1111,19.0,25.0,0,24,12,19,ITA,None
19,Salernitana,0,6480,#59181C,14.0,20.0,0,24,12,20,ITA,None

In [170]:
pd.json_normalize(data['stats']['teams'][9]['topThree']).T #accurate passes per match

,0,1,2
id,0,0,0
name,SSC Napoli,Bologna,Inter
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9875,9857,8636
teamName,None,None,None
stat.name,accurate_pass_team,accurate_pass_team,accurate_pass_team
stat.value,479.9,470.4,451.7
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#12A0D7,#203faf,#1A5DD4
teamColors.lightMode,#12A0D7,#102880,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [187]:
acc_passes = requests.get(data['stats']['teams'][9]['fetchAllUrl'])
acc_passes = acc_passes.json()
pd.json_normalize(acc_passes['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,SSC Napoli,0,9875,#12A0D7,479.9,87.0,0,23,23,1,ITA,None
1,Bologna,0,9857,#102880,470.4,85.9,0,24,24,2,ITA,None
2,Inter,0,8636,#010E80,451.7,86.7,0,23,23,3,ITA,None
3,Lazio,0,8543,#75acd4,433.6,85.0,0,23,23,4,ITA,None
4,Monza,0,6504,#EC173A,430.3,85.6,0,24,24,5,ITA,None
5,AC Milan,0,8564,#CF2C27,427.0,86.5,0,24,24,6,ITA,None
6,Roma,0,8686,#9c0922,414.7,84.6,0,24,24,7,ITA,None
7,Fiorentina,0,8535,#5F259F,400.1,83.0,0,24,24,8,ITA,None
8,Atalanta,0,8524,#004ca6,394.3,81.9,0,23,23,9,ITA,None
9,Frosinone,0,9891,#d5a300,365.2,80.7,0,24,24,10,ITA,None
10,Juventus,0,9885,#000001,363.5,83.7,0,24,24,11,ITA,None
11,Torino,0,9804,#680903,356.8,81.5,0,23,23,12,ITA,None
12,Sassuolo,0,7943,#084018,310.0,80.1,0,23,23,13,ITA,None
13,Empoli,0,8534,#005098,300.8,79.0,0,24,24,14,ITA,None
14,Salernitana,0,6480,#59181C,292.8,77.9,0,24,24,15,ITA,None
15,Lecce,0,9888,#e12300,287.8,78.8,0,24,24,16,ITA,None
16,Genoa,0,10233,#CB1111,285.8,77.1,0,24,24,17,ITA,None
17,Cagliari,0,8529,#B51F2B,279.4,77.1,0,24,24,18,ITA,None
18,Hellas Verona,0,9876,#002F6C,265.0,75.4,0,24,24,19,ITA,None
19,Udinese,0,8600,#101010,246.8,77.7,0,24,24,20,ITA,None

In [168]:
pd.json_normalize(data['stats']['teams'][10]['topThree']).T #accurate long balls per match

,0,1,2
id,0,0,0
name,Fiorentina,Hellas Verona,SSC Napoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8535,9876,9875
teamName,None,None,None
stat.name,accurate_long_balls_team,accurate_long_balls_team,accurate_long_balls_team
stat.value,36.7,30.7,29.5
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#6f34af,#00449f,#12A0D7
teamColors.lightMode,#5F259F,#002F6C,#12A0D7
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [188]:
acc_lgballs = requests.get(data['stats']['teams'][10]['fetchAllUrl'])
acc_lgballs = acc_lgballs.json()
pd.json_normalize(acc_lgballs['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Fiorentina,0,8535,#5F259F,36.7,55.8,0,24,24,1,ITA,None
1,Hellas Verona,0,9876,#002F6C,30.7,48.4,0,24,24,2,ITA,None
2,SSC Napoli,0,9875,#12A0D7,29.5,56.9,0,23,23,3,ITA,None
3,Cagliari,0,8529,#B51F2B,28.1,46.7,0,24,24,4,ITA,None
4,Monza,0,6504,#EC173A,27.9,52.0,0,24,24,5,ITA,None
5,Inter,0,8636,#010E80,27.8,59.7,0,23,23,6,ITA,None
6,Juventus,0,9885,#000001,27.5,53.7,0,24,24,7,ITA,None
7,Lazio,0,8543,#75acd4,25.5,53.7,0,23,23,8,ITA,None
8,Roma,0,8686,#9c0922,25.5,51.0,0,24,24,9,ITA,None
9,Lecce,0,9888,#e12300,24.7,46.2,0,24,24,10,ITA,None
10,Atalanta,0,8524,#004ca6,24.1,46.3,0,23,23,11,ITA,None
11,Sassuolo,0,7943,#084018,23.6,44.7,0,23,23,12,ITA,None
12,Bologna,0,9857,#102880,23.3,50.7,0,24,24,13,ITA,None
13,Genoa,0,10233,#CB1111,23.0,41.6,0,24,24,14,ITA,None
14,Torino,0,9804,#680903,22.5,43.7,0,23,23,15,ITA,None
15,AC Milan,0,8564,#CF2C27,21.7,50.9,0,24,24,16,ITA,None
16,Empoli,0,8534,#005098,20.7,39.6,0,24,24,17,ITA,None
17,Udinese,0,8600,#101010,20.0,44.5,0,24,24,18,ITA,None
18,Frosinone,0,9891,#d5a300,19.1,38.1,0,24,24,19,ITA,None
19,Salernitana,0,6480,#59181C,18.4,37.6,0,24,24,20,ITA,None

In [167]:
pd.json_normalize(data['stats']['teams'][11]['topThree']).T #accurate crosses per match

,0,1,2
id,0,0,0
name,Atalanta,Cagliari,Inter
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8524,8529,8636
teamName,None,None,None
stat.name,accurate_cross_team,accurate_cross_team,accurate_cross_team
stat.value,6.4,6.2,6.0
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#B51F2B,#1A5DD4
teamColors.lightMode,#004ca6,#B51F2B,#010E80
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [189]:
acc_crosses = requests.get(data['stats']['teams'][11]['fetchAllUrl'])
acc_crosses = acc_crosses.json()
pd.json_normalize(acc_crosses['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Atalanta,0,8524,#004ca6,6.4,32.3,0,23,23,1,ITA,None
1,Cagliari,0,8529,#B51F2B,6.2,26.3,0,24,24,2,ITA,None
2,Inter,0,8636,#010E80,6.0,27.7,0,23,23,3,ITA,None
3,Juventus,0,9885,#000001,5.3,28.9,0,24,24,4,ITA,None
4,Hellas Verona,0,9876,#002F6C,5.3,28.8,0,24,24,5,ITA,None
5,Torino,0,9804,#680903,5.1,25.8,0,23,23,6,ITA,None
6,Monza,0,6504,#EC173A,4.5,28.5,0,24,22,7,ITA,None
7,Genoa,0,10233,#CB1111,4.5,28.1,0,24,22,8,ITA,None
8,AC Milan,0,8564,#CF2C27,4.5,26.7,0,24,23,9,ITA,None
9,Roma,0,8686,#9c0922,4.5,26.0,0,24,24,10,ITA,None
10,Fiorentina,0,8535,#5F259F,4.5,22.3,0,24,23,11,ITA,None
11,SSC Napoli,0,9875,#12A0D7,4.4,23.4,0,23,22,12,ITA,None
12,Udinese,0,8600,#101010,4.2,29.5,0,24,24,13,ITA,None
13,Empoli,0,8534,#005098,4.1,22.9,0,24,23,14,ITA,None
14,Lecce,0,9888,#e12300,4.0,24.3,0,24,23,15,ITA,None
15,Sassuolo,0,7943,#084018,3.7,21.2,0,23,23,16,ITA,None
16,Salernitana,0,6480,#59181C,3.6,22.3,0,24,22,17,ITA,None
17,Lazio,0,8543,#75acd4,3.2,19.7,0,23,21,18,ITA,None
18,Frosinone,0,9891,#d5a300,3.0,25.2,0,24,23,19,ITA,None
19,Bologna,0,9857,#102880,3.0,22.7,0,24,22,20,ITA,None

In [166]:
pd.json_normalize(data['stats']['teams'][12]['topThree']).T #penalties awarded

,0,1,2
id,0,0,0
name,Inter,Frosinone,Roma
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,9891,8686
teamName,None,None,None
stat.name,penalty_won_team,penalty_won_team,penalty_won_team
stat.value,9,7,7
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#E3AD00,#b90926
teamColors.lightMode,#010E80,#d5a300,#9c0922
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [190]:
pens = requests.get(data['stats']['teams'][12]['fetchAllUrl'])
pens = pens.json()
pd.json_normalize(pens['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,9.0,100.0,0,23,8,1,ITA,None
1,Frosinone,0,9891,#d5a300,7.0,100.0,0,24,7,2,ITA,None
2,Roma,0,8686,#9c0922,7.0,85.7,0,24,7,3,ITA,None
3,AC Milan,0,8564,#CF2C27,7.0,71.4,0,24,5,4,ITA,None
4,SSC Napoli,0,9875,#12A0D7,7.0,71.4,0,23,6,4,ITA,None
5,Hellas Verona,0,9876,#002F6C,6.0,33.3,0,24,5,6,ITA,None
6,Sassuolo,0,7943,#084018,5.0,100.0,0,23,4,7,ITA,None
7,Fiorentina,0,8535,#5F259F,5.0,60.0,0,24,5,8,ITA,None
8,Lazio,0,8543,#75acd4,4.0,100.0,0,23,4,9,ITA,None
9,Bologna,0,9857,#102880,4.0,75.0,0,24,4,10,ITA,None
10,Lecce,0,9888,#e12300,4.0,75.0,0,24,4,10,ITA,None
11,Juventus,0,9885,#000001,4.0,50.0,0,24,4,12,ITA,None
12,Monza,0,6504,#EC173A,3.0,66.7,0,24,3,13,ITA,None
13,Udinese,0,8600,#101010,3.0,66.7,0,24,3,13,ITA,None
14,Cagliari,0,8529,#B51F2B,3.0,33.3,0,24,3,15,ITA,None
15,Atalanta,0,8524,#004ca6,2.0,100.0,0,23,2,16,ITA,None
16,Empoli,0,8534,#005098,2.0,100.0,0,24,2,16,ITA,None
17,Genoa,0,10233,#CB1111,2.0,100.0,0,24,2,16,ITA,None
18,Salernitana,0,6480,#59181C,1.0,100.0,0,24,1,19,ITA,None
19,Torino,0,9804,#680903,1.0,100.0,0,23,1,19,ITA,None

In [165]:
pd.json_normalize(data['stats']['teams'][13]['topThree']).T #touches in opposition box

,0,1,2
id,0,0,0
name,Inter,SSC Napoli,Fiorentina
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8636,9875,8535
teamName,None,None,None
stat.name,touches_in_opp_box_team,touches_in_opp_box_team,touches_in_opp_box_team
stat.value,677,661,604
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#1A5DD4,#12A0D7,#6f34af
teamColors.lightMode,#010E80,#12A0D7,#5F259F
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [191]:
box_touches = requests.get(data['stats']['teams'][13]['fetchAllUrl'])
box_touches = box_touches.json()
pd.json_normalize(box_touches['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Inter,0,8636,#010E80,677.0,0.0,0,23,23,1,ITA,None
1,SSC Napoli,0,9875,#12A0D7,661.0,0.0,0,23,23,2,ITA,None
2,Fiorentina,0,8535,#5F259F,604.0,0.0,0,24,24,3,ITA,None
3,Juventus,0,9885,#000001,578.0,0.0,0,24,24,4,ITA,None
4,Atalanta,0,8524,#004ca6,577.0,0.0,0,23,23,5,ITA,None
5,AC Milan,0,8564,#CF2C27,568.0,0.0,0,24,24,6,ITA,None
6,Roma,0,8686,#9c0922,546.0,0.0,0,24,24,7,ITA,None
7,Monza,0,6504,#EC173A,498.0,0.0,0,24,24,8,ITA,None
8,Lazio,0,8543,#75acd4,487.0,0.0,0,23,23,9,ITA,None
9,Bologna,0,9857,#102880,486.0,0.0,0,24,24,10,ITA,None
10,Cagliari,0,8529,#B51F2B,471.0,0.0,0,24,24,11,ITA,None
11,Sassuolo,0,7943,#084018,462.0,0.0,0,23,23,12,ITA,None
12,Empoli,0,8534,#005098,454.0,0.0,0,24,24,13,ITA,None
13,Frosinone,0,9891,#d5a300,443.0,0.0,0,24,24,14,ITA,None
14,Torino,0,9804,#680903,442.0,0.0,0,23,23,15,ITA,None
15,Lecce,0,9888,#e12300,441.0,0.0,0,24,24,16,ITA,None
16,Udinese,0,8600,#101010,397.0,0.0,0,24,24,17,ITA,None
17,Salernitana,0,6480,#59181C,388.0,0.0,0,24,24,18,ITA,None
18,Genoa,0,10233,#CB1111,376.0,0.0,0,24,24,19,ITA,None
19,Hellas Verona,0,9876,#002F6C,375.0,0.0,0,24,24,20,ITA,None

In [163]:
pd.json_normalize(data['stats']['teams'][14]['topThree']).T #corners

,0,1,2
id,0,0,0
name,SSC Napoli,Inter,Atalanta
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9875,8636,8524
teamName,None,None,None
stat.name,corner_taken_team,corner_taken_team,corner_taken_team
stat.value,141,134,132
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#12A0D7,#1A5DD4,#0D68B1
teamColors.lightMode,#12A0D7,#010E80,#004ca6
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [162]:
corners = requests.get(data['stats']['teams'][14]['fetchAllUrl'])
corners = corners.json()
pd.json_normalize(corners['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,SSC Napoli,0,9875,#12A0D7,141.0,0.0,0,23,22,1,ITA,None
1,Inter,0,8636,#010E80,134.0,0.0,0,23,22,2,ITA,None
2,Atalanta,0,8524,#004ca6,132.0,0.0,0,23,23,3,ITA,None
3,Empoli,0,8534,#005098,123.0,0.0,0,24,24,4,ITA,None
4,Juventus,0,9885,#000001,123.0,0.0,0,24,24,4,ITA,None
5,Sassuolo,0,7943,#084018,121.0,0.0,0,23,23,6,ITA,None
6,Frosinone,0,9891,#d5a300,120.0,0.0,0,24,24,7,ITA,None
7,Monza,0,6504,#EC173A,119.0,0.0,0,24,24,8,ITA,None
8,Cagliari,0,8529,#B51F2B,118.0,0.0,0,24,24,9,ITA,None
9,Lazio,0,8543,#75acd4,117.0,0.0,0,23,22,10,ITA,None
10,Fiorentina,0,8535,#5F259F,114.0,0.0,0,24,23,11,ITA,None
11,Roma,0,8686,#9c0922,110.0,0.0,0,24,23,12,ITA,None
12,Udinese,0,8600,#101010,109.0,0.0,0,24,24,13,ITA,None
13,AC Milan,0,8564,#CF2C27,104.0,0.0,0,24,23,14,ITA,None
14,Torino,0,9804,#680903,101.0,0.0,0,23,22,15,ITA,None
15,Salernitana,0,6480,#59181C,100.0,0.0,0,24,22,16,ITA,None
16,Lecce,0,9888,#e12300,96.0,0.0,0,24,24,17,ITA,None
17,Genoa,0,10233,#CB1111,93.0,0.0,0,24,22,18,ITA,None
18,Bologna,0,9857,#102880,91.0,0.0,0,24,23,19,ITA,None
19,Hellas Verona,0,9876,#002F6C,80.0,0.0,0,24,23,20,ITA,None

In [161]:
pd.json_normalize(data['stats']['teams'][15]['topThree']).T #xG conceded

,0,1,2
id,0,0,0
name,Salernitana,Frosinone,Lecce
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,6480,9891,9888
teamName,None,None,None
stat.name,expected_goals_conceded_team,expected_goals_conceded_team,expected_goals_conceded_team
stat.value,43.9,38.9,37.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#ac4f47,#E3AD00,#e12300
teamColors.lightMode,#59181C,#d5a300,#e12300
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [160]:
xGA = requests.get(data['stats']['teams'][15]['fetchAllUrl'])
xGA = xGA.json()
pd.json_normalize(xGA['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Salernitana,0,6480,#59181C,43.9,47.0,0,24,24,1,ITA,None
1,Frosinone,0,9891,#d5a300,38.9,49.0,0,24,24,2,ITA,None
2,Lecce,0,9888,#e12300,37.1,37.0,0,24,24,3,ITA,None
3,Cagliari,0,8529,#B51F2B,36.4,45.0,0,24,24,4,ITA,None
4,Sassuolo,0,7943,#084018,35.1,42.0,0,23,23,5,ITA,None
5,Monza,0,6504,#EC173A,35.0,28.0,0,24,24,6,ITA,None
6,Udinese,0,8600,#101010,33.2,37.0,0,24,24,7,ITA,None
7,Empoli,0,8534,#005098,32.5,37.0,0,24,24,8,ITA,None
8,Fiorentina,0,8535,#5F259F,31.8,28.0,0,24,24,9,ITA,None
9,Hellas Verona,0,9876,#002F6C,30.1,32.0,0,24,24,10,ITA,None
10,AC Milan,0,8564,#CF2C27,29.7,27.0,0,24,24,11,ITA,None
11,Genoa,0,10233,#CB1111,25.0,30.0,0,24,24,12,ITA,None
12,Lazio,0,8543,#75acd4,24.4,24.0,0,23,23,13,ITA,None
13,SSC Napoli,0,9875,#12A0D7,24.2,27.0,0,23,23,14,ITA,None
14,Bologna,0,9857,#102880,23.7,22.0,0,24,24,15,ITA,None
15,Atalanta,0,8524,#004ca6,23.5,23.0,0,23,23,16,ITA,None
16,Roma,0,8686,#9c0922,22.7,30.0,0,24,24,17,ITA,None
17,Torino,0,9804,#680903,22.1,20.0,0,23,23,18,ITA,None
18,Inter,0,8636,#010E80,19.0,12.0,0,23,23,19,ITA,None
19,Juventus,0,9885,#000001,17.3,15.0,0,24,24,20,ITA,None

In [159]:
pd.json_normalize(data['stats']['teams'][16]['topThree']).T #interceptions per match

,0,1,2
id,0,0,0
name,Atalanta,Lecce,Torino
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8524,9888,9804
teamName,None,None,None
stat.name,interception_team,interception_team,interception_team
stat.value,9.5,9.1,9.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#e12300,#9b2d22
teamColors.lightMode,#004ca6,#e12300,#680903
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [158]:
interceptions = requests.get(data['stats']['teams'][16]['fetchAllUrl'])
interceptions = interceptions.json()
pd.json_normalize(interceptions['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Atalanta,0,8524,#004ca6,9.5,219.0,0,23,23,1,ITA,None
1,Lecce,0,9888,#e12300,9.1,218.0,0,24,24,2,ITA,None
2,Torino,0,9804,#680903,9.1,209.0,0,23,23,3,ITA,None
3,Genoa,0,10233,#CB1111,9.0,216.0,0,24,24,4,ITA,None
4,Udinese,0,8600,#101010,8.8,211.0,0,24,24,5,ITA,None
5,Lazio,0,8543,#75acd4,7.9,181.0,0,23,23,6,ITA,None
6,Inter,0,8636,#010E80,7.7,177.0,0,23,23,7,ITA,None
7,Monza,0,6504,#EC173A,7.6,182.0,0,24,24,8,ITA,None
8,Salernitana,0,6480,#59181C,7.6,182.0,0,24,24,8,ITA,None
9,Hellas Verona,0,9876,#002F6C,7.4,178.0,0,24,24,10,ITA,None
10,Empoli,0,8534,#005098,7.4,177.0,0,24,24,11,ITA,None
11,Cagliari,0,8529,#B51F2B,7.3,176.0,0,24,24,12,ITA,None
12,Juventus,0,9885,#000001,7.2,172.0,0,24,24,13,ITA,None
13,AC Milan,0,8564,#CF2C27,7.0,169.0,0,24,23,14,ITA,None
14,Sassuolo,0,7943,#084018,7.0,160.0,0,23,23,15,ITA,None
15,Bologna,0,9857,#102880,6.9,166.0,0,24,24,16,ITA,None
16,Frosinone,0,9891,#d5a300,6.3,152.0,0,24,24,17,ITA,None
17,Fiorentina,0,8535,#5F259F,6.3,150.0,0,24,24,18,ITA,None
18,SSC Napoli,0,9875,#12A0D7,6.3,146.0,0,23,23,19,ITA,None
19,Roma,0,8686,#9c0922,6.0,145.0,0,24,24,20,ITA,None

In [157]:
pd.json_normalize(data['stats']['teams'][17]['topThree']).T #successful tackles per match

,0,1,2
id,0,0,0
name,Bologna,Lecce,Empoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9857,9888,8534
teamName,None,None,None
stat.name,won_tackle_team,won_tackle_team,won_tackle_team
stat.value,10.4,10.3,10.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#203faf,#e12300,#0767e5
teamColors.lightMode,#102880,#e12300,#005098
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [156]:
tackles = requests.get(data['stats']['teams'][17]['fetchAllUrl'])
tackles = tackles.json()
pd.json_normalize(tackles['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Bologna,0,9857,#102880,10.4,60.1,0,24,24,1,ITA,None
1,Lecce,0,9888,#e12300,10.3,61.3,0,24,24,2,ITA,None
2,Empoli,0,8534,#005098,10.3,60.7,0,24,24,3,ITA,None
3,Udinese,0,8600,#101010,10.2,64.0,0,24,24,4,ITA,None
4,Atalanta,0,8524,#004ca6,10.0,61.5,0,23,23,5,ITA,None
5,Hellas Verona,0,9876,#002F6C,9.8,61.5,0,24,24,6,ITA,None
6,Genoa,0,10233,#CB1111,9.5,56.9,0,24,24,7,ITA,None
7,Juventus,0,9885,#000001,9.4,64.0,0,24,24,8,ITA,None
8,Lazio,0,8543,#75acd4,9.3,59.7,0,23,23,9,ITA,None
9,Roma,0,8686,#9c0922,9.3,59.2,0,24,24,10,ITA,None
10,Fiorentina,0,8535,#5F259F,9.3,57.7,0,24,24,11,ITA,None
11,Inter,0,8636,#010E80,9.0,60.2,0,23,23,12,ITA,None
12,SSC Napoli,0,9875,#12A0D7,9.0,57.0,0,23,23,13,ITA,None
13,Monza,0,6504,#EC173A,9.0,56.2,0,24,24,14,ITA,None
14,Salernitana,0,6480,#59181C,8.9,61.1,0,24,24,15,ITA,None
15,AC Milan,0,8564,#CF2C27,8.8,56.9,0,24,24,16,ITA,None
16,Frosinone,0,9891,#d5a300,8.6,58.9,0,24,24,17,ITA,None
17,Cagliari,0,8529,#B51F2B,8.3,60.1,0,24,24,18,ITA,None
18,Torino,0,9804,#680903,7.8,62.6,0,23,23,19,ITA,None
19,Sassuolo,0,7943,#084018,7.7,60.2,0,23,23,20,ITA,None

In [155]:
pd.json_normalize(data['stats']['teams'][18]['topThree']).T #clearances per match

,0,1,2
id,0,0,0
name,Udinese,Empoli,Frosinone
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8600,8534,9891
teamName,None,None,None
stat.name,effective_clearance_team,effective_clearance_team,effective_clearance_team
stat.value,23.0,20.4,19.9
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#ffffff,#0767e5,#E3AD00
teamColors.lightMode,#101010,#005098,#d5a300
teamColors.fontDarkMode,"rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [154]:
clearances = requests.get(data['stats']['teams'][18]['fetchAllUrl'])
clearances = clearances.json()
pd.json_normalize(clearances['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Udinese,0,8600,#101010,23.0,553.0,0,24,24,1,ITA,None
1,Empoli,0,8534,#005098,20.4,490.0,0,24,24,2,ITA,None
2,Frosinone,0,9891,#d5a300,19.9,478.0,0,24,24,3,ITA,None
3,Genoa,0,10233,#CB1111,19.7,472.0,0,24,24,4,ITA,None
4,Salernitana,0,6480,#59181C,19.6,470.0,0,24,24,5,ITA,None
5,Juventus,0,9885,#000001,19.4,465.0,0,24,24,6,ITA,None
6,Hellas Verona,0,9876,#002F6C,19.3,462.0,0,24,24,7,ITA,None
7,Cagliari,0,8529,#B51F2B,18.8,452.0,0,24,24,8,ITA,None
8,Sassuolo,0,7943,#084018,18.4,423.0,0,23,23,9,ITA,None
9,Lecce,0,9888,#e12300,17.4,417.0,0,24,24,10,ITA,None
10,Bologna,0,9857,#102880,17.0,408.0,0,24,24,11,ITA,None
11,Lazio,0,8543,#75acd4,16.0,368.0,0,23,23,12,ITA,None
12,Atalanta,0,8524,#004ca6,15.4,354.0,0,23,23,13,ITA,None
13,Monza,0,6504,#EC173A,15.3,366.0,0,24,24,14,ITA,None
14,Torino,0,9804,#680903,15.0,344.0,0,23,23,15,ITA,None
15,Roma,0,8686,#9c0922,14.7,353.0,0,24,24,16,ITA,None
16,AC Milan,0,8564,#CF2C27,14.5,348.0,0,24,24,17,ITA,None
17,SSC Napoli,0,9875,#12A0D7,13.8,317.0,0,23,23,18,ITA,None
18,Inter,0,8636,#010E80,13.7,315.0,0,23,23,19,ITA,None
19,Fiorentina,0,8535,#5F259F,13.3,319.0,0,24,24,20,ITA,None

In [152]:
pd.json_normalize(data['stats']['teams'][19]['topThree']).T #possession won final 3rd per match

,0,1,2
id,0,0,0
name,Atalanta,Fiorentina,Empoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8524,8535,8534
teamName,None,None,None
stat.name,poss_won_att_3rd_team,poss_won_att_3rd_team,poss_won_att_3rd_team
stat.value,5.8,5.5,5.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#0D68B1,#6f34af,#0767e5
teamColors.lightMode,#004ca6,#5F259F,#005098
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [153]:
final_3rd_poss_won = requests.get(data['stats']['teams'][19]['fetchAllUrl'])
final_3rd_poss_won = final_3rd_poss_won.json()
pd.json_normalize(final_3rd_poss_won['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Atalanta,0,8524,#004ca6,5.8,612.0,0,23,23,1,ITA,None
1,Fiorentina,0,8535,#5F259F,5.5,603.0,0,24,24,2,ITA,None
2,Empoli,0,8534,#005098,5.1,453.0,0,24,24,3,ITA,None
3,Lecce,0,9888,#e12300,4.7,568.0,0,24,23,4,ITA,None
4,Torino,0,9804,#680903,4.7,557.0,0,23,23,5,ITA,None
5,Inter,0,8636,#010E80,4.6,476.0,0,23,22,6,ITA,None
6,Frosinone,0,9891,#d5a300,4.5,570.0,0,24,23,7,ITA,None
7,Cagliari,0,8529,#B51F2B,4.4,502.0,0,24,24,8,ITA,None
8,SSC Napoli,0,9875,#12A0D7,4.3,540.0,0,23,23,9,ITA,None
9,Sassuolo,0,7943,#084018,4.2,453.0,0,23,23,10,ITA,None
10,Lazio,0,8543,#75acd4,4.0,542.0,0,23,23,11,ITA,None
11,Genoa,0,10233,#CB1111,3.8,470.0,0,24,23,12,ITA,None
12,Juventus,0,9885,#000001,3.6,444.0,0,24,23,13,ITA,None
13,Bologna,0,9857,#102880,3.3,506.0,0,24,23,14,ITA,None
14,Udinese,0,8600,#101010,3.3,503.0,0,24,21,15,ITA,None
15,AC Milan,0,8564,#CF2C27,3.3,480.0,0,24,23,16,ITA,None
16,Roma,0,8686,#9c0922,3.0,501.0,0,24,24,17,ITA,None
17,Hellas Verona,0,9876,#002F6C,2.9,600.0,0,24,22,18,ITA,None
18,Monza,0,6504,#EC173A,2.9,406.0,0,24,22,19,ITA,None
19,Salernitana,0,6480,#59181C,2.8,485.0,0,24,20,20,ITA,None

In [151]:
pd.json_normalize(data['stats']['teams'][20]['topThree']).T #penalties conceded

,0,1,2
id,0,0,0
name,Salernitana,Udinese,Sassuolo
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,6480,8600,7943
teamName,None,None,None
stat.name,penalty_conceded_team,penalty_conceded_team,penalty_conceded_team
stat.value,9,7,7
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#ac4f47,#ffffff,#00A752
teamColors.lightMode,#59181C,#101010,#084018
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(29, 29, 29, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [150]:
pens = requests.get(data['stats']['teams'][20]['fetchAllUrl'])
pens = pens.json()
pd.json_normalize(pens['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Salernitana,0,6480,#59181C,9.0,9.0,0,24,9,1,ITA,None
1,Udinese,0,8600,#101010,7.0,7.0,0,24,6,2,ITA,None
2,Sassuolo,0,7943,#084018,7.0,5.0,0,23,6,3,ITA,None
3,Fiorentina,0,8535,#5F259F,6.0,5.0,0,24,6,4,ITA,None
4,Monza,0,6504,#EC173A,6.0,5.0,0,24,5,4,ITA,None
5,Bologna,0,9857,#102880,6.0,3.0,0,24,5,6,ITA,None
6,AC Milan,0,8564,#CF2C27,5.0,5.0,0,24,5,7,ITA,None
7,Atalanta,0,8524,#004ca6,5.0,4.0,0,23,5,8,ITA,None
8,Lecce,0,9888,#e12300,5.0,4.0,0,24,5,8,ITA,None
9,Empoli,0,8534,#005098,5.0,3.0,0,24,5,10,ITA,None
10,Frosinone,0,9891,#d5a300,5.0,3.0,0,24,4,10,ITA,None
11,Inter,0,8636,#010E80,4.0,2.0,0,23,4,12,ITA,None
12,Torino,0,9804,#680903,3.0,3.0,0,23,2,13,ITA,None
13,Cagliari,0,8529,#B51F2B,3.0,2.0,0,24,3,14,ITA,None
14,Roma,0,8686,#9c0922,3.0,2.0,0,24,3,14,ITA,None
15,Lazio,0,8543,#75acd4,2.0,2.0,0,23,2,16,ITA,None
16,Genoa,0,10233,#CB1111,2.0,1.0,0,24,2,17,ITA,None
17,SSC Napoli,0,9875,#12A0D7,2.0,1.0,0,23,2,17,ITA,None
18,Hellas Verona,0,9876,#002F6C,1.0,1.0,0,24,1,19,ITA,None

In [146]:
pd.json_normalize(data['stats']['teams'][21]['topThree']).T #saves per match

,0,1,2
id,0,0,0
name,Monza,Empoli,Salernitana
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,6504,8534,6480
teamName,None,None,None
stat.name,saves_team,saves_team,saves_team
stat.value,3.8,3.5,3.3
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#EC173A,#0767e5,#ac4f47
teamColors.lightMode,#EC173A,#005098,#59181C
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [149]:
saves = requests.get(data['stats']['teams'][21]['fetchAllUrl'])
saves = saves.json()
pd.json_normalize(saves['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Monza,0,6504,#EC173A,3.8,91.0,0,24,23,1,ITA,None
1,Empoli,0,8534,#005098,3.5,83.0,0,24,23,2,ITA,None
2,Salernitana,0,6480,#59181C,3.3,80.0,0,24,21,3,ITA,None
3,Frosinone,0,9891,#d5a300,3.2,77.0,0,24,23,4,ITA,None
4,Lecce,0,9888,#e12300,3.2,77.0,0,24,23,4,ITA,None
5,Hellas Verona,0,9876,#002F6C,3.1,75.0,0,24,21,6,ITA,None
6,Fiorentina,0,8535,#5F259F,3.0,72.0,0,24,21,7,ITA,None
7,AC Milan,0,8564,#CF2C27,3.0,71.0,0,24,23,8,ITA,None
8,Torino,0,9804,#680903,3.0,68.0,0,23,22,9,ITA,None
9,Udinese,0,8600,#101010,2.8,66.0,0,24,21,10,ITA,None
10,Lazio,0,8543,#75acd4,2.7,62.0,0,23,21,11,ITA,None
11,Atalanta,0,8524,#004ca6,2.7,61.0,0,23,20,12,ITA,None
12,Sassuolo,0,7943,#084018,2.6,60.0,0,23,20,13,ITA,None
13,Genoa,0,10233,#CB1111,2.5,61.0,0,24,22,14,ITA,None
14,Bologna,0,9857,#102880,2.5,59.0,0,24,22,15,ITA,None
15,Cagliari,0,8529,#B51F2B,2.5,59.0,0,24,22,15,ITA,None
16,Inter,0,8636,#010E80,2.3,53.0,0,23,22,17,ITA,None
17,Juventus,0,9885,#000001,2.2,53.0,0,24,20,18,ITA,None
18,SSC Napoli,0,9875,#12A0D7,2.2,50.0,0,23,19,19,ITA,None
19,Roma,0,8686,#9c0922,2.1,51.0,0,24,21,20,ITA,None

In [142]:
pd.json_normalize(data['stats']['teams'][22]['topThree']).T #fouls per match

,0,1,2
id,0,0,0
name,Lecce,Hellas Verona,Empoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9888,9876,8534
teamName,None,None,None
stat.name,fk_foul_lost_team,fk_foul_lost_team,fk_foul_lost_team
stat.value,13.5,13.5,13.1
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#e12300,#00449f,#0767e5
teamColors.lightMode,#e12300,#002F6C,#005098
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [143]:
fouls_json = requests.get(data['stats']['teams'][22]['fetchAllUrl'])
fouls = fouls_json.json()
pd.json_normalize(fouls['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Lecce,0,9888,#e12300,13.5,62.0,0,24,24,1,ITA,None
1,Hellas Verona,0,9876,#002F6C,13.5,54.0,0,24,24,2,ITA,None
2,Empoli,0,8534,#005098,13.1,53.0,0,24,24,3,ITA,None
3,Udinese,0,8600,#101010,12.8,54.0,0,24,24,4,ITA,None
4,Fiorentina,0,8535,#5F259F,12.7,53.0,0,24,24,5,ITA,None
5,Atalanta,0,8524,#004ca6,12.6,45.0,0,23,23,6,ITA,None
6,Salernitana,0,6480,#59181C,12.5,57.0,0,24,24,7,ITA,None
7,Juventus,0,9885,#000001,12.3,58.0,0,24,24,8,ITA,None
8,Roma,0,8686,#9c0922,12.3,58.0,0,24,24,8,ITA,None
9,Cagliari,0,8529,#B51F2B,12.3,43.0,0,24,24,10,ITA,None
10,Lazio,0,8543,#75acd4,12.1,60.0,0,23,23,11,ITA,None
11,Bologna,0,9857,#102880,12.1,57.0,0,24,24,12,ITA,None
12,Monza,0,6504,#EC173A,12.0,52.0,0,24,24,13,ITA,None
13,Torino,0,9804,#680903,11.9,51.0,0,23,23,14,ITA,None
14,Genoa,0,10233,#CB1111,11.5,56.0,0,24,24,15,ITA,None
15,Inter,0,8636,#010E80,11.4,31.0,0,23,23,16,ITA,None
16,AC Milan,0,8564,#CF2C27,11.3,53.0,0,24,24,17,ITA,None
17,SSC Napoli,0,9875,#12A0D7,10.3,51.0,0,23,23,18,ITA,None
18,Frosinone,0,9891,#d5a300,10.1,49.0,0,24,24,19,ITA,None
19,Sassuolo,0,7943,#084018,10.1,44.0,0,23,23,20,ITA,None

In [141]:
pd.json_normalize(data['stats']['teams'][23]['topThree']).T #yellows

,0,1,2
id,0,0,0
name,Lecce,Lazio,Roma
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,9888,8543,8686
teamName,None,None,None
stat.name,total_yel_card_team,total_yel_card_team,total_yel_card_team
stat.value,62,60,58
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#e12300,#75acd4,#b90926
teamColors.lightMode,#e12300,#75acd4,#9c0922
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [140]:
yellow_json = requests.get(data['stats']['teams'][23]['fetchAllUrl'])
yellow_cards = yellow_json.json()
pd.json_normalize(yellow_cards['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Lecce,0,9888,#e12300,62.0,3.0,0,24,24,1,ITA,None
1,Lazio,0,8543,#75acd4,60.0,1.0,0,23,22,2,ITA,None
2,Roma,0,8686,#9c0922,58.0,2.0,0,24,23,3,ITA,None
3,Juventus,0,9885,#000001,58.0,1.0,0,24,23,4,ITA,None
4,Salernitana,0,6480,#59181C,57.0,3.0,0,24,22,5,ITA,None
5,Bologna,0,9857,#102880,57.0,1.0,0,24,24,6,ITA,None
6,Genoa,0,10233,#CB1111,56.0,3.0,0,24,23,7,ITA,None
7,Hellas Verona,0,9876,#002F6C,54.0,4.0,0,24,23,8,ITA,None
8,Udinese,0,8600,#101010,54.0,2.0,0,24,23,9,ITA,None
9,AC Milan,0,8564,#CF2C27,53.0,5.0,0,24,23,10,ITA,None
10,Empoli,0,8534,#005098,53.0,0.0,0,24,24,11,ITA,None
11,Fiorentina,0,8535,#5F259F,53.0,0.0,0,24,24,11,ITA,None
12,Monza,0,6504,#EC173A,52.0,3.0,0,24,23,13,ITA,None
13,SSC Napoli,0,9875,#12A0D7,51.0,4.0,0,23,21,14,ITA,None
14,Torino,0,9804,#680903,51.0,0.0,0,23,21,15,ITA,None
15,Frosinone,0,9891,#d5a300,49.0,2.0,0,24,22,16,ITA,None
16,Atalanta,0,8524,#004ca6,45.0,1.0,0,23,19,17,ITA,None
17,Sassuolo,0,7943,#084018,44.0,3.0,0,23,21,18,ITA,None
18,Cagliari,0,8529,#B51F2B,43.0,4.0,0,24,22,19,ITA,None
19,Inter,0,8636,#010E80,31.0,0.0,0,23,18,20,ITA,None

In [123]:
pd.json_normalize(data['stats']['teams'][24]['topThree']).T #reds

,0,1,2
id,0,0,0
name,AC Milan,Hellas Verona,SSC Napoli
rank,1,2,3
ccode,ITA,ITA,ITA
teamId,8564,9876,9875
teamName,None,None,None
stat.name,total_red_card_team,total_red_card_team,total_red_card_team
stat.value,5,4,4
stat.format,number,number,number
stat.fractions,0,0,0
teamColors.darkMode,#CF2C27,#00449f,#12A0D7
teamColors.lightMode,#CF2C27,#002F6C,#12A0D7
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [138]:
red_cards_json = requests.get(data['stats']['teams'][24]['fetchAllUrl'])
red_cards = red_cards_json.json()
pd.json_normalize(red_cards['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,AC Milan,0,8564,#CF2C27,5.0,53.0,0,24,5,1,ITA,None
1,Hellas Verona,0,9876,#002F6C,4.0,54.0,0,24,4,2,ITA,None
2,SSC Napoli,0,9875,#12A0D7,4.0,51.0,0,23,3,3,ITA,None
3,Cagliari,0,8529,#B51F2B,4.0,43.0,0,24,4,4,ITA,None
4,Lecce,0,9888,#e12300,3.0,62.0,0,24,3,5,ITA,None
5,Salernitana,0,6480,#59181C,3.0,57.0,0,24,3,6,ITA,None
6,Genoa,0,10233,#CB1111,3.0,56.0,0,24,3,7,ITA,None
7,Monza,0,6504,#EC173A,3.0,52.0,0,24,3,8,ITA,None
8,Sassuolo,0,7943,#084018,3.0,44.0,0,23,3,9,ITA,None
9,Roma,0,8686,#9c0922,2.0,58.0,0,24,1,10,ITA,None
10,Udinese,0,8600,#101010,2.0,54.0,0,24,2,11,ITA,None
11,Frosinone,0,9891,#d5a300,2.0,49.0,0,24,2,12,ITA,None
12,Lazio,0,8543,#75acd4,1.0,60.0,0,23,1,13,ITA,None
13,Juventus,0,9885,#000001,1.0,58.0,0,24,1,14,ITA,None
14,Bologna,0,9857,#102880,1.0,57.0,0,24,1,15,ITA,None
15,Atalanta,0,8524,#004ca6,1.0,45.0,0,23,1,16,ITA,None

In [102]:
pd.json_normalize(data['stats']['trophies'])

,seasonName,winner.id,winner.seasonName,winner.name,winner.winner,loser.id,loser.seasonName,loser.name,loser.winner
0,2022/2023,9875.0,2022/2023,SSC Napoli,True,8543,2022/2023,Lazio,False
1,2021/2022,8564.0,2021/2022,AC Milan,True,8636,2021/2022,Inter,False
2,2020/2021,8636.0,2020/2021,Inter,True,8564,2020/2021,AC Milan,False
3,2019/2020,9885.0,2019/2020,Juventus,True,8636,2019/2020,Inter,False
4,2018/2019,9885.0,2018/2019,Juventus,True,9875,2018/2019,SSC Napoli,False
...,...,...,...,...,...,...,...,...,...
114,1902,10233.0,1902,Genoa,True,8564,1902,AC Milan,False
115,1901,8564.0,1901,AC Milan,True,10233,1901,Genoa,False
116,1900,10233.0,1900,Genoa,True,-1,1900,Internazionale FC Torino,False
117,1899,10233.0,1899,Genoa,True,-1,1899,Internazionale FC Torino,False
118,1898,10233.0,1898,Genoa,True,-1,1898,Internazionale FC Torino,False

In [117]:
pd.json_normalize(data['transfers']['data'])

,name,playerId,transferDate,transferText,fromClub,fromClubId,toClub,toClubId,contractExtension,onLoan,...,marketValue,position.label,position.key,fee.feeText,fee.localizedFeeText,transferType.text,transferType.localizationKey,position,fee,fee.value
0,Marko Rog,552040,2024-02-13T09:09:31Z,"[None, None, None]",Cagliari,8529,Dinamo Zagreb,10156,False,True,...,1600000.0,DM,centerdefensivemidfielder_short,on loan,on_loan,on loan,on_loan,NaN,NaN,NaN
1,Alassane Sidibe,1330957,2024-02-11T19:20:31Z,"[None, None, None]",Atalanta,8524,Arka Gdynia,-1,False,True,...,750000.0,NaN,NaN,on loan,on_loan,on loan,on_loan,NaN,NaN,NaN
2,Mehdi Bourabia,187288,2024-02-09T20:24:54Z,"[None, None, None]",Frosinone,9891,Kayserispor,10182,False,False,...,1500000.0,CM,centermidfielder_short,NaN,NaN,contract,contract,NaN,NaN,NaN
3,Konstantinos Manolas,161683,2024-02-09T17:25:09Z,"[None, None, None]",Al-Sharjah,-1,Salernitana,6480,False,False,...,4400000.0,CB,centerback_short,free transfer,transfer_type_free_transfer,contract,contract,NaN,NaN,NaN
4,Iwo Kaczmarski,1137015,2024-02-07T13:24:05Z,"[None, None, None]",Empoli,8534,Miedz Legnica,8048,False,True,...,350000.0,CM,centermidfielder_short,on loan,on_loan,on loan,on_loan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Elayis Tavsan,983047,2024-01-23T19:07:25Z,"[None, None, None]",NEC Nijmegen,8464,Hellas Verona,9876,False,False,...,1600000.0,RW,rightwinger_short,fee,transfer_fee,contract,contract,NaN,NaN,500000.0
96,Tijjani Noslin,1282285,2024-01-23T19:06:05Z,"[None, None, None]",Fortuna Sittard,6422,Hellas Verona,9876,False,False,...,2950000.0,RW,rightwinger_short,fee,transfer_fee,contract,contract,NaN,NaN,3000000.0
97,Elio Capradossi,673737,2024-01-23T10:49:36Z,"[None, None, None]",Cagliari,8529,Free agent,2,False,False,...,760000.0,CB,centerback_short,NaN,NaN,contract,contract,NaN,NaN,NaN
98,Tiago Djalo,866358,2024-01-22T19:40:48Z,"[None, None, None]",Lille,8639,Juventus,9885,False,False,...,16000000.0,CB,centerback_short,fee,transfer_fee,contract,contract,NaN,NaN,3600000.0
99,Luka Romero,1160089,2024-01-22T18:21:56Z,"[None, None, None]",AC Milan,8564,Almeria,9865,False,True,...,4000000.0,RW,rightwinger_short,on loan,on_loan,on loan,on_loan,NaN,NaN,NaN