In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json

In [2]:
link = 'https://www.fotmob.com/teams/9857/overview/bologna'
res = requests.get(link)
soup = BeautifulSoup(res.content, 'lxml')
scripts = soup.find_all('script')

- PPDA: passes allowed per defensive action in the opposition half
- OPPDA: opponent passes per defensive action in the opposition
- Deep completions (DC, "deep"): Passes completed within an estimated 20 yards of goal (crosses excluded)
- Opposition Deep completions (ODC, "deep_allowed"): Opponent passes completed within an estimated 20 yards of goal (crosses excluded)
- xGChain: Total xG of every possession the player is involved in
- xGBuildup: Total xG of every possession the player is involved in without key passes and shots

In [3]:
data = scripts[35].string
before, sep, after = data.partition(',"seo"')

In [4]:
def check_json_brackets(json_string):
    square_brackets = 0  # For []
    curly_brackets = 0   # For {}

    for char in json_string:
        if char == '[':
            square_brackets += 1
        elif char == ']':
            square_brackets -= 1
        elif char == '{':
            curly_brackets += 1
        elif char == '}':
            curly_brackets -= 1

    return square_brackets, curly_brackets

# Replace with your actual JSON string
json_string = before
square, curly = check_json_brackets(json_string)

print("Mismatch in square brackets: ", square)
print("Mismatch in curly brackets: ", curly)

Mismatch in square brackets:  0
Mismatch in curly brackets:  0

In [5]:
#correcting the JSON string in order to be able to parse it
data = json.loads(before)
data = data['props']['pageProps']['fallback']['team-9857']

In [6]:
data['details']

{'id': 9857,
 'type': 'team',
 'name': 'Bologna',
 'latestSeason': '2023/2024',
 'shortName': 'Bologna',
 'country': 'ITA',
 'faqJSONLD': {'@context': 'https://schema.org',
  '@type': 'FAQPage',
  'mainEntity': [{'@type': 'Question',
    'name': "When is Bologna's next match?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': "Bologna's next match is at 17:00 GMT on Sat, 9 Mar 2024 against Inter."}},
   {'@type': 'Question',
    'name': "Who is Bologna's top scorer?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': 'Joshua Zirkzee has scored the most goals for Bologna, with 10 goals.'}},
   {'@type': 'Question',
    'name': "Who is Bologna's best player?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': 'Lewis Ferguson is the top-rated player for Bologna with a FotMob rating of 7.39.'}},
   {'@type': 'Question',
    'name': 'Who has the most assists for Bologna?',
    'acceptedAnswer': {'@type': 'Answer',
     'text': 'Lewis Ferguson has the most assists on Bologna, with 3 assists.'}},
   {'@type': 'Question',
    'name': "Where is Bologna's stadium?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': "Bologna stadium is located in Bologna and is called Stadio Renato Dall'Ara."}},
   {'@type': 'Question',
    'name': "What is the capacity of Stadio Renato Dall'Ara?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': "The capacity for Stadio Renato Dall'Ara is 39279."}},
   {'@type': 'Question',
    'name': "When was Stadio Renato Dall'Ara opened?",
    'acceptedAnswer': {'@type': 'Answer',
     'text': "Stadio Renato Dall'Ara opened in 1927."}}]},
 'sportsTeamJSONLD': {'@context': 'https://schema.org',
  '@type': 'SportsTeam',
  'name': 'Bologna',
  'sport': 'Football/Soccer',
  'gender': 'https://schema.org/Male',
  'logo': 'https://images.fotmob.com/image_resources/logo/teamlogo/9857.png',
  'url': 'https://www.fotmob.com/teams/9857/overview/bologna',
  'athlete': [],
  'location': {'@type': 'Place',
   'name': "Stadio Renato Dall'Ara",
   'address': {'@type': 'PostalAddress',
    'addressCountry': 'Italy',
    'addressLocality': 'Bologna'},
   'geo': {'@type': 'GeoCoordinates',
    'latitude': '44.492290',
    'longitude': '11.309957'}},
  'memberOf': {'@type': 'SportsOrganization',
   'name': 'Serie A',
   'url': 'https://www.fotmob.com/leagues/55/overview/serie'}},
 'breadcrumbJSONLD': {'@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  'itemListElement': [{'@type': 'ListItem',
    'position': 1,
    'name': 'Home',
    'item': 'https://www.fotmob.com'},
   {'@type': 'ListItem',
    'position': 2,
    'name': 'Serie A',
    'item': 'https://www.fotmob.com/leagues/55/overview/serie'},
   {'@type': 'ListItem',
    'position': 3,
    'name': 'Bologna',
    'item': 'https://www.fotmob.com/teams/9857/overview/bologna'}]},
 'canSyncCalendar': True}

In [7]:
#Serie A table and stats
#data['table']

In [8]:
pd.json_normalize(data['fixtures']['allFixtures']['fixtures'])

,id,pageUrl,displayTournament,result,notStarted,opponent.id,opponent.name,opponent.score,home.id,home.name,...,status.utcTime,status.timezone,status.finished,status.started,status.cancelled,status.scoreStr,status.reason.short,status.reason.shortKey,status.reason.long,status.reason.longKey
0,4264284,/matches/palermo-vs-bologna/2srhec#4264284,True,0.0,False,8540,Palermo,2,9857,Bologna,...,2023-07-22T16:00:00.000Z,UTC,True,True,False,2 - 2,FT,fulltime_short,Full-Time,finished
1,4252990,/matches/bologna-vs-fc-utrecht/38az0r#4252990,True,1.0,False,9908,FC Utrecht,1,9908,FC Utrecht,...,2023-08-02T13:00:00.000Z,UTC,True,True,False,1 - 2,FT,fulltime_short,Full-Time,finished
2,4238555,/matches/bologna-vs-az-alkmaar/3c42cu#4238555,True,-1.0,False,10229,AZ Alkmaar,1,10229,AZ Alkmaar,...,2023-08-05T15:00:00.000Z,UTC,True,True,False,1 - 0,FT,fulltime_short,Full-Time,finished
3,4274676,/matches/bologna-vs-cesena/290g481h#4274676,True,1.0,False,584022,Cesena,0,9857,Bologna,...,2023-08-11T19:15:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
4,4230530,/matches/ac-milan-vs-bologna/2t0ybc#4230530,False,-1.0,False,8564,AC Milan,2,9857,Bologna,...,2023-08-21T18:45:00.000Z,UTC,True,True,False,0 - 2,FT,fulltime_short,Full-Time,finished
5,4230548,/matches/bologna-vs-juventus/3818fi#4230548,False,0.0,False,9885,Juventus,1,9885,Juventus,...,2023-08-27T16:30:00.000Z,UTC,True,True,False,1 - 1,FT,fulltime_short,Full-Time,finished
6,4230552,/matches/cagliari-vs-bologna/2sn5ak#4230552,False,1.0,False,8529,Cagliari,1,9857,Bologna,...,2023-09-02T16:30:00.000Z,UTC,True,True,False,2 - 1,FT,fulltime_short,Full-Time,finished
7,4230568,/matches/bologna-vs-hellas-verona/37xfcr#4230568,False,0.0,False,9876,Hellas Verona,0,9876,Hellas Verona,...,2023-09-18T18:45:00.000Z,UTC,True,True,False,0 - 0,FT,fulltime_short,Full-Time,finished
8,4230572,/matches/bologna-vs-ssc-napoli/37x04l#4230572,False,0.0,False,9875,SSC Napoli,0,9857,Bologna,...,2023-09-24T16:00:00.000Z,UTC,True,True,False,0 - 0,FT,fulltime_short,Full-Time,finished
9,4230589,/matches/monza-vs-bologna/27p2f2#4230589,False,0.0,False,6504,Monza,0,6504,Monza,...,2023-09-28T16:30:00.000Z,UTC,True,True,False,0 - 0,FT,fulltime_short,Full-Time,finished
10,4230592,/matches/empoli-vs-bologna/2sp48l#4230592,False,1.0,False,8534,Empoli,0,9857,Bologna,...,2023-10-01T10:30:00.000Z,UTC,True,True,False,3 - 0,FT,fulltime_short,Full-Time,finished
11,4230609,/matches/inter-vs-bologna/2ttfqc#4230609,False,0.0,False,8636,Inter,2,8636,Inter,...,2023-10-07T13:00:00.000Z,UTC,True,True,False,2 - 2,FT,fulltime_short,Full-Time,finished
12,4230612,/matches/bologna-vs-frosinone/383rul#4230612,False,1.0,False,9891,Frosinone,1,9857,Bologna,...,2023-10-22T13:00:00.000Z,UTC,True,True,False,2 - 1,FT,fulltime_short,Full-Time,finished
13,4230627,/matches/sassuolo-vs-bologna/2mbw4l#4230627,False,0.0,False,7943,Sassuolo,1,7943,Sassuolo,...,2023-10-28T13:00:00.000Z,UTC,True,True,False,1 - 1,FT,fulltime_short,Full-Time,finished
14,4287714,/matches/bologna-vs-hellas-verona/37xfcr#4287714,True,1.0,False,9876,Hellas Verona,0,9857,Bologna,...,2023-10-31T20:00:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
15,4230635,/matches/lazio-vs-bologna/2ssnzl#4230635,False,1.0,False,8543,Lazio,0,9857,Bologna,...,2023-11-03T19:45:00.000Z,UTC,True,True,False,1 - 0,FT,fulltime_short,Full-Time,finished
16,4230649,/matches/fiorentina-vs-bologna/2spifh#4230649,False,-1.0,False,8535,Fiorentina,2,8535,Fiorentina,...,2023-11-12T14:00:00.000Z,UTC,True,True,False,2 - 1,FT,fulltime_short,Full-Time,finished
17,4230655,/matches/torino-vs-bologna/373118#4230655,False,1.0,False,9804,Torino,0,9857,Bologna,...,2023-11-27T19:45:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
18,4230666,/matches/bologna-vs-lecce/382i4x#4230666,False,0.0,False,9888,Lecce,1,9888,Lecce,...,2023-12-03T11:30:00.000Z,UTC,True,True,False,1 - 1,FT,fulltime_short,Full-Time,finished
19,4230681,/matches/salernitana-vs-bologna/27gnne#4230681,False,1.0,False,6480,Salernitana,1,6480,Salernitana,...,2023-12-10T17:00:00.000Z,UTC,True,True,False,1 - 2,FT,fulltime_short,Full-Time,finished
20,4230685,/matches/roma-vs-bologna/2uda6h#4230685,False,1.0,False,8686,Roma,0,9857,Bologna,...,2023-12-17T17:00:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
21,4301267,/matches/inter-vs-bologna/2ttfqc#4301267,True,1.0,False,8636,Inter,1,8636,Inter,...,2023-12-20T20:00:00.000Z,UTC,True,True,False,1 - 2,AET,afterextratime_short,After extra time,afterextra
22,4230698,/matches/atalanta-vs-bologna/2sl6d8#4230698,False,1.0,False,8524,Atalanta,0,9857,Bologna,...,2023-12-23T14:00:00.000Z,UTC,True,True,False,1 - 0,FT,fulltime_short,Full-Time,finished
23,4230711,/matches/udinese-vs-bologna/2tf6iu#4230711,False,-1.0,False,8600,Udinese,3,8600,Udinese,...,2023-12-30T14:00:00.000Z,UTC,True,True,False,3 - 0,FT,fulltime_short,Full-Time,finished
24,4230714,/matches/bologna-vs-genoa/3c5scw#4230714,False,0.0,False,10233,Genoa,1,9857,Bologna,...,2024-01-05T19:45:00.000Z,UTC,True,True,False,1 - 1,FT,fulltime_short,Full-Time,finished
25,4301275,/matches/fiorentina-vs-bologna/2spifh#4301275,True,-1.0,False,8535,Fiorentina,5,8535,Fiorentina,...,2024-01-09T20:00:00.000Z,UTC,True,True,False,0 - 0,Pen,penalties_short,After penalties,afterpenalties
26,4230731,/matches/cagliari-vs-bologna/2sn5ak#4230731,False,-1.0,False,8529,Cagliari,2,8529,Cagliari,...,2024-01-14T14:00:00.000Z,UTC,True,True,False,2 - 1,FT,fulltime_short,Full-Time,finished
27,4230750,/matches/ac-milan-vs-bologna/2t0ybc#4230750,False,0.0,False,8564,AC Milan,2,8564,AC Milan,...,2024-01-27T19:45:00.000Z,UTC,True,True,False,2 - 2,FT,fulltime_short,Full-Time,finished
28,4230755,/matches/sassuolo-vs-bologna/2mbw4l#4230755,False,1.0,False,7943,Sassuolo,2,9857,Bologna,...,2024-02-03T19:45:00.000Z,UTC,True,True,False,4 - 2,FT,fulltime_short,Full-Time,finished
29,4230764,/matches/bologna-vs-lecce/382i4x#4230764,False,1.0,False,9888,Lecce,0,9857,Bologna,...,2024-02-11T14:00:00.000Z,UTC,True,True,False,4 - 0,FT,fulltime_short,Full-Time,finished
30,4230734,/matches/fiorentina-vs-bologna/2spifh#4230734,False,1.0,False,8535,Fiorentina,0,9857,Bologna,...,2024-02-14T18:00:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
31,4230779,/matches/lazio-vs-bologna/2ssnzl#4230779,False,1.0,False,8543,Lazio,1,8543,Lazio,...,2024-02-18T11:30:00.000Z,UTC,True,True,False,1 - 2,FT,fulltime_short,Full-Time,finished
32,4230784,/matches/bologna-vs-hellas-verona/37xfcr#4230784,False,1.0,False,9876,Hellas Verona,0,9857,Bologna,...,2024-02-23T19:45:00.000Z,UTC,True,True,False,2 - 0,FT,fulltime_short,Full-Time,finished
33,4230794,/matches/atalanta-vs-bologna/2sl6d8#4230794,False,1.0,False,8524,Atalanta,1,8524,Atalanta,...,2024-03-03T17:00:00.000Z,UTC,True,True,False,1 - 2,FT,fulltime_short,Full-Time,finished
34,4230804,/matches/inter-vs-bologna/2ttfqc#4230804,False,NaN,True,8636,Inter,0,9857,Bologna,...,2024-03-09T17:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
35,4230829,/matches/empoli-vs-bologna/2sp48l#4230829,False,NaN,True,8534,Empoli,0,8534,Empoli,...,2024-03-15T19:45:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
36,4230834,/matches/salernitana-vs-bologna/27gnne#4230834,False,NaN,True,6480,Salernitana,0,9857,Bologna,...,2024-04-01T10:30:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
37,4230814,/matches/bologna-vs-frosinone/383rul#4230814,False,NaN,True,9891,Frosinone,0,9891,Frosinone,...,2024-04-07T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
38,4230845,/matches/monza-vs-bologna/27p2f2#4230845,False,NaN,True,6504,Monza,0,9857,Bologna,...,2024-04-14T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
39,4230859,/matches/roma-vs-bologna/2uda6h#4230859,False,NaN,True,8686,Roma,0,8686,Roma,...,2024-04-21T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
40,4230865,/matches/udinese-vs-bologna/2tf6iu#4230865,False,NaN,True,8600,Udinese,0,9857,Bologna,...,2024-04-28T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
41,4230877,/matches/torino-vs-bologna/373118#4230877,False,NaN,True,9804,Torino,0,9804,Torino,...,2024-05-05T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
42,4230891,/matches/bologna-vs-ssc-napoli/37x04l#4230891,False,NaN,True,9875,SSC Napoli,0,9875,SSC Napoli,...,2024-05-12T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
43,4230894,/matches/bologna-vs-juventus/3818fi#4230894,False,NaN,True,9885,Juventus,0,9857,Bologna,...,2024-05-19T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN
44,4230912,/matches/bologna-vs-genoa/3c5scw#4230912,False,NaN,True,10233,Genoa,0,10233,Genoa,...,2024-05-26T16:00:00.000Z,UTC,False,False,False,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.json_normalize(data['squad'])

         title                                            members
0        coach  [{'id': 26852, 'name': 'Thiago Motta', 'ccode'...
1      keepers  [{'id': 178732, 'name': 'Lukasz Skorupski', 's...
2    defenders  [{'id': 25587, 'name': 'Lorenzo De Silvestri',...
3  midfielders  [{'id': 201704, 'name': 'Remo Freuler', 'shirt...
4    attackers  [{'id': 661761, 'name': 'Riccardo Orsolini', '...

In [10]:
pd.json_normalize(data['squad'][0]['members'])

      id          name ccode  cname  excludeFromRanking role.key role.fallback
0  26852  Thiago Motta   ITA  Italy                True    coach         Coach

In [11]:
pd.json_normalize(data['squad'][1]['members'])

,id,name,shirtNumber,ccode,cname,positionId,rating,goals,penalties,assists,rcards,ycards,excludeFromRanking,role.key,role.fallback
0,178732,Lukasz Skorupski,28,POL,Poland,0,6.8,0,0,0,0,2,False,keeper_long,Keeper
1,793041,Federico Ravaglia,34,ITA,Italy,0,7.3,0,0,0,0,0,True,keeper_long,Keeper
2,1301935,Nicola Bagnolini,23,ITA,Italy,0,NaN,0,0,0,0,0,True,keeper_long,Keeper

In [12]:
pd.json_normalize(data['squad'][2]['members'])

,id,name,shirtNumber,ccode,cname,positionId,rating,goals,penalties,assists,rcards,ycards,excludeFromRanking,role.key,role.fallback,injured
0,25587,Lorenzo De Silvestri,29,ITA,Italy,1,6.63,2,0,0,0,0,True,defender_long,Defender,NaN
1,357881,Adama Soumaoro,5,CIV,Ivory Coast,1,NaN,0,0,0,0,0,True,defender_long,Defender,True
2,395914,Charalambos Lykogiannis,22,GRE,Greece,1,6.60,1,0,1,0,1,False,defender_long,Defender,NaN
3,557325,Stefan Posch,3,AUT,Austria,1,7.03,0,0,2,0,7,False,defender_long,Defender,NaN
4,860913,Jhon Lucumi,26,COL,Colombia,1,7.13,0,0,0,0,1,False,defender_long,Defender,NaN
5,873573,Sam Beukema,31,NED,Netherlands,1,7.07,1,0,1,0,3,False,defender_long,Defender,NaN
6,1105912,Riccardo Calafiori,33,ITA,Italy,1,7.27,0,0,2,0,4,False,defender_long,Defender,NaN
7,1211437,Victor Kristiansen,15,DEN,Denmark,1,6.87,0,0,3,0,3,False,defender_long,Defender,NaN
8,1343910,Mihajlo Ilic,4,SRB,Serbia,1,NaN,0,0,0,0,0,True,defender_long,Defender,NaN
9,1526283,Tommaso Corazza,16,ITA,Italy,1,6.53,0,0,0,0,1,True,defender_long,Defender,NaN

In [13]:
pd.json_normalize(data['squad'][3]['members'])

,id,name,shirtNumber,ccode,cname,positionId,rating,goals,penalties,assists,rcards,ycards,excludeFromRanking,role.key,role.fallback
0,201704,Remo Freuler,8,SUI,Switzerland,2,7.10,1,0,0,0,6,False,midfielder_long,Midfielder
1,641595,Nikola Moro,6,CRO,Croatia,2,6.55,1,0,0,0,0,False,midfielder_long,Midfielder
2,792756,Michel Aebischer,20,SUI,Switzerland,2,6.81,0,0,1,0,6,False,midfielder_long,Midfielder
3,888921,Lewis Ferguson,19,SCO,Scotland,2,7.39,6,0,3,0,7,False,midfielder_long,Midfielder
4,1254425,Kazper Karlsson,0,SWE,Sweden,2,NaN,0,0,0,0,0,True,midfielder_long,Midfielder
5,1276505,Giovanni Fabbian,80,ITA,Italy,2,6.98,4,0,2,0,3,False,midfielder_long,Midfielder
6,1283469,Oussama El Azzouzi,17,MAR,Morocco,2,6.77,1,0,1,0,3,True,midfielder_long,Midfielder

In [14]:
pd.json_normalize(data['squad'][4]['members'])

,id,name,shirtNumber,ccode,cname,positionId,rating,goals,penalties,assists,rcards,ycards,excludeFromRanking,role.key,role.fallback
0,661761,Riccardo Orsolini,7,ITA,Italy,3,7.20,9,2,2,0,1,False,attacker_long,Attacker
1,689680,Jens Odgaard,21,DEN,Denmark,3,7.20,2,0,0,0,1,True,attacker_long,Attacker
2,737061,Jesper Karlsson,10,SWE,Sweden,3,6.72,0,0,0,0,0,True,attacker_long,Attacker
3,921341,Alexis Saelemaekers,56,BEL,Belgium,3,7.02,1,0,1,1,5,False,attacker_long,Attacker
4,950830,Joshua Zirkzee,9,NED,Netherlands,3,7.32,10,2,3,0,5,False,attacker_long,Attacker
5,1022649,Dan Ndoye,11,SUI,Switzerland,3,6.82,0,0,1,0,3,False,attacker_long,Attacker
6,1121295,Kacper Urbanski,82,POL,Poland,3,6.61,0,0,0,0,3,True,attacker_long,Attacker
7,1282008,Santiago Castro,0,ARG,Argentina,3,NaN,0,0,0,0,0,True,attacker_long,Attacker

In [15]:
#all Bologna player rankings for various stats/metrics, from [0] (goals scored) to [33] (Red cards)
#data['stats']['players']

In [16]:
pd.json_normalize(data['stats']['players'][5]['topThree']).T

,0,1,2
id,950830,661761,888921
name,Joshua Zirkzee,Riccardo Orsolini,Lewis Ferguson
rank,9,20,34
ccode,NED,ITA,SCO
teamId,9857,9857,9857
teamName,Bologna,Bologna,Bologna
value,8.1,5.7,4.4
stat.name,expected_goals,expected_goals,expected_goals
stat.value,8.1,5.7,4.4
stat.format,fraction,fraction,fraction
stat.fractions,1,1,1
teamColors.darkMode,#203faf,#203faf,#203faf
teamColors.lightMode,#102880,#102880,#102880
teamColors.fontDarkMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"
teamColors.fontLightMode,"rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)","rgba(255, 255, 255, 1.0)"

In [17]:
#accessing the full list for all Serie A players
xG = requests.get(data['stats']['players'][5]['fetchAllUrl'])
xG = xG.json()
pd.json_normalize(xG['TopLists'][0]['StatList'])

,ParticipantName,ParticiantId,TeamId,TeamColor,StatValue,SubStatValue,MinutesPlayed,MatchesPlayed,StatValueCount,Rank,ParticipantCountryCode,TeamName
0,Lautaro Martinez,690230,8636,#010E80,14.6,23.0,2036,25,24,1,ARG,Internazionale
1,Dusan Vlahovic,737857,9885,#000001,13.1,15.0,1680,24,23,2,SRB,Juventus
2,Marcus Thuram,621562,8636,#010E80,11.8,10.0,1867,25,20,3,FRA,Internazionale
3,Olivier Giroud,46469,8564,#CF2C27,11.2,12.0,1810,24,22,4,FRA,Milan
4,Victor Osimhen,687681,9875,#12A0D7,9.3,11.0,1248,16,15,5,NGA,Napoli
...,...,...,...,...,...,...,...,...,...,...,...,...
456,Marcin Listkowski,645704,9888,#e12300,0.0,0.0,7,1,1,436,POL,Lecce
457,Pablo Galdames,522083,10233,#CB1111,0.0,0.0,9,2,1,436,CHI,Genoa
458,Pierluigi Gollini,553849,9875,#12A0D7,0.0,0.0,630,7,1,436,ITA,Napoli
459,Rafael Toloi,127374,8524,#004ca6,0.0,0.0,444,10,1,436,ITA,Atalanta
460,Reda Belahyane,1388071,9876,#002F6C,0.0,0.0,16,1,1,436,FRA,Verona

*There is actually a longer xG rankings list for Bologna players, but (seemingly?) not in the json/script, here's the list for xG for instance: https://www.fotmob.com/leagues/55/stats/season/20956/players/expected_goals/team/9857/bologna-players*

In [18]:
#all Serie A team stats/rankings [0] (FotMob rating) to [24] (Red cards)
#data['stats']['teams']

In [19]:
pd.json_normalize(data['history']['trophyList'])

,name,tournamentTemplateId,area,ccode,won,runnerup,season_won,season_runnerup
0,[Serie A],[55],[Italy],[ITA],[7],[3],"[1963/1964,1940/1941,1938/1939,1936/1937,1935/...","[1965/1966,1939/1940,1931/1932]"
1,[Serie B],[86],[Italy],[ITA],[2],[1],"[1995/1996,1987/1988]",[2007/2008]
2,[Coppa Italia],[141],[Italy],[ITA],[2],[0],"[1973/1974,1969/1970]",[]

In [20]:
pd.json_normalize(data['history']['historicalTableData']['ranks'])

,stageId,tournamentName,tournamentId,templateId,seasonName,position,numberOfTeams,tableLink,isConsecutive,stats.points,stats.wins,stats.draws,stats.loss
0,821429,Serie A,5507,55,2010/2011,16,20,https://data.fotmob.com/historic/55/season/550...,True,42,11,12,15
1,824735,Serie A,6320,55,2011/2012,9,20,https://data.fotmob.com/historic/55/season/632...,True,51,13,12,13
2,828290,Serie A,7122,55,2012/2013,13,20,https://data.fotmob.com/historic/55/season/712...,True,44,11,11,16
3,832688,Serie A,7956,55,2013/2014,19,20,https://data.fotmob.com/historic/55/season/795...,True,29,5,14,19
4,836592,Serie B,8820,86,2014/2015,4,22,https://data.fotmob.com/historic/86/season/882...,True,68,17,17,8
5,841062,Serie A,9734,55,2015/2016,14,20,https://data.fotmob.com/historic/55/season/973...,True,42,11,9,18
6,845699,Serie A,10692,55,2016/2017,15,20,https://data.fotmob.com/historic/55/season/106...,True,41,11,8,19
7,850756,Serie A,11768,55,2017/2018,15,20,https://data.fotmob.com/historic/55/season/117...,True,39,11,6,21
8,856689,Serie A,13037,55,2018/2019,10,20,https://data.fotmob.com/historic/55/season/130...,True,44,11,11,16
9,863056,Serie A,14290,55,2019/2020,12,20,https://data.fotmob.com/historic/55/season/142...,True,47,12,11,15
10,869410,Serie A,15604,55,2020/2021,12,20,https://data.fotmob.com/historic/55/season/156...,True,41,10,11,17
11,874287,Serie A,16621,55,2021/2022,13,20,https://data.fotmob.com/historic/55/season/166...,True,46,12,10,16
12,880067,Serie A,17866,55,2022/2023,9,20,https://data.fotmob.com/historic/55/season/178...,True,54,14,12,12
13,885919,Serie A,20956,55,2023/2024,4,20,https://data.fotmob.com/tables.ext.55.fot,True,51,14,9,4

In [21]:
pd.json_normalize(data['history']['tables']['current'][0]['link'])

,_,name,ccode,season,stage_id,tournament_id,template_id,league_id
0,tables.ext.55.fot,[Serie A],[ITA],[2023/2024],[885919],[20956],[55],[55]

In [22]:
pd.json_normalize(data['history']['tables']['historic'][0]['link'])

,_,name,ccode,season,stage_id,tournament_id,template_id,league_id
0,historic/55/season/17866/table.fot,[Serie A],[ITA],[2022/2023],[880067],[17866],[55],[55]
1,historic/55/season/16621/table.fot,[Serie A],[ITA],[2021/2022],[874287],[16621],[55],[55]
2,historic/55/season/15604/table.fot,[Serie A],[ITA],[2020/2021],[869410],[15604],[55],[55]
3,historic/55/season/14290/table.fot,[Serie A],[ITA],[2019/2020],[863056],[14290],[55],[55]
4,historic/55/season/13037/table.fot,[Serie A],[ITA],[2018/2019],[856689],[13037],[55],[55]
5,historic/55/season/11768/table.fot,[Serie A],[ITA],[2017/2018],[850756],[11768],[55],[55]
6,historic/55/season/10692/table.fot,[Serie A],[ITA],[2016/2017],[845699],[10692],[55],[55]
7,historic/55/season/9734/table.fot,[Serie A],[ITA],[2015/2016],[841062],[9734],[55],[55]
8,historic/86/season/8820/table.fot,[Serie B],[ITA],[2014/2015],[836592],[8820],[86],[836592]
9,historic/55/season/7956/table.fot,[Serie A],[ITA],[2013/2014],[832688],[7956],[55],[55]
10,historic/55/season/7122/table.fot,[Serie A],[ITA],[2012/2013],[828290],[7122],[55],[55]
11,historic/55/season/6320/table.fot,[Serie A],[ITA],[2011/2012],[824735],[6320],[55],[55]
12,historic/55/season/5507/table.fot,[Serie A],[ITA],[2010/2011],[821429],[5507],[55],[55]